"""Report generation endpoints for Imaging Intelligence Agent.

POST /reports/generate -- Generate a structured clinical report
from a RAG query, including evidence citations and optional PDF output.

Author: Adam Jones
Date: February 2026
"""

import time
from datetime import datetime
from typing import Any, Dict, List, Optional

from fastapi import APIRouter, HTTPException
from loguru import logger
from pydantic import BaseModel, Field
from starlette.responses import Response

# =====================================================================
# Request / Response Models
# =====================================================================


class ReportRequest(BaseModel):
    """Report generation request."""
    question: str = Field(..., min_length=3, max_length=2000, description="Clinical question")
    modality: Optional[str] = Field(None, description="Imaging modality filter")
    body_region: Optional[str] = Field(None, description="Body region filter")
    top_k: int = Field(5, ge=1, le=30, description="Results per collection")
    format: str = Field("markdown", description="Output format: markdown, json, or pdf")
    include_evidence: bool = Field(True, description="Include evidence citations in report")
    report_title: str = Field("", description="Custom report title (optional)")


class EvidenceCitation(BaseModel):
    """A single evidence citation in the report."""
    collection: str
    id: str
    score: float
    text_snippet: str = ""
    label: str = ""


class ReportResponse(BaseModel):
    """Generated report response (for markdown and json formats)."""
    title: str
    generated_at: str
    question: str
    answer: str
    evidence: List[EvidenceCitation] = []
    evidence_count: int
    collections_searched: int
    search_time_ms: float
    generation_time_ms: float
    format: str
    content: str = Field("", description="Full rendered report content (markdown or json string)")


# =====================================================================
# Report Rendering
# =====================================================================


def _render_markdown_report(
    title: str,
    question: str,
    answer: str,
    evidence: List[EvidenceCitation],
    search_time_ms: float,
) -> str:
    """Render a Markdown-formatted clinical report."""
    lines = [
        f"# {title}",
        "",
        f"**Generated:** {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}",
        f"**Search time:** {search_time_ms:.0f}ms",
        "",
        "---",
        "",
        "## Clinical Question",
        "",
        question,
        "",
        "## Analysis",
        "",
        answer,
        "",
    ]

    if evidence:
        lines.extend([
            "---",
            "",
            f"## Evidence ({len(evidence)} citations)",
            "",
        ])
        for i, cite in enumerate(evidence, 1):
            score_pct = cite.score * 100
            lines.append(
                f"{i}. **[{cite.label or cite.collection}]** "
                f"`{cite.id}` (relevance: {score_pct:.1f}%)"
            )
            if cite.text_snippet:
                lines.append(f"   > {cite.text_snippet[:300]}")
            lines.append("")

    lines.extend([
        "---",
        "",
        "*This report was generated by the HCLS AI Factory -- Imaging Intelligence Agent. "
        "All findings require verification by a qualified radiologist. "
        "For research purposes only.*",
    ])

    return "\n".join(lines)


def _render_pdf_report(
    title: str,
    question: str,
    answer: str,
    evidence: List[EvidenceCitation],
    search_time_ms: float,
) -> bytes:
    """Render an NVIDIA-branded PDF report using reportlab."""
    from io import BytesIO

    from reportlab.lib.pagesizes import letter
    from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
    from reportlab.lib.units import inch
    from reportlab.platypus import (
        Paragraph, SimpleDocTemplate, Spacer, Table, TableStyle,
    )
    from reportlab.platypus.flowables import HRFlowable
    from reportlab.lib import colors

    # NVIDIA branding
    nvidia_green = colors.Color(118 / 255, 185 / 255, 0 / 255)
    nvidia_dark = colors.Color(30 / 255, 30 / 255, 30 / 255)

    buffer = BytesIO()
    doc = SimpleDocTemplate(
        buffer, pagesize=letter,
        topMargin=40, bottomMargin=40, leftMargin=40, rightMargin=40,
    )
    styles = getSampleStyleSheet()

    # Custom styles
    nv_title = ParagraphStyle(
        "NVTitle", parent=styles["Title"],
        textColor=colors.white, fontSize=20, leading=24, spaceAfter=6,
    )
    nv_heading = ParagraphStyle(
        "NVHeading", parent=styles["Heading2"],
        textColor=nvidia_dark, fontSize=14, leading=18,
        spaceBefore=16, spaceAfter=8,
    )
    nv_body = ParagraphStyle(
        "NVBody", parent=styles["BodyText"], fontSize=10, leading=13,
    )
    nv_disclaimer = ParagraphStyle(
        "NVDisclaimer", parent=styles["BodyText"],
        fontSize=7, leading=9, textColor=colors.gray,
    )

    story = []

    # ── Green Header Bar ──
    header_data = [[Paragraph(title, nv_title)]]
    header_table = Table(header_data, colWidths=[7.3 * inch], rowHeights=[50])
    header_table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, -1), nvidia_green),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ("LEFTPADDING", (0, 0), (-1, -1), 12),
    ]))
    story.append(header_table)
    story.append(Spacer(1, 12))

    # Metadata
    story.append(Paragraph(
        f"<b>Generated:</b> {datetime.now().strftime('%Y-%m-%d %H:%M:%S')} &nbsp;|&nbsp; "
        f"<b>Search time:</b> {search_time_ms:.0f} ms",
        nv_body,
    ))
    story.append(Spacer(1, 12))

    # ── Clinical Question ──
    story.append(Paragraph("Clinical Question", nv_heading))
    story.append(Paragraph(question, nv_body))
    story.append(Spacer(1, 12))

    # ── Analysis ──
    story.append(Paragraph("Analysis", nv_heading))
    for para in answer.split("\n\n"):
        cleaned = para.strip().replace("\n", "<br/>")
        # Convert markdown bold/italic to HTML tags for ReportLab
        import re as _re
        cleaned = _re.sub(r'\*\*(.+?)\*\*', r'<b>\1</b>', cleaned)
        cleaned = _re.sub(r'__(.+?)__', r'<b>\1</b>', cleaned)
        cleaned = _re.sub(r'\*(.+?)\*', r'<i>\1</i>', cleaned)
        if cleaned:
            story.append(Paragraph(cleaned, nv_body))
            story.append(Spacer(1, 6))
    story.append(Spacer(1, 12))

    # ── Evidence Table ──
    if evidence:
        story.append(Paragraph(f"Evidence ({len(evidence)} citations)", nv_heading))
        table_data = [["#", "Collection", "ID", "Score", "Summary"]]
        for i, cite in enumerate(evidence[:15], 1):
            table_data.append([
                str(i),
                cite.label or cite.collection,
                cite.id[:20],
                f"{cite.score * 100:.1f}%",
                (cite.text_snippet or "")[:120],
            ])
        t = Table(table_data, colWidths=[0.3 * inch, 1.1 * inch, 1.0 * inch, 0.6 * inch, 4.3 * inch],
                  repeatRows=1)
        t.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), nvidia_green),
            ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
            ("FONTSIZE", (0, 0), (-1, 0), 9),
            ("FONTSIZE", (0, 1), (-1, -1), 7),
            ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
            ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.whitesmoke, colors.white]),
            ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
            ("LEFTPADDING", (0, 0), (-1, -1), 4),
            ("RIGHTPADDING", (0, 0), (-1, -1), 4),
        ]))
        story.append(t)

    # ── Footer ──
    story.append(Spacer(1, 24))
    story.append(HRFlowable(width="100%", thickness=1, color=colors.grey))
    story.append(Spacer(1, 6))
    story.append(Paragraph(
        "This report was generated by the HCLS AI Factory — Imaging Intelligence Agent. "
        "All findings require verification by a qualified radiologist. "
        "Research use only. Not for clinical decision-making.",
        nv_disclaimer,
    ))

    doc.build(story)
    return buffer.getvalue()


# =====================================================================
# Router
# =====================================================================

router = APIRouter()


def _get_state():
    """Import and access the shared application state from api.main."""
    from api.main import _state
    return _state


@router.post("/reports/generate")
async def generate_report(request: ReportRequest):
    """Generate a structured clinical report from a RAG query.

    Supports three output formats:
      - markdown: Returns ReportResponse with rendered Markdown in `content`
      - json: Returns ReportResponse with full structured data
      - pdf: Returns binary PDF file as download

    The report includes:
      - Clinical question
      - RAG-synthesized analysis
      - Evidence citations with relevance scores
      - Timestamp and metadata
    """
    start = time.time()
    state = _get_state()

    engine = state.get("engine")
    if engine is None:
        raise HTTPException(status_code=503, detail="Agent engine not initialized")

    # Build search kwargs
    kwargs = {"top_k_per_collection": request.top_k}
    if request.modality:
        kwargs["modality_filter"] = request.modality

    try:
        # Retrieve evidence
        evidence = engine.retrieve(request.question, **kwargs)

        # Synthesize answer
        answer = engine.query(request.question, **kwargs)
    except Exception as e:
        logger.error(f"Report generation failed during RAG: {e}")
        raise HTTPException(status_code=500, detail="Internal processing error")

    # Build evidence citations
    from src.rag_engine import COLLECTION_CONFIG

    citations = []
    if request.include_evidence:
        for hit in evidence.hits[:20]:
            config = COLLECTION_CONFIG.get(hit.collection, {})
            citations.append(EvidenceCitation(
                collection=hit.collection,
                id=hit.id,
                score=hit.score,
                text_snippet=hit.text[:500] if hit.text else "",
                label=config.get("label", hit.collection),
            ))

    title = request.report_title or f"Imaging Intelligence Report: {request.question[:80]}"
    generation_time_ms = (time.time() - start) * 1000

    # Handle PDF format -- return binary response
    if request.format == "pdf":
        try:
            pdf_bytes = _render_pdf_report(
                title=title,
                question=request.question,
                answer=answer,
                evidence=citations,
                search_time_ms=evidence.search_time_ms,
            )
            return Response(
                content=pdf_bytes,
                media_type="application/pdf",
                headers={
                    "Content-Disposition": (
                        f'attachment; filename="imaging_report_'
                        f'{datetime.now().strftime("%Y%m%d_%H%M%S")}.pdf"'
                    )
                },
            )
        except ImportError:
            raise HTTPException(
                status_code=501,
                detail="PDF generation requires the reportlab package",
            )
        except Exception as e:
            logger.error(f"PDF generation failed: {e}")
            raise HTTPException(status_code=500, detail="Internal processing error")

    # Markdown or JSON format
    content = ""
    if request.format == "markdown":
        content = _render_markdown_report(
            title=title,
            question=request.question,
            answer=answer,
            evidence=citations,
            search_time_ms=evidence.search_time_ms,
        )

    return ReportResponse(
        title=title,
        generated_at=datetime.now().isoformat(),
        question=request.question,
        answer=answer,
        evidence=citations,
        evidence_count=evidence.hit_count,
        collections_searched=evidence.total_collections_searched,
        search_time_ms=evidence.search_time_ms,
        generation_time_ms=generation_time_ms,
        format=request.format,
        content=content,
    )
