"""
Knowledge Connections Database (Clinker-style semantic layer)

This module provides the knowledge graph that connects:
Variant -> Gene -> Protein -> Pathway -> Disease -> Drug

Used by both the RAG engine (for Claude context) and the UI (for visualization).

Coverage: 201 high-value genes across 13 therapeutic areas:
- Neurology/Neurodegeneration (36 genes) - VCP, C9orf72, MAPT, APP, HTT, CGRP, SCN9A, TREM2
- Oncology (27 genes) - BRCA, EGFR, KRAS, ALK, checkpoint inhibitors
- Metabolic/Endocrine (22 genes) - GLP1R, SGLT2, MC4R, HMGCR
- Infectious Disease (21 genes) - HIV, HCV, SARS-CoV-2, TB, fungal
- Respiratory/Pulmonary (13 genes) - ADRB2, IL4R, BMPR2, SERPINA1
- Rare Disease (12 genes) - CFTR, SMN1, DMD, HBB
- Hematology (12 genes) - SYK, THPO, F10, ADAMTS13, VWF
- GI/Hepatology (12 genes) - ATP4A, S1PR1, THR_BETA, FXR
- Ophthalmology (11 genes) - VEGFA, CFH, RPE65, ROCK1
- Pharmacogenomics (11 genes) - CYP2D6, CYP2C19, DPYD, TPMT
- Cardiovascular (10 genes) - PCSK9, TTR, MYBPC3, SCN5A
- Immunology/Inflammation (9 genes) - IL6, TNF, JAK1/2, IL17A
- Dermatology (9 genes) - IL31RA, TYK2, COL7A1, KIT

85% of genes (171/201) are druggable with FDA-approved drugs or clinical candidates.
"""

from typing import Dict, List, Any, Optional


# =============================================================================
# KNOWLEDGE CONNECTION DATABASE
# =============================================================================

KNOWLEDGE_CONNECTIONS: Dict[str, Dict[str, Any]] = {

    # =========================================================================
    # NEURODEGENERATION / FTD / ALS (Original + Expanded)
    # =========================================================================

    'VCP': {
        'protein': 'p97/VCP ATPase',
        'function': 'Protein quality control, ERAD, autophagy',
        'pathway': 'Ubiquitin-proteasome system',
        'diseases': ['Frontotemporal Dementia (FTD)', 'ALS', 'IBMPFD', 'Paget Disease'],
        'drugs': ['CB-5083 (Phase I)', 'NMS-873', 'DBeQ'],
        'drug_status': 'Clinical development',
        'pdb_ids': ['5FTK', '7K56', '8OOI'],
        'druggable': True,
    },
    'GRN': {
        'protein': 'Progranulin',
        'function': 'Neurotrophic factor, lysosomal function',
        'pathway': 'Lysosomal pathway',
        'diseases': ['Frontotemporal Dementia (FTD)', 'Neuronal Ceroid Lipofuscinosis'],
        'drugs': ['Latozinemab (AL001)', 'Gene therapy (PR006)'],
        'drug_status': 'Phase II/III',
        'pdb_ids': ['2JYE'],
        'druggable': True,
    },
    'C9orf72': {
        'protein': 'C9orf72 protein',
        'function': 'Autophagy regulation, vesicle trafficking',
        'pathway': 'Autophagy pathway',
        'diseases': ['Frontotemporal Dementia (FTD)', 'ALS'],
        'drugs': ['ASO therapies (BIIB078)', 'WVE-004'],
        'drug_status': 'Phase I/II',
        'pdb_ids': ['6LT0'],
        'druggable': False,
    },
    'MAPT': {
        'protein': 'Tau protein',
        'function': 'Microtubule stabilization',
        'pathway': 'Cytoskeleton organization',
        'diseases': ['Frontotemporal Dementia (FTD)', 'Alzheimer Disease', 'PSP'],
        'drugs': ['Tau antibodies (Semorinemab)', 'ASO (BIIB080)', 'Gosuranemab'],
        'drug_status': 'Phase II',
        'pdb_ids': ['6QJH', '5O3L'],
        'druggable': True,
    },
    'TBK1': {
        'protein': 'TANK-binding kinase 1',
        'function': 'Innate immunity, autophagy',
        'pathway': 'Autophagy/inflammation',
        'diseases': ['ALS', 'Frontotemporal Dementia (FTD)'],
        'drugs': ['Kinase inhibitors (research)', 'BX795'],
        'drug_status': 'Preclinical',
        'pdb_ids': ['4IWO', '4EUT'],
        'druggable': True,
    },
    'FUS': {
        'protein': 'FUS RNA-binding protein',
        'function': 'RNA processing, DNA repair',
        'pathway': 'RNA metabolism',
        'diseases': ['ALS', 'Frontotemporal Dementia (FTD)'],
        'drugs': ['ASO therapies (ION363)', 'Jacifusen'],
        'drug_status': 'Phase III',
        'pdb_ids': ['6G99', '5W3N'],
        'druggable': False,
    },
    'TARDBP': {
        'protein': 'TDP-43',
        'function': 'RNA processing, splicing',
        'pathway': 'RNA metabolism',
        'diseases': ['ALS', 'Frontotemporal Dementia (FTD)'],
        'drugs': ['ASO therapies (research)', 'BIIB105'],
        'drug_status': 'Phase I',
        'pdb_ids': ['4BS2', '5MDI'],
        'druggable': False,
    },
    'SOD1': {
        'protein': 'Superoxide dismutase 1',
        'function': 'Antioxidant defense',
        'pathway': 'Oxidative stress response',
        'diseases': ['ALS (familial)', 'ALS2'],
        'drugs': ['Tofersen (Qalsody)', 'ASO therapy'],
        'drug_status': 'FDA Approved (2023)',
        'pdb_ids': ['1PU0', '2C9V'],
        'druggable': True,
    },
    'APP': {
        'protein': 'Amyloid precursor protein',
        'function': 'Cell adhesion, signaling',
        'pathway': 'Amyloid processing',
        'diseases': ['Alzheimer Disease', 'Cerebral Amyloid Angiopathy'],
        'drugs': ['Lecanemab (Leqembi)', 'Donanemab', 'Aducanumab'],
        'drug_status': 'FDA Approved',
        'pdb_ids': ['1AAP', '3NYL'],
        'druggable': True,
    },
    'PSEN1': {
        'protein': 'Presenilin-1',
        'function': 'Gamma-secretase component',
        'pathway': 'Amyloid processing',
        'diseases': ['Alzheimer Disease (early-onset)', 'Familial AD'],
        'drugs': ['Gamma-secretase modulators', 'Semagacestat (discontinued)'],
        'drug_status': 'Research',
        'pdb_ids': ['5A63', '6IYC'],
        'druggable': True,
    },
    'PSEN2': {
        'protein': 'Presenilin-2',
        'function': 'Gamma-secretase component',
        'pathway': 'Amyloid processing',
        'diseases': ['Alzheimer Disease (early-onset)'],
        'drugs': ['Gamma-secretase modulators'],
        'drug_status': 'Research',
        'pdb_ids': ['5A63'],
        'druggable': True,
    },
    'LRRK2': {
        'protein': 'Leucine-rich repeat kinase 2',
        'function': 'Kinase signaling, vesicle trafficking',
        'pathway': 'Autophagy/lysosomal pathway',
        'diseases': ['Parkinson Disease', 'Familial PD'],
        'drugs': ['DNL201', 'BIIB122', 'Denali LRRK2 inhibitors'],
        'drug_status': 'Phase II',
        'pdb_ids': ['6VNO', '7LHW'],
        'druggable': True,
    },
    'SNCA': {
        'protein': 'Alpha-synuclein',
        'function': 'Synaptic vesicle regulation',
        'pathway': 'Dopamine signaling',
        'diseases': ['Parkinson Disease', 'Lewy Body Dementia', 'MSA'],
        'drugs': ['Prasinezumab', 'BIIB054', 'Anle138b'],
        'drug_status': 'Phase II',
        'pdb_ids': ['1XQ8', '2N0A'],
        'druggable': True,
    },
    'HTT': {
        'protein': 'Huntingtin',
        'function': 'Vesicle transport, transcription',
        'pathway': 'Neuronal signaling',
        'diseases': ['Huntington Disease'],
        'drugs': ['Tominersen (halted)', 'WVE-120101', 'AMT-130 (gene therapy)'],
        'drug_status': 'Phase I/II',
        'pdb_ids': ['3IO4', '6EZ8'],
        'druggable': False,
    },
    'PARK7': {
        'protein': 'DJ-1 protein',
        'function': 'Oxidative stress sensor',
        'pathway': 'Mitochondrial quality control',
        'diseases': ['Parkinson Disease (PARK7)', 'Early-onset PD'],
        'drugs': ['Antioxidant therapies (research)'],
        'drug_status': 'Research',
        'pdb_ids': ['1P5F', '1SOA'],
        'druggable': False,
    },
    'PINK1': {
        'protein': 'PTEN-induced kinase 1',
        'function': 'Mitophagy initiation',
        'pathway': 'PINK1/Parkin mitophagy',
        'diseases': ['Parkinson Disease (PARK6)', 'Early-onset PD'],
        'drugs': ['Kinetin (PINK1 activator)', 'USP30 inhibitors'],
        'drug_status': 'Preclinical',
        'pdb_ids': ['5TR5', '6EQI'],
        'druggable': True,
    },
    'PRKN': {
        'protein': 'Parkin E3 ubiquitin ligase',
        'function': 'Mitophagy execution',
        'pathway': 'PINK1/Parkin mitophagy',
        'diseases': ['Parkinson Disease (PARK2)', 'Juvenile PD'],
        'drugs': ['Gene therapy (research)'],
        'drug_status': 'Research',
        'pdb_ids': ['4K95', '5C1Z'],
        'druggable': False,
    },
    'OPTN': {
        'protein': 'Optineurin',
        'function': 'Autophagy receptor',
        'pathway': 'Selective autophagy',
        'diseases': ['ALS', 'Glaucoma', 'Paget Disease'],
        'drugs': ['Autophagy modulators (research)'],
        'drug_status': 'Research',
        'pdb_ids': ['5B83'],
        'druggable': False,
    },
    'SQSTM1': {
        'protein': 'Sequestosome-1 (p62)',
        'function': 'Autophagy receptor',
        'pathway': 'Selective autophagy',
        'diseases': ['ALS', 'FTD', 'Paget Disease'],
        'drugs': ['Autophagy modulators'],
        'drug_status': 'Research',
        'pdb_ids': ['2KKC', '4UF8'],
        'druggable': False,
    },
    'ATXN1': {
        'protein': 'Ataxin-1',
        'function': 'Transcriptional regulation',
        'pathway': 'PolyQ aggregation',
        'diseases': ['Spinocerebellar Ataxia Type 1'],
        'drugs': ['ASO therapy (research)'],
        'drug_status': 'Research',
        'pdb_ids': ['1OA8'],
        'druggable': True,
    },
    'ATXN2': {
        'protein': 'Ataxin-2',
        'function': 'RNA metabolism',
        'pathway': 'Stress granules',
        'diseases': ['Spinocerebellar Ataxia Type 2', 'ALS (modifier)'],
        'drugs': ['ION541 (ASO)'],
        'drug_status': 'Phase I',
        'pdb_ids': ['4OFR'],
        'druggable': True,
    },
    'ATXN3': {
        'protein': 'Ataxin-3',
        'function': 'Deubiquitinase',
        'pathway': 'Ubiquitin signaling',
        'diseases': ['Spinocerebellar Ataxia Type 3 (Machado-Joseph Disease)'],
        'drugs': ['Gene therapy (research)'],
        'drug_status': 'Preclinical',
        'pdb_ids': ['1YZB', '3O65'],
        'druggable': True,
    },
    'MS4A6A': {
        'protein': 'MS4A6A membrane protein',
        'function': 'Microglial function',
        'pathway': 'Neuroinflammation',
        'diseases': ['Alzheimer Disease (risk locus)'],
        'drugs': ['Research'],
        'drug_status': 'Genetic risk factor',
        'pdb_ids': [],
        'druggable': False,
    },
    'TREM2': {
        'protein': 'Triggering receptor expressed on myeloid cells 2',
        'function': 'Microglial activation',
        'pathway': 'Neuroinflammation',
        'diseases': ['Alzheimer Disease', 'FTD (Nasu-Hakola disease)'],
        'drugs': ['AL002 (TREM2 agonist antibody)'],
        'drug_status': 'Phase II',
        'pdb_ids': ['5ELI', '6B8O'],
        'druggable': True,
    },
    'APOE': {
        'protein': 'Apolipoprotein E',
        'function': 'Lipid transport, amyloid clearance',
        'pathway': 'Brain lipid metabolism',
        'diseases': ['Alzheimer Disease (E4 risk)', 'Cardiovascular Disease'],
        'drugs': ['APOE4 structure correctors', 'Gene therapy'],
        'drug_status': 'Research',
        'pdb_ids': ['1GS9', '2L7B'],
        'druggable': True,
    },
    'MS_CD20': {
        'protein': 'CD20 (MS4A1) - Multiple Sclerosis',
        'function': 'B-cell surface marker',
        'pathway': 'B-cell depletion',
        'diseases': ['Multiple Sclerosis', 'B-cell malignancies'],
        'drugs': ['Ocrelizumab (Ocrevus)', 'Ofatumumab (Kesimpta)', 'Rituximab'],
        'drug_status': 'FDA Approved',
        'pdb_ids': ['5JNE'],
        'druggable': True,
    },
    'IL2RA': {
        'protein': 'Interleukin-2 receptor alpha (CD25)',
        'function': 'T-cell activation',
        'pathway': 'T-cell signaling',
        'diseases': ['Multiple Sclerosis', 'Type 1 Diabetes'],
        'drugs': ['Daclizumab (withdrawn)'],
        'drug_status': 'Genetic association',
        'pdb_ids': ['1Z92'],
        'druggable': True,
    },
    'CGRP': {
        'protein': 'Calcitonin gene-related peptide',
        'function': 'Vasodilation, pain signaling',
        'pathway': 'CGRP signaling',
        'diseases': ['Migraine', 'Cluster Headache'],
        'drugs': ['Erenumab (Aimovig)', 'Fremanezumab', 'Galcanezumab', 'Rimegepant'],
        'drug_status': 'FDA Approved',
        'pdb_ids': ['4RWF'],
        'druggable': True,
    },
    'CALCA': {
        'protein': 'Calcitonin/CGRP gene product',
        'function': 'Neuropeptide production',
        'pathway': 'CGRP pathway',
        'diseases': ['Migraine'],
        'drugs': ['CGRP mAbs', 'Gepants'],
        'drug_status': 'FDA Approved',
        'pdb_ids': [],
        'druggable': True,
    },
    'TRPV1': {
        'protein': 'Transient receptor potential vanilloid 1',
        'function': 'Pain/heat sensor',
        'pathway': 'Nociception',
        'diseases': ['Chronic Pain', 'Neuropathic Pain'],
        'drugs': ['Capsaicin patches', 'TRPV1 antagonists (research)'],
        'drug_status': 'Partial (topical)',
        'pdb_ids': ['3J5P', '5IRZ'],
        'druggable': True,
    },
    'SCN9A': {
        'protein': 'Sodium channel Nav1.7',
        'function': 'Pain signaling',
        'pathway': 'Nociceptor excitability',
        'diseases': ['Chronic Pain', 'Erythromelalgia', 'Congenital Insensitivity to Pain'],
        'drugs': ['Nav1.7 inhibitors (research)', 'VX-150'],
        'drug_status': 'Phase II',
        'pdb_ids': ['6J8H'],
        'druggable': True,
    },
    'SCN10A': {
        'protein': 'Sodium channel Nav1.8',
        'function': 'Pain signaling in DRG neurons',
        'pathway': 'Nociception',
        'diseases': ['Chronic Pain', 'Neuropathic Pain'],
        'drugs': ['VX-548 (suzetrigine)'],
        'drug_status': 'FDA submission (2024)',
        'pdb_ids': [],
        'druggable': True,
    },
    'GRIN2B': {
        'protein': 'NMDA receptor subunit 2B',
        'function': 'Glutamate signaling',
        'pathway': 'Excitatory neurotransmission',
        'diseases': ['Epilepsy', 'Intellectual Disability', 'Depression'],
        'drugs': ['Memantine (partial)', 'Ketamine (NMDA modulation)'],
        'drug_status': 'Research',
        'pdb_ids': ['4PE5'],
        'druggable': True,
    },
    'GABRA1': {
        'protein': 'GABA-A receptor alpha-1',
        'function': 'Inhibitory neurotransmission',
        'pathway': 'GABAergic signaling',
        'diseases': ['Epilepsy', 'Anxiety', 'Insomnia'],
        'drugs': ['Benzodiazepines', 'Zolpidem', 'Phenobarbital'],
        'drug_status': 'FDA Approved',
        'pdb_ids': ['6D6U', '6HUP'],
        'druggable': True,
    },
    'SV2A': {
        'protein': 'Synaptic vesicle glycoprotein 2A',
        'function': 'Synaptic vesicle function',
        'pathway': 'Neurotransmitter release',
        'diseases': ['Epilepsy'],
        'drugs': ['Levetiracetam (Keppra)', 'Brivaracetam'],
        'drug_status': 'FDA Approved',
        'pdb_ids': ['6ES1'],
        'druggable': True,
    },

    # =========================================================================
    # ONCOLOGY - Major Drug Targets
    # =========================================================================

    'BRCA1': {
        'protein': 'BRCA1 DNA repair protein',
        'function': 'Homologous recombination repair',
        'pathway': 'DNA damage response',
        'diseases': ['Breast Cancer (hereditary)', 'Ovarian Cancer', 'Prostate Cancer'],
        'drugs': ['Olaparib (Lynparza)', 'Rucaparib', 'Niraparib', 'Talazoparib'],
        'drug_status': 'FDA Approved (PARP inhibitors)',
        'pdb_ids': ['1JM7', '4Y18'],
        'druggable': True,
    },
    'BRCA2': {
        'protein': 'BRCA2 DNA repair protein',
        'function': 'Homologous recombination repair',
        'pathway': 'DNA damage response',
        'diseases': ['Breast Cancer (hereditary)', 'Ovarian Cancer', 'Pancreatic Cancer'],
        'drugs': ['Olaparib (Lynparza)', 'Rucaparib', 'Niraparib', 'Talazoparib'],
        'drug_status': 'FDA Approved (PARP inhibitors)',
        'pdb_ids': ['1MIU', '5DSS'],
        'druggable': True,
    },
    'EGFR': {
        'protein': 'Epidermal growth factor receptor',
        'function': 'Receptor tyrosine kinase signaling',
        'pathway': 'EGFR/RAS/MAPK pathway',
        'diseases': ['Non-small cell lung cancer', 'Glioblastoma', 'Colorectal Cancer'],
        'drugs': ['Osimertinib (Tagrisso)', 'Erlotinib', 'Gefitinib', 'Afatinib'],
        'drug_status': 'FDA Approved',
        'pdb_ids': ['1M17', '4HJO', '5UG9'],
        'druggable': True,
    },
    'ALK': {
        'protein': 'Anaplastic lymphoma kinase',
        'function': 'Receptor tyrosine kinase',
        'pathway': 'ALK/RAS/PI3K pathway',
        'diseases': ['Non-small cell lung cancer', 'Anaplastic large cell lymphoma', 'Neuroblastoma'],
        'drugs': ['Alectinib (Alecensa)', 'Crizotinib', 'Brigatinib', 'Lorlatinib'],
        'drug_status': 'FDA Approved',
        'pdb_ids': ['2XP2', '4MKC'],
        'druggable': True,
    },
    'BRAF': {
        'protein': 'B-Raf proto-oncogene',
        'function': 'Serine/threonine kinase',
        'pathway': 'RAS/RAF/MEK/ERK pathway',
        'diseases': ['Melanoma', 'Colorectal Cancer', 'Thyroid Cancer', 'Lung Cancer'],
        'drugs': ['Vemurafenib (Zelboraf)', 'Dabrafenib', 'Encorafenib'],
        'drug_status': 'FDA Approved',
        'pdb_ids': ['1UWH', '4MNE', '5CSW'],
        'druggable': True,
    },
    'KRAS': {
        'protein': 'KRAS GTPase',
        'function': 'GTPase signaling',
        'pathway': 'RAS/MAPK pathway',
        'diseases': ['Pancreatic Cancer', 'Lung Cancer', 'Colorectal Cancer'],
        'drugs': ['Sotorasib (Lumakras)', 'Adagrasib (KRAS G12C inhibitors)'],
        'drug_status': 'FDA Approved (G12C)',
        'pdb_ids': ['4OBE', '6OIM'],
        'druggable': True,
    },
    'ERBB2': {
        'protein': 'HER2/neu receptor',
        'function': 'Receptor tyrosine kinase',
        'pathway': 'HER2/PI3K/AKT pathway',
        'diseases': ['Breast Cancer (HER2+)', 'Gastric Cancer', 'Esophageal Cancer'],
        'drugs': ['Trastuzumab (Herceptin)', 'Pertuzumab', 'T-DM1', 'Tucatinib'],
        'drug_status': 'FDA Approved',
        'pdb_ids': ['1N8Z', '3PP0'],
        'druggable': True,
    },
    'PIK3CA': {
        'protein': 'PI3K catalytic subunit alpha',
        'function': 'Lipid kinase signaling',
        'pathway': 'PI3K/AKT/mTOR pathway',
        'diseases': ['Breast Cancer', 'Endometrial Cancer', 'Ovarian Cancer'],
        'drugs': ['Alpelisib (Piqray)', 'Copanlisib', 'Inavolisib'],
        'drug_status': 'FDA Approved',
        'pdb_ids': ['4JPS', '5DXT'],
        'druggable': True,
    },
    'BCR-ABL1': {
        'protein': 'BCR-ABL fusion kinase',
        'function': 'Constitutive tyrosine kinase',
        'pathway': 'ABL signaling',
        'diseases': ['Chronic Myeloid Leukemia', 'ALL (Ph+)'],
        'drugs': ['Imatinib (Gleevec)', 'Dasatinib', 'Nilotinib', 'Ponatinib', 'Asciminib'],
        'drug_status': 'FDA Approved',
        'pdb_ids': ['1IEP', '2GQG'],
        'druggable': True,
    },
    'RET': {
        'protein': 'RET proto-oncogene',
        'function': 'Receptor tyrosine kinase',
        'pathway': 'RET/RAS/MAPK pathway',
        'diseases': ['Thyroid Cancer (MTC)', 'Non-small cell lung cancer', 'MEN2'],
        'drugs': ['Selpercatinib (Retevmo)', 'Pralsetinib'],
        'drug_status': 'FDA Approved',
        'pdb_ids': ['2IVV', '7JU6'],
        'druggable': True,
    },
    'MET': {
        'protein': 'Hepatocyte growth factor receptor',
        'function': 'Receptor tyrosine kinase',
        'pathway': 'MET/HGF pathway',
        'diseases': ['Non-small cell lung cancer', 'Gastric Cancer', 'Renal Cell Carcinoma'],
        'drugs': ['Capmatinib (Tabrecta)', 'Tepotinib', 'Crizotinib'],
        'drug_status': 'FDA Approved',
        'pdb_ids': ['1R0P', '3Q6W'],
        'druggable': True,
    },
    'ROS1': {
        'protein': 'ROS1 receptor tyrosine kinase',
        'function': 'Receptor tyrosine kinase',
        'pathway': 'ROS1/RAS/PI3K pathway',
        'diseases': ['Non-small cell lung cancer', 'Glioblastoma'],
        'drugs': ['Crizotinib', 'Entrectinib', 'Lorlatinib', 'Repotrectinib'],
        'drug_status': 'FDA Approved',
        'pdb_ids': ['3ZBF'],
        'druggable': True,
    },
    'NTRK1': {
        'protein': 'Neurotrophic tyrosine kinase receptor 1',
        'function': 'Receptor tyrosine kinase',
        'pathway': 'TRK/RAS/PI3K pathway',
        'diseases': ['NTRK fusion-positive solid tumors', 'Thyroid Cancer', 'Sarcoma'],
        'drugs': ['Larotrectinib (Vitrakvi)', 'Entrectinib'],
        'drug_status': 'FDA Approved (tumor-agnostic)',
        'pdb_ids': ['4AOJ', '4YNE'],
        'druggable': True,
    },
    'IDH1': {
        'protein': 'Isocitrate dehydrogenase 1',
        'function': 'Metabolic enzyme',
        'pathway': 'TCA cycle / 2-HG production',
        'diseases': ['Glioma', 'Acute Myeloid Leukemia', 'Cholangiocarcinoma'],
        'drugs': ['Ivosidenib (Tibsovo)', 'Olutasidenib'],
        'drug_status': 'FDA Approved',
        'pdb_ids': ['3INM', '5TQH'],
        'druggable': True,
    },
    'IDH2': {
        'protein': 'Isocitrate dehydrogenase 2',
        'function': 'Metabolic enzyme',
        'pathway': 'TCA cycle / 2-HG production',
        'diseases': ['Acute Myeloid Leukemia', 'Glioma'],
        'drugs': ['Enasidenib (Idhifa)'],
        'drug_status': 'FDA Approved',
        'pdb_ids': ['4JA8'],
        'druggable': True,
    },
    'FLT3': {
        'protein': 'FMS-like tyrosine kinase 3',
        'function': 'Receptor tyrosine kinase',
        'pathway': 'FLT3/RAS/STAT5 pathway',
        'diseases': ['Acute Myeloid Leukemia'],
        'drugs': ['Midostaurin (Rydapt)', 'Gilteritinib', 'Quizartinib'],
        'drug_status': 'FDA Approved',
        'pdb_ids': ['1RJB', '4XUF'],
        'druggable': True,
    },
    'BTK': {
        'protein': 'Bruton tyrosine kinase',
        'function': 'Non-receptor tyrosine kinase',
        'pathway': 'B-cell receptor signaling',
        'diseases': ['Chronic Lymphocytic Leukemia', 'Mantle Cell Lymphoma', 'Waldenstrom'],
        'drugs': ['Ibrutinib (Imbruvica)', 'Acalabrutinib', 'Zanubrutinib', 'Pirtobrutinib'],
        'drug_status': 'FDA Approved',
        'pdb_ids': ['3GEN', '5P9J'],
        'druggable': True,
    },
    'BCL2': {
        'protein': 'B-cell lymphoma 2',
        'function': 'Apoptosis regulator',
        'pathway': 'Intrinsic apoptosis pathway',
        'diseases': ['Chronic Lymphocytic Leukemia', 'AML', 'Follicular Lymphoma'],
        'drugs': ['Venetoclax (Venclexta)'],
        'drug_status': 'FDA Approved',
        'pdb_ids': ['1G5M', '4MAN'],
        'druggable': True,
    },
    'PDCD1': {
        'protein': 'PD-1 (Programmed cell death protein 1)',
        'function': 'Immune checkpoint receptor',
        'pathway': 'T-cell exhaustion/checkpoint',
        'diseases': ['Melanoma', 'Lung Cancer', 'Many solid tumors'],
        'drugs': ['Pembrolizumab (Keytruda)', 'Nivolumab (Opdivo)', 'Cemiplimab'],
        'drug_status': 'FDA Approved',
        'pdb_ids': ['3RRQ', '5GGS'],
        'druggable': True,
    },
    'CD274': {
        'protein': 'PD-L1 (Programmed death-ligand 1)',
        'function': 'Immune checkpoint ligand',
        'pathway': 'T-cell exhaustion/checkpoint',
        'diseases': ['Lung Cancer', 'Bladder Cancer', 'Triple-negative breast cancer'],
        'drugs': ['Atezolizumab (Tecentriq)', 'Durvalumab', 'Avelumab'],
        'drug_status': 'FDA Approved',
        'pdb_ids': ['3BIK', '5C3T'],
        'druggable': True,
    },
    'CTLA4': {
        'protein': 'Cytotoxic T-lymphocyte-associated protein 4',
        'function': 'Immune checkpoint receptor',
        'pathway': 'T-cell activation/checkpoint',
        'diseases': ['Melanoma', 'Renal Cell Carcinoma'],
        'drugs': ['Ipilimumab (Yervoy)', 'Tremelimumab'],
        'drug_status': 'FDA Approved',
        'pdb_ids': ['1I8L', '3OSK'],
        'druggable': True,
    },
    'TP53': {
        'protein': 'Tumor protein p53',
        'function': 'Tumor suppressor, transcription factor',
        'pathway': 'Cell cycle arrest, apoptosis',
        'diseases': ['Li-Fraumeni Syndrome', 'Many cancers (most mutated gene)'],
        'drugs': ['APR-246 (Eprenetapopt)', 'PC14586 (p53 Y220C)', 'AZD1775 (WEE1)'],
        'drug_status': 'Phase II/III',
        'pdb_ids': ['1TUP', '2XWR', '5MCT'],
        'druggable': True,
    },
    'PTEN': {
        'protein': 'Phosphatase and tensin homolog',
        'function': 'Phosphatase tumor suppressor',
        'pathway': 'PI3K/AKT pathway (negative regulator)',
        'diseases': ['Prostate Cancer', 'Breast Cancer', 'Endometrial Cancer', 'Cowden Syndrome'],
        'drugs': ['PI3K inhibitors (synthetic lethality)', 'AKT inhibitors'],
        'drug_status': 'Biomarker for PI3K pathway drugs',
        'pdb_ids': ['1D5R'],
        'druggable': False,
    },
    'MTOR': {
        'protein': 'Mechanistic target of rapamycin',
        'function': 'Serine/threonine kinase',
        'pathway': 'PI3K/AKT/mTOR pathway',
        'diseases': ['Renal Cell Carcinoma', 'Breast Cancer', 'TSC', 'Neuroendocrine tumors'],
        'drugs': ['Everolimus (Afinitor)', 'Temsirolimus', 'Sirolimus'],
        'drug_status': 'FDA Approved',
        'pdb_ids': ['4JSV', '4DRI'],
        'druggable': True,
    },
    'CDK4': {
        'protein': 'Cyclin-dependent kinase 4',
        'function': 'Cell cycle kinase',
        'pathway': 'Cell cycle (G1/S transition)',
        'diseases': ['Breast Cancer (HR+)', 'Melanoma', 'Liposarcoma'],
        'drugs': ['Palbociclib (Ibrance)', 'Ribociclib', 'Abemaciclib'],
        'drug_status': 'FDA Approved',
        'pdb_ids': ['2W96', '5L2I'],
        'druggable': True,
    },
    'CDK6': {
        'protein': 'Cyclin-dependent kinase 6',
        'function': 'Cell cycle kinase',
        'pathway': 'Cell cycle (G1/S transition)',
        'diseases': ['Breast Cancer (HR+)', 'Mantle Cell Lymphoma'],
        'drugs': ['Palbociclib (Ibrance)', 'Ribociclib', 'Abemaciclib'],
        'drug_status': 'FDA Approved',
        'pdb_ids': ['1BI7', '5L2T'],
        'druggable': True,
    },

    # =========================================================================
    # CARDIOVASCULAR
    # =========================================================================

    'LDLR': {
        'protein': 'Low-density lipoprotein receptor',
        'function': 'Cholesterol uptake',
        'pathway': 'Lipid metabolism',
        'diseases': ['Familial Hypercholesterolemia', 'Coronary Artery Disease'],
        'drugs': ['Statins (indirect)', 'PCSK9 inhibitors', 'Evinacumab'],
        'drug_status': 'Target for lipid-lowering',
        'pdb_ids': ['1N7D'],
        'druggable': False,
    },
    'PCSK9': {
        'protein': 'Proprotein convertase subtilisin/kexin type 9',
        'function': 'LDLR degradation',
        'pathway': 'Lipid metabolism',
        'diseases': ['Hypercholesterolemia', 'Cardiovascular Disease'],
        'drugs': ['Evolocumab (Repatha)', 'Alirocumab (Praluent)', 'Inclisiran'],
        'drug_status': 'FDA Approved',
        'pdb_ids': ['2P4E', '3BPS'],
        'druggable': True,
    },
    'APOB': {
        'protein': 'Apolipoprotein B',
        'function': 'Lipoprotein component',
        'pathway': 'Lipid transport',
        'diseases': ['Familial Hypercholesterolemia', 'Hypobetalipoproteinemia'],
        'drugs': ['Mipomersen (Kynamro)', 'ASO therapy'],
        'drug_status': 'FDA Approved',
        'pdb_ids': ['1LSH'],
        'druggable': True,
    },
    'TTR': {
        'protein': 'Transthyretin',
        'function': 'Thyroid hormone transport',
        'pathway': 'Protein transport',
        'diseases': ['Transthyretin Amyloidosis (ATTR)', 'Cardiomyopathy', 'Polyneuropathy'],
        'drugs': ['Tafamidis (Vyndaqel)', 'Patisiran (Onpattro)', 'Inotersen', 'Vutrisiran'],
        'drug_status': 'FDA Approved',
        'pdb_ids': ['1F41', '4TLT'],
        'druggable': True,
    },
    'MYBPC3': {
        'protein': 'Myosin-binding protein C3',
        'function': 'Cardiac muscle contraction',
        'pathway': 'Sarcomere function',
        'diseases': ['Hypertrophic Cardiomyopathy (HCM)', 'Dilated Cardiomyopathy'],
        'drugs': ['Mavacamten (Camzyos)', 'Aficamten'],
        'drug_status': 'FDA Approved (2022)',
        'pdb_ids': ['4BPF'],
        'druggable': True,
    },
    'MYH7': {
        'protein': 'Beta-myosin heavy chain',
        'function': 'Cardiac muscle contraction',
        'pathway': 'Sarcomere function',
        'diseases': ['Hypertrophic Cardiomyopathy', 'Dilated Cardiomyopathy'],
        'drugs': ['Mavacamten (Camzyos)', 'Cardiac myosin inhibitors'],
        'drug_status': 'FDA Approved',
        'pdb_ids': ['4DB1'],
        'druggable': True,
    },
    'SCN5A': {
        'protein': 'Sodium channel Nav1.5',
        'function': 'Cardiac sodium channel',
        'pathway': 'Cardiac action potential',
        'diseases': ['Long QT Syndrome', 'Brugada Syndrome', 'Dilated Cardiomyopathy'],
        'drugs': ['Mexiletine', 'Quinidine', 'Flecainide'],
        'drug_status': 'Class I antiarrhythmics',
        'pdb_ids': ['6UZ3'],
        'druggable': True,
    },
    'KCNH2': {
        'protein': 'hERG potassium channel',
        'function': 'Cardiac potassium channel',
        'pathway': 'Cardiac repolarization',
        'diseases': ['Long QT Syndrome Type 2', 'Arrhythmias'],
        'drugs': ['Beta-blockers', 'Potassium supplementation'],
        'drug_status': 'Drug safety target (hERG screening)',
        'pdb_ids': ['5VA2'],
        'druggable': True,
    },
    'KCNQ1': {
        'protein': 'Potassium channel KvLQT1',
        'function': 'Cardiac potassium channel',
        'pathway': 'Cardiac repolarization',
        'diseases': ['Long QT Syndrome Type 1', 'Short QT Syndrome'],
        'drugs': ['Beta-blockers (Nadolol)', 'Left cardiac sympathetic denervation'],
        'drug_status': 'Standard of care',
        'pdb_ids': ['5VMS'],
        'druggable': True,
    },
    'LMNA': {
        'protein': 'Lamin A/C',
        'function': 'Nuclear envelope structure',
        'pathway': 'Nuclear organization',
        'diseases': ['Dilated Cardiomyopathy', 'Muscular Dystrophy', 'Progeria'],
        'drugs': ['MEK inhibitors (research)', 'Lonafarnib (progeria)'],
        'drug_status': 'Limited treatments',
        'pdb_ids': ['1IFR'],
        'druggable': False,
    },

    # =========================================================================
    # RARE DISEASE
    # =========================================================================

    'CFTR': {
        'protein': 'Cystic fibrosis transmembrane conductance regulator',
        'function': 'Chloride/bicarbonate channel',
        'pathway': 'Epithelial ion transport',
        'diseases': ['Cystic Fibrosis'],
        'drugs': ['Trikafta (elexacaftor/tezacaftor/ivacaftor)', 'Ivacaftor (Kalydeco)', 'Lumacaftor'],
        'drug_status': 'FDA Approved (breakthrough)',
        'pdb_ids': ['5UAK', '6MSM'],
        'druggable': True,
    },
    'SMN1': {
        'protein': 'Survival motor neuron 1',
        'function': 'snRNP assembly',
        'pathway': 'RNA splicing',
        'diseases': ['Spinal Muscular Atrophy (SMA)'],
        'drugs': ['Onasemnogene (Zolgensma)', 'Nusinersen (Spinraza)', 'Risdiplam (Evrysdi)'],
        'drug_status': 'FDA Approved (gene therapy)',
        'pdb_ids': ['4A4G'],
        'druggable': True,
    },
    'DMD': {
        'protein': 'Dystrophin',
        'function': 'Muscle structural protein',
        'pathway': 'Muscle membrane stability',
        'diseases': ['Duchenne Muscular Dystrophy', 'Becker Muscular Dystrophy'],
        'drugs': ['Exondys 51 (eteplirsen)', 'Viltolarsen', 'Casimersen', 'SRP-9001 (gene therapy)'],
        'drug_status': 'FDA Approved (exon skipping)',
        'pdb_ids': ['1DXX', '3UUN'],
        'druggable': True,
    },
    'HBB': {
        'protein': 'Hemoglobin subunit beta',
        'function': 'Oxygen transport',
        'pathway': 'Hemoglobin function',
        'diseases': ['Sickle Cell Disease', 'Beta-Thalassemia'],
        'drugs': ['Casgevy (exagamglogene)', 'Lyfgenia (lovotibeglogene)', 'Voxelotor', 'Crizanlizumab'],
        'drug_status': 'FDA Approved (CRISPR gene therapy 2023)',
        'pdb_ids': ['2HHB', '1GZX'],
        'druggable': True,
    },
    'F8': {
        'protein': 'Coagulation factor VIII',
        'function': 'Blood clotting',
        'pathway': 'Coagulation cascade',
        'diseases': ['Hemophilia A'],
        'drugs': ['Valoctocogene (Roctavian)', 'Emicizumab (Hemlibra)', 'Factor VIII concentrates'],
        'drug_status': 'FDA Approved (gene therapy 2023)',
        'pdb_ids': ['2R7E', '6MF2'],
        'druggable': True,
    },
    'F9': {
        'protein': 'Coagulation factor IX',
        'function': 'Blood clotting',
        'pathway': 'Coagulation cascade',
        'diseases': ['Hemophilia B'],
        'drugs': ['Etranacogene (Hemgenix)', 'Fidanacogene (Beqvez)', 'Factor IX concentrates'],
        'drug_status': 'FDA Approved (gene therapy)',
        'pdb_ids': ['1CFI', '6MV4'],
        'druggable': True,
    },
    'GAA': {
        'protein': 'Acid alpha-glucosidase',
        'function': 'Glycogen breakdown',
        'pathway': 'Lysosomal glycogen metabolism',
        'diseases': ['Pompe Disease', 'Glycogen Storage Disease Type II'],
        'drugs': ['Alglucosidase alfa (Lumizyme)', 'Avalglucosidase alfa (Nexviazyme)'],
        'drug_status': 'FDA Approved (ERT)',
        'pdb_ids': ['5NN8'],
        'druggable': True,
    },
    'GBA': {
        'protein': 'Glucocerebrosidase',
        'function': 'Glucocerebroside breakdown',
        'pathway': 'Lysosomal lipid metabolism',
        'diseases': ['Gaucher Disease', 'Parkinson Disease (risk factor)'],
        'drugs': ['Imiglucerase (Cerezyme)', 'Velaglucerase', 'Eliglustat (Cerdelga)', 'Venglustat'],
        'drug_status': 'FDA Approved (ERT + SRT)',
        'pdb_ids': ['1OGS', '2NT1'],
        'druggable': True,
    },
    'IDUA': {
        'protein': 'Alpha-L-iduronidase',
        'function': 'Glycosaminoglycan breakdown',
        'pathway': 'Lysosomal GAG metabolism',
        'diseases': ['Hurler Syndrome (MPS I)', 'Scheie Syndrome'],
        'drugs': ['Laronidase (Aldurazyme)'],
        'drug_status': 'FDA Approved (ERT)',
        'pdb_ids': ['4MJ5'],
        'druggable': True,
    },
    'PAH': {
        'protein': 'Phenylalanine hydroxylase',
        'function': 'Phenylalanine metabolism',
        'pathway': 'Amino acid metabolism',
        'diseases': ['Phenylketonuria (PKU)'],
        'drugs': ['Sapropterin (Kuvan)', 'Pegvaliase (Palynziq)'],
        'drug_status': 'FDA Approved',
        'pdb_ids': ['1PAH', '5FII'],
        'druggable': True,
    },
    'SCN1A': {
        'protein': 'Sodium channel Nav1.1',
        'function': 'Neuronal sodium channel',
        'pathway': 'Neuronal excitability',
        'diseases': ['Dravet Syndrome', 'Epilepsy', 'GEFS+'],
        'drugs': ['Fenfluramine (Fintepla)', 'Stiripentol', 'Cannabidiol (Epidiolex)'],
        'drug_status': 'FDA Approved',
        'pdb_ids': ['6J8E'],
        'druggable': True,
    },
    'MECP2': {
        'protein': 'Methyl-CpG-binding protein 2',
        'function': 'Transcriptional regulation',
        'pathway': 'Epigenetic regulation',
        'diseases': ['Rett Syndrome'],
        'drugs': ['Trofinetide (Daybue)', 'Gene therapy (in trials)'],
        'drug_status': 'FDA Approved (2023)',
        'pdb_ids': ['3C2I'],
        'druggable': True,
    },

    # =========================================================================
    # IMMUNOLOGY / INFLAMMATION
    # =========================================================================

    'IL6': {
        'protein': 'Interleukin-6',
        'function': 'Pro-inflammatory cytokine',
        'pathway': 'IL-6/JAK/STAT3 pathway',
        'diseases': ['Rheumatoid Arthritis', 'Cytokine Release Syndrome', 'Castleman Disease'],
        'drugs': ['Tocilizumab (Actemra)', 'Sarilumab', 'Siltuximab'],
        'drug_status': 'FDA Approved',
        'pdb_ids': ['1ALU', '4CNI'],
        'druggable': True,
    },
    'TNF': {
        'protein': 'Tumor necrosis factor alpha',
        'function': 'Pro-inflammatory cytokine',
        'pathway': 'NF-kB/inflammation pathway',
        'diseases': ['Rheumatoid Arthritis', 'Crohn Disease', 'Psoriasis', 'Ankylosing Spondylitis'],
        'drugs': ['Adalimumab (Humira)', 'Infliximab (Remicade)', 'Etanercept', 'Certolizumab'],
        'drug_status': 'FDA Approved',
        'pdb_ids': ['1TNF', '3ALQ'],
        'druggable': True,
    },
    'JAK1': {
        'protein': 'Janus kinase 1',
        'function': 'Non-receptor tyrosine kinase',
        'pathway': 'JAK/STAT signaling',
        'diseases': ['Rheumatoid Arthritis', 'Atopic Dermatitis', 'Myelofibrosis'],
        'drugs': ['Tofacitinib (Xeljanz)', 'Upadacitinib', 'Abrocitinib'],
        'drug_status': 'FDA Approved',
        'pdb_ids': ['3EYG', '6BBU'],
        'druggable': True,
    },
    'JAK2': {
        'protein': 'Janus kinase 2',
        'function': 'Non-receptor tyrosine kinase',
        'pathway': 'JAK/STAT signaling',
        'diseases': ['Myeloproliferative Neoplasms', 'Polycythemia Vera', 'Myelofibrosis'],
        'drugs': ['Ruxolitinib (Jakafi)', 'Fedratinib', 'Pacritinib'],
        'drug_status': 'FDA Approved',
        'pdb_ids': ['2B7A', '4YTH'],
        'druggable': True,
    },
    'IL17A': {
        'protein': 'Interleukin-17A',
        'function': 'Pro-inflammatory cytokine',
        'pathway': 'Th17 immunity',
        'diseases': ['Psoriasis', 'Psoriatic Arthritis', 'Ankylosing Spondylitis'],
        'drugs': ['Secukinumab (Cosentyx)', 'Ixekizumab', 'Brodalumab'],
        'drug_status': 'FDA Approved',
        'pdb_ids': ['4HR9', '5VB9'],
        'druggable': True,
    },
    'IL23A': {
        'protein': 'Interleukin-23 subunit alpha',
        'function': 'Pro-inflammatory cytokine',
        'pathway': 'Th17 differentiation',
        'diseases': ['Psoriasis', 'Crohn Disease', 'Ulcerative Colitis'],
        'drugs': ['Ustekinumab (Stelara)', 'Guselkumab', 'Risankizumab', 'Tildrakizumab'],
        'drug_status': 'FDA Approved',
        'pdb_ids': ['3DUH', '5NJD'],
        'druggable': True,
    },
    'TSLP': {
        'protein': 'Thymic stromal lymphopoietin',
        'function': 'Cytokine (allergic inflammation)',
        'pathway': 'Type 2 immunity',
        'diseases': ['Asthma', 'Atopic Dermatitis', 'Allergic Rhinitis'],
        'drugs': ['Tezepelumab (Tezspire)'],
        'drug_status': 'FDA Approved (2021)',
        'pdb_ids': ['5J12'],
        'druggable': True,
    },
    'TNFRSF1A': {
        'protein': 'TNF receptor 1',
        'function': 'TNF receptor',
        'pathway': 'TNF signaling',
        'diseases': ['TRAPS (TNF Receptor-Associated Periodic Syndrome)', 'Autoinflammation'],
        'drugs': ['Etanercept', 'Anti-IL-1 therapy (Anakinra)'],
        'drug_status': 'Off-label use',
        'pdb_ids': ['1EXT'],
        'druggable': True,
    },

    # =========================================================================
    # PHARMACOGENOMICS (Expanded)
    # =========================================================================

    'CYP2C19': {
        'protein': 'Cytochrome P450 2C19',
        'function': 'Drug metabolism',
        'pathway': 'Xenobiotic metabolism',
        'diseases': ['Poor drug metabolism', 'Drug toxicity risk', 'Drug resistance'],
        'drugs': ['PPIs (omeprazole)', 'Clopidogrel', 'Voriconazole', 'Escitalopram'],
        'drug_status': 'Pharmacogenomic marker',
        'pdb_ids': ['4GQS'],
        'druggable': False,
    },
    'CYP2D6': {
        'protein': 'Cytochrome P450 2D6',
        'function': 'Drug metabolism',
        'pathway': 'Xenobiotic metabolism',
        'diseases': ['Poor drug metabolism', 'Codeine toxicity', 'Tamoxifen resistance'],
        'drugs': ['Codeine', 'Tramadol', 'Tamoxifen', 'Many antidepressants'],
        'drug_status': 'Pharmacogenomic marker',
        'pdb_ids': ['4WNT'],
        'druggable': False,
    },
    'CYP3A4': {
        'protein': 'Cytochrome P450 3A4',
        'function': 'Drug metabolism (50% of drugs)',
        'pathway': 'Xenobiotic metabolism',
        'diseases': ['Drug-drug interactions', 'Variable drug exposure'],
        'drugs': ['Statins', 'Immunosuppressants', 'HIV protease inhibitors', 'Many others'],
        'drug_status': 'Pharmacogenomic marker',
        'pdb_ids': ['4K9W'],
        'druggable': False,
    },
    'CYP2C9': {
        'protein': 'Cytochrome P450 2C9',
        'function': 'Drug metabolism',
        'pathway': 'Xenobiotic metabolism',
        'diseases': ['Warfarin sensitivity', 'NSAID toxicity'],
        'drugs': ['Warfarin', 'Phenytoin', 'NSAIDs', 'Sulfonylureas'],
        'drug_status': 'Pharmacogenomic marker',
        'pdb_ids': ['1OG5'],
        'druggable': False,
    },
    'VKORC1': {
        'protein': 'Vitamin K epoxide reductase',
        'function': 'Vitamin K recycling',
        'pathway': 'Coagulation',
        'diseases': ['Warfarin sensitivity', 'Vitamin K clotting disorder'],
        'drugs': ['Warfarin (dosing)', 'Other vitamin K antagonists'],
        'drug_status': 'Pharmacogenomic marker',
        'pdb_ids': ['3KP9'],
        'druggable': True,
    },
    'DPYD': {
        'protein': 'Dihydropyrimidine dehydrogenase',
        'function': 'Pyrimidine catabolism',
        'pathway': 'Fluoropyrimidine metabolism',
        'diseases': ['5-FU toxicity', 'Capecitabine toxicity', 'DPD deficiency'],
        'drugs': ['5-Fluorouracil', 'Capecitabine', 'Tegafur'],
        'drug_status': 'FDA requires testing',
        'pdb_ids': ['1H7X'],
        'druggable': False,
    },
    'TPMT': {
        'protein': 'Thiopurine S-methyltransferase',
        'function': 'Thiopurine inactivation',
        'pathway': 'Purine metabolism',
        'diseases': ['Thiopurine toxicity', 'Myelosuppression'],
        'drugs': ['Azathioprine', 'Mercaptopurine', 'Thioguanine'],
        'drug_status': 'Pharmacogenomic marker',
        'pdb_ids': ['2BZG'],
        'druggable': False,
    },
    'UGT1A1': {
        'protein': 'UDP-glucuronosyltransferase 1A1',
        'function': 'Glucuronidation',
        'pathway': 'Drug conjugation',
        'diseases': ['Irinotecan toxicity', 'Gilbert syndrome', 'Hyperbilirubinemia'],
        'drugs': ['Irinotecan', 'Atazanavir'],
        'drug_status': 'Pharmacogenomic marker',
        'pdb_ids': ['6BKE'],
        'druggable': False,
    },
    'SLCO1B1': {
        'protein': 'Organic anion transporter 1B1',
        'function': 'Hepatic drug uptake',
        'pathway': 'Drug transport',
        'diseases': ['Statin-induced myopathy', 'Simvastatin toxicity'],
        'drugs': ['Simvastatin', 'Atorvastatin', 'Rosuvastatin'],
        'drug_status': 'Pharmacogenomic marker',
        'pdb_ids': [],
        'druggable': False,
    },
    'NUDT15': {
        'protein': 'Nucleotide diphosphatase',
        'function': 'Nucleotide metabolism',
        'pathway': 'Thiopurine metabolism',
        'diseases': ['Thiopurine toxicity', 'Leukopenia'],
        'drugs': ['Azathioprine', 'Mercaptopurine'],
        'drug_status': 'Pharmacogenomic marker (esp. Asian populations)',
        'pdb_ids': ['5LPG'],
        'druggable': False,
    },

    # =========================================================================
    # METABOLIC / ENDOCRINE (NEW SECTION)
    # =========================================================================

    'GLP1R': {
        'protein': 'Glucagon-like peptide-1 receptor',
        'function': 'Incretin signaling, insulin secretion',
        'pathway': 'GLP-1/cAMP/insulin pathway',
        'diseases': ['Type 2 Diabetes', 'Obesity', 'NASH'],
        'drugs': ['Semaglutide (Ozempic/Wegovy)', 'Tirzepatide (Mounjaro)', 'Liraglutide', 'Dulaglutide'],
        'drug_status': 'FDA Approved (blockbuster)',
        'pdb_ids': ['5VAI', '6X18', '7KI0'],
        'druggable': True,
    },
    'GIPR': {
        'protein': 'Glucose-dependent insulinotropic polypeptide receptor',
        'function': 'Incretin signaling',
        'pathway': 'GIP/cAMP pathway',
        'diseases': ['Type 2 Diabetes', 'Obesity'],
        'drugs': ['Tirzepatide (Mounjaro)', 'Retatrutide (triple agonist)'],
        'drug_status': 'FDA Approved (dual/triple agonists)',
        'pdb_ids': ['7DTY'],
        'druggable': True,
    },
    'GCGR': {
        'protein': 'Glucagon receptor',
        'function': 'Glucagon signaling, hepatic glucose output',
        'pathway': 'Glucagon/cAMP pathway',
        'diseases': ['Type 2 Diabetes', 'Obesity', 'NASH'],
        'drugs': ['Retatrutide (triple agonist)', 'Glucagon receptor antagonists'],
        'drug_status': 'Phase III',
        'pdb_ids': ['5YQZ', '6LMK'],
        'druggable': True,
    },
    'INSR': {
        'protein': 'Insulin receptor',
        'function': 'Insulin signaling',
        'pathway': 'Insulin/PI3K/AKT pathway',
        'diseases': ['Type 2 Diabetes', 'Insulin Resistance', 'Donohue Syndrome'],
        'drugs': ['Insulin analogs', 'Insulin sensitizers'],
        'drug_status': 'FDA Approved',
        'pdb_ids': ['4ZXB', '6PXV'],
        'druggable': True,
    },
    'PPARG': {
        'protein': 'Peroxisome proliferator-activated receptor gamma',
        'function': 'Nuclear receptor, adipogenesis',
        'pathway': 'PPAR signaling',
        'diseases': ['Type 2 Diabetes', 'Metabolic Syndrome', 'Lipodystrophy'],
        'drugs': ['Pioglitazone (Actos)', 'Rosiglitazone'],
        'drug_status': 'FDA Approved',
        'pdb_ids': ['2PRG', '3CS8'],
        'druggable': True,
    },
    'PPARA': {
        'protein': 'Peroxisome proliferator-activated receptor alpha',
        'function': 'Nuclear receptor, lipid metabolism',
        'pathway': 'PPAR signaling',
        'diseases': ['Dyslipidemia', 'Hypertriglyceridemia'],
        'drugs': ['Fenofibrate', 'Gemfibrozil', 'Pemafibrate'],
        'drug_status': 'FDA Approved',
        'pdb_ids': ['1I7G', '3VI8'],
        'druggable': True,
    },
    'DPP4': {
        'protein': 'Dipeptidyl peptidase-4',
        'function': 'Incretin degradation',
        'pathway': 'GLP-1 inactivation',
        'diseases': ['Type 2 Diabetes'],
        'drugs': ['Sitagliptin (Januvia)', 'Linagliptin', 'Saxagliptin', 'Alogliptin'],
        'drug_status': 'FDA Approved',
        'pdb_ids': ['1X70', '2RGU'],
        'druggable': True,
    },
    'SGLT2': {
        'protein': 'Sodium-glucose cotransporter 2',
        'function': 'Renal glucose reabsorption',
        'pathway': 'Renal glucose handling',
        'diseases': ['Type 2 Diabetes', 'Heart Failure', 'CKD'],
        'drugs': ['Empagliflozin (Jardiance)', 'Dapagliflozin', 'Canagliflozin'],
        'drug_status': 'FDA Approved',
        'pdb_ids': ['7VSI'],
        'druggable': True,
    },
    'KCNJ11': {
        'protein': 'Kir6.2 potassium channel',
        'function': 'ATP-sensitive K+ channel',
        'pathway': 'Insulin secretion',
        'diseases': ['Neonatal Diabetes', 'MODY', 'Hyperinsulinism'],
        'drugs': ['Sulfonylureas (glibenclamide)', 'Glinides'],
        'drug_status': 'FDA Approved',
        'pdb_ids': ['6BAA'],
        'druggable': True,
    },
    'ABCC8': {
        'protein': 'Sulfonylurea receptor 1 (SUR1)',
        'function': 'ATP-sensitive K+ channel regulation',
        'pathway': 'Insulin secretion',
        'diseases': ['Neonatal Diabetes', 'Hyperinsulinism', 'MODY'],
        'drugs': ['Sulfonylureas', 'Diazoxide'],
        'drug_status': 'FDA Approved',
        'pdb_ids': ['6BAA', '7S5V'],
        'druggable': True,
    },
    'GCK': {
        'protein': 'Glucokinase',
        'function': 'Glucose sensing, glycolysis',
        'pathway': 'Glucose metabolism',
        'diseases': ['MODY2', 'Hyperinsulinism', 'Neonatal Diabetes'],
        'drugs': ['Glucokinase activators (dorzagliatin)'],
        'drug_status': 'Approved (China)',
        'pdb_ids': ['1V4S', '3F9M'],
        'druggable': True,
    },
    'HNF1A': {
        'protein': 'Hepatocyte nuclear factor 1-alpha',
        'function': 'Transcription factor',
        'pathway': 'Beta cell development',
        'diseases': ['MODY3', 'Type 2 Diabetes'],
        'drugs': ['Sulfonylureas (sensitive)'],
        'drug_status': 'Pharmacogenomic marker',
        'pdb_ids': ['1IC8'],
        'druggable': False,
    },
    'HNF4A': {
        'protein': 'Hepatocyte nuclear factor 4-alpha',
        'function': 'Nuclear receptor transcription factor',
        'pathway': 'Beta cell function',
        'diseases': ['MODY1', 'Type 2 Diabetes'],
        'drugs': ['Sulfonylureas (sensitive)'],
        'drug_status': 'Pharmacogenomic marker',
        'pdb_ids': ['1M7W', '4IQR'],
        'druggable': False,
    },
    'TSHR': {
        'protein': 'Thyroid stimulating hormone receptor',
        'function': 'TSH signaling',
        'pathway': 'Thyroid hormone axis',
        'diseases': ['Graves Disease', 'Thyroid Cancer', 'Hypothyroidism'],
        'drugs': ['Antithyroid drugs (methimazole)', 'Radioiodine', 'Levothyroxine'],
        'drug_status': 'FDA Approved (indirect)',
        'pdb_ids': ['7T9I'],
        'druggable': True,
    },
    'MC4R': {
        'protein': 'Melanocortin 4 receptor',
        'function': 'Appetite regulation',
        'pathway': 'Leptin-melanocortin pathway',
        'diseases': ['Obesity (monogenic)', 'Hyperphagia'],
        'drugs': ['Setmelanotide (Imcivree)'],
        'drug_status': 'FDA Approved (2020)',
        'pdb_ids': ['6W25'],
        'druggable': True,
    },
    'LEPR': {
        'protein': 'Leptin receptor',
        'function': 'Leptin signaling',
        'pathway': 'Leptin-melanocortin pathway',
        'diseases': ['Obesity (monogenic)', 'Leptin Receptor Deficiency'],
        'drugs': ['Setmelanotide (Imcivree)'],
        'drug_status': 'FDA Approved',
        'pdb_ids': ['3V6O'],
        'druggable': True,
    },
    'POMC': {
        'protein': 'Pro-opiomelanocortin',
        'function': 'Melanocortin precursor',
        'pathway': 'Leptin-melanocortin pathway',
        'diseases': ['Obesity (POMC deficiency)', 'Adrenal Insufficiency'],
        'drugs': ['Setmelanotide (Imcivree)'],
        'drug_status': 'FDA Approved',
        'pdb_ids': [],
        'druggable': True,
    },
    'PCSK1': {
        'protein': 'Proprotein convertase subtilisin/kexin type 1',
        'function': 'Prohormone processing',
        'pathway': 'Leptin-melanocortin pathway',
        'diseases': ['Obesity (PCSK1 deficiency)', 'Malabsorptive Diarrhea'],
        'drugs': ['Setmelanotide (Imcivree)'],
        'drug_status': 'FDA Approved',
        'pdb_ids': ['1KN6'],
        'druggable': True,
    },
    'NPC1L1': {
        'protein': 'Niemann-Pick C1-Like 1',
        'function': 'Intestinal cholesterol absorption',
        'pathway': 'Cholesterol absorption',
        'diseases': ['Hypercholesterolemia', 'Sitosterolemia'],
        'drugs': ['Ezetimibe (Zetia)'],
        'drug_status': 'FDA Approved',
        'pdb_ids': ['6V3H'],
        'druggable': True,
    },
    'ANGPTL3': {
        'protein': 'Angiopoietin-like 3',
        'function': 'Lipoprotein lipase inhibition',
        'pathway': 'Lipid metabolism',
        'diseases': ['Familial Hypercholesterolemia', 'Hypertriglyceridemia'],
        'drugs': ['Evinacumab (Evkeeza)', 'Vupanorsen (ASO)'],
        'drug_status': 'FDA Approved (2021)',
        'pdb_ids': ['4JB9'],
        'druggable': True,
    },
    'CETP': {
        'protein': 'Cholesteryl ester transfer protein',
        'function': 'HDL/LDL cholesterol exchange',
        'pathway': 'Reverse cholesterol transport',
        'diseases': ['Dyslipidemia', 'Cardiovascular Disease'],
        'drugs': ['Obicetrapib (Phase III)', 'Anacetrapib (discontinued)'],
        'drug_status': 'Phase III',
        'pdb_ids': ['2OBD'],
        'druggable': True,
    },
    'HMGCR': {
        'protein': 'HMG-CoA reductase',
        'function': 'Cholesterol biosynthesis',
        'pathway': 'Mevalonate pathway',
        'diseases': ['Hypercholesterolemia', 'Cardiovascular Disease'],
        'drugs': ['Atorvastatin (Lipitor)', 'Rosuvastatin', 'Simvastatin', 'Pravastatin'],
        'drug_status': 'FDA Approved (blockbuster)',
        'pdb_ids': ['1HWK', '1HW9'],
        'druggable': True,
    },

    # =========================================================================
    # INFECTIOUS DISEASE (NEW SECTION)
    # =========================================================================

    'HIV1_RT': {
        'protein': 'HIV-1 Reverse Transcriptase',
        'function': 'Viral RNA to DNA conversion',
        'pathway': 'HIV replication',
        'diseases': ['HIV/AIDS'],
        'drugs': ['Tenofovir', 'Emtricitabine', 'Lamivudine', 'Efavirenz', 'Doravirine'],
        'drug_status': 'FDA Approved',
        'pdb_ids': ['1RTD', '3V81'],
        'druggable': True,
    },
    'HIV1_PR': {
        'protein': 'HIV-1 Protease',
        'function': 'Viral polyprotein cleavage',
        'pathway': 'HIV replication',
        'diseases': ['HIV/AIDS'],
        'drugs': ['Darunavir', 'Atazanavir', 'Lopinavir', 'Ritonavir'],
        'drug_status': 'FDA Approved',
        'pdb_ids': ['1HVR', '3OXC'],
        'druggable': True,
    },
    'HIV1_IN': {
        'protein': 'HIV-1 Integrase',
        'function': 'Viral DNA integration',
        'pathway': 'HIV replication',
        'diseases': ['HIV/AIDS'],
        'drugs': ['Dolutegravir (Tivicay)', 'Bictegravir', 'Cabotegravir', 'Raltegravir'],
        'drug_status': 'FDA Approved',
        'pdb_ids': ['3OYA', '6PUW'],
        'druggable': True,
    },
    'CCR5': {
        'protein': 'C-C chemokine receptor type 5',
        'function': 'HIV co-receptor',
        'pathway': 'HIV entry',
        'diseases': ['HIV/AIDS'],
        'drugs': ['Maraviroc (Selzentry)', 'Leronlimab'],
        'drug_status': 'FDA Approved',
        'pdb_ids': ['4MBS', '6AKX'],
        'druggable': True,
    },
    'CD4': {
        'protein': 'CD4 receptor',
        'function': 'HIV primary receptor, T-cell co-receptor',
        'pathway': 'HIV entry, T-cell activation',
        'diseases': ['HIV/AIDS'],
        'drugs': ['Ibalizumab (Trogarzo)'],
        'drug_status': 'FDA Approved (2018)',
        'pdb_ids': ['1CDH', '3JWD'],
        'druggable': True,
    },
    'HCV_NS3': {
        'protein': 'HCV NS3/4A Protease',
        'function': 'Viral polyprotein processing',
        'pathway': 'HCV replication',
        'diseases': ['Hepatitis C'],
        'drugs': ['Glecaprevir', 'Voxilaprevir', 'Grazoprevir', 'Paritaprevir'],
        'drug_status': 'FDA Approved',
        'pdb_ids': ['3SUD', '4WF8'],
        'druggable': True,
    },
    'HCV_NS5A': {
        'protein': 'HCV NS5A protein',
        'function': 'Viral replication complex',
        'pathway': 'HCV replication',
        'diseases': ['Hepatitis C'],
        'drugs': ['Ledipasvir', 'Velpatasvir', 'Pibrentasvir', 'Elbasvir'],
        'drug_status': 'FDA Approved',
        'pdb_ids': ['3FQM', '4CL1'],
        'druggable': True,
    },
    'HCV_NS5B': {
        'protein': 'HCV NS5B RNA polymerase',
        'function': 'Viral RNA replication',
        'pathway': 'HCV replication',
        'diseases': ['Hepatitis C'],
        'drugs': ['Sofosbuvir (Sovaldi)', 'Dasabuvir'],
        'drug_status': 'FDA Approved (curative)',
        'pdb_ids': ['1NB7', '4WTG'],
        'druggable': True,
    },
    'HBV_RT': {
        'protein': 'HBV Polymerase/Reverse Transcriptase',
        'function': 'Viral DNA synthesis',
        'pathway': 'HBV replication',
        'diseases': ['Hepatitis B', 'Hepatocellular Carcinoma'],
        'drugs': ['Tenofovir', 'Entecavir', 'Lamivudine'],
        'drug_status': 'FDA Approved',
        'pdb_ids': [],
        'druggable': True,
    },
    'SARS2_MPRO': {
        'protein': 'SARS-CoV-2 Main Protease (3CLpro)',
        'function': 'Viral polyprotein cleavage',
        'pathway': 'Coronavirus replication',
        'diseases': ['COVID-19'],
        'drugs': ['Nirmatrelvir (Paxlovid)', 'Ensitrelvir'],
        'drug_status': 'FDA Approved/EUA',
        'pdb_ids': ['6LU7', '7RFS'],
        'druggable': True,
    },
    'SARS2_RDRP': {
        'protein': 'SARS-CoV-2 RNA-dependent RNA polymerase',
        'function': 'Viral RNA replication',
        'pathway': 'Coronavirus replication',
        'diseases': ['COVID-19'],
        'drugs': ['Remdesivir (Veklury)', 'Molnupiravir'],
        'drug_status': 'FDA Approved',
        'pdb_ids': ['7BV2', '7CTT'],
        'druggable': True,
    },
    'SARS2_SPIKE': {
        'protein': 'SARS-CoV-2 Spike protein',
        'function': 'Viral entry receptor binding',
        'pathway': 'Coronavirus entry',
        'diseases': ['COVID-19'],
        'drugs': ['Bebtelovimab', 'Sotrovimab', 'COVID vaccines'],
        'drug_status': 'FDA Approved/EUA',
        'pdb_ids': ['6VXX', '7BNM'],
        'druggable': True,
    },
    'ACE2': {
        'protein': 'Angiotensin-converting enzyme 2',
        'function': 'SARS-CoV-2 receptor, RAS regulation',
        'pathway': 'Coronavirus entry, blood pressure',
        'diseases': ['COVID-19', 'Hypertension'],
        'drugs': ['Recombinant ACE2 (research)'],
        'drug_status': 'Research',
        'pdb_ids': ['1R42', '6M0J'],
        'druggable': True,
    },
    'TMPRSS2': {
        'protein': 'Transmembrane serine protease 2',
        'function': 'Spike protein priming',
        'pathway': 'Coronavirus entry',
        'diseases': ['COVID-19', 'Prostate Cancer'],
        'drugs': ['Camostat', 'Nafamostat'],
        'drug_status': 'Off-label/Research',
        'pdb_ids': ['7MEQ'],
        'druggable': True,
    },
    'DHFR': {
        'protein': 'Dihydrofolate reductase',
        'function': 'Folate metabolism',
        'pathway': 'Nucleotide biosynthesis',
        'diseases': ['Bacterial infections', 'Malaria', 'Cancer'],
        'drugs': ['Trimethoprim', 'Pyrimethamine', 'Methotrexate'],
        'drug_status': 'FDA Approved',
        'pdb_ids': ['1DLS', '4M6J'],
        'druggable': True,
    },
    'DHPS': {
        'protein': 'Dihydropteroate synthase',
        'function': 'Folate biosynthesis',
        'pathway': 'Folate pathway',
        'diseases': ['Bacterial infections'],
        'drugs': ['Sulfamethoxazole', 'Sulfadiazine', 'Dapsone'],
        'drug_status': 'FDA Approved',
        'pdb_ids': ['1AD4'],
        'druggable': True,
    },
    'GYRA': {
        'protein': 'DNA gyrase subunit A',
        'function': 'DNA supercoiling',
        'pathway': 'DNA replication',
        'diseases': ['Bacterial infections'],
        'drugs': ['Ciprofloxacin', 'Levofloxacin', 'Moxifloxacin'],
        'drug_status': 'FDA Approved',
        'pdb_ids': ['2XCT', '3RAD'],
        'druggable': True,
    },
    'RPOB': {
        'protein': 'RNA polymerase beta subunit',
        'function': 'Bacterial transcription',
        'pathway': 'Transcription',
        'diseases': ['Tuberculosis', 'Bacterial infections'],
        'drugs': ['Rifampin', 'Rifabutin', 'Rifapentine'],
        'drug_status': 'FDA Approved',
        'pdb_ids': ['1I6V'],
        'druggable': True,
    },
    'INHA': {
        'protein': 'Enoyl-ACP reductase',
        'function': 'Mycolic acid biosynthesis',
        'pathway': 'Cell wall synthesis',
        'diseases': ['Tuberculosis'],
        'drugs': ['Isoniazid'],
        'drug_status': 'FDA Approved',
        'pdb_ids': ['1ENY', '4TRO'],
        'druggable': True,
    },
    'CYP51A1': {
        'protein': 'Lanosterol 14-alpha demethylase',
        'function': 'Ergosterol biosynthesis',
        'pathway': 'Fungal cell membrane',
        'diseases': ['Fungal infections', 'Candidiasis', 'Aspergillosis'],
        'drugs': ['Fluconazole', 'Itraconazole', 'Voriconazole', 'Posaconazole'],
        'drug_status': 'FDA Approved',
        'pdb_ids': ['3LD6', '5TZ1'],
        'druggable': True,
    },
    'FKS1': {
        'protein': 'Beta-1,3-glucan synthase',
        'function': 'Fungal cell wall synthesis',
        'pathway': 'Cell wall biosynthesis',
        'diseases': ['Invasive Candidiasis', 'Aspergillosis'],
        'drugs': ['Caspofungin', 'Micafungin', 'Anidulafungin', 'Rezafungin'],
        'drug_status': 'FDA Approved',
        'pdb_ids': [],
        'druggable': True,
    },

    # =========================================================================
    # RESPIRATORY / PULMONARY (NEW SECTION)
    # =========================================================================

    'ADRB2': {
        'protein': 'Beta-2 adrenergic receptor',
        'function': 'Bronchodilation',
        'pathway': 'cAMP/PKA signaling',
        'diseases': ['Asthma', 'COPD'],
        'drugs': ['Albuterol', 'Salmeterol', 'Formoterol', 'Vilanterol'],
        'drug_status': 'FDA Approved',
        'pdb_ids': ['2RH1', '3SN6'],
        'druggable': True,
    },
    'CHRM3': {
        'protein': 'Muscarinic acetylcholine receptor M3',
        'function': 'Bronchoconstriction',
        'pathway': 'Cholinergic signaling',
        'diseases': ['COPD', 'Asthma'],
        'drugs': ['Tiotropium (Spiriva)', 'Ipratropium', 'Umeclidinium', 'Glycopyrrolate'],
        'drug_status': 'FDA Approved',
        'pdb_ids': ['4DAJ', '4U14'],
        'druggable': True,
    },
    'PDE4D': {
        'protein': 'Phosphodiesterase 4D',
        'function': 'cAMP degradation',
        'pathway': 'cAMP signaling',
        'diseases': ['COPD', 'Psoriasis'],
        'drugs': ['Roflumilast (Daliresp)', 'Apremilast'],
        'drug_status': 'FDA Approved',
        'pdb_ids': ['1XMY', '3IAD'],
        'druggable': True,
    },
    'IL5': {
        'protein': 'Interleukin-5',
        'function': 'Eosinophil activation',
        'pathway': 'Type 2 inflammation',
        'diseases': ['Eosinophilic Asthma', 'Hypereosinophilic Syndrome'],
        'drugs': ['Mepolizumab (Nucala)', 'Reslizumab'],
        'drug_status': 'FDA Approved',
        'pdb_ids': ['1HUL'],
        'druggable': True,
    },
    'IL5RA': {
        'protein': 'Interleukin-5 receptor alpha',
        'function': 'Eosinophil signaling',
        'pathway': 'Type 2 inflammation',
        'diseases': ['Severe Eosinophilic Asthma'],
        'drugs': ['Benralizumab (Fasenra)'],
        'drug_status': 'FDA Approved',
        'pdb_ids': ['3VA2'],
        'druggable': True,
    },
    'IL4R': {
        'protein': 'Interleukin-4 receptor alpha',
        'function': 'IL-4/IL-13 signaling',
        'pathway': 'Type 2 inflammation',
        'diseases': ['Asthma', 'Atopic Dermatitis', 'Eosinophilic Esophagitis'],
        'drugs': ['Dupilumab (Dupixent)'],
        'drug_status': 'FDA Approved (blockbuster)',
        'pdb_ids': ['3BPL'],
        'druggable': True,
    },
    'IL13': {
        'protein': 'Interleukin-13',
        'function': 'Type 2 cytokine',
        'pathway': 'Type 2 inflammation',
        'diseases': ['Asthma', 'Atopic Dermatitis', 'IPF'],
        'drugs': ['Lebrikizumab', 'Tralokinumab (Adbry)'],
        'drug_status': 'FDA Approved',
        'pdb_ids': ['3BPO'],
        'druggable': True,
    },
    'FCER1A': {
        'protein': 'High-affinity IgE receptor alpha',
        'function': 'IgE binding on mast cells',
        'pathway': 'Allergic response',
        'diseases': ['Allergic Asthma', 'Chronic Urticaria'],
        'drugs': ['Omalizumab (Xolair) - targets IgE'],
        'drug_status': 'FDA Approved',
        'pdb_ids': ['1F6A'],
        'druggable': True,
    },
    'SERPINA1': {
        'protein': 'Alpha-1 antitrypsin',
        'function': 'Neutrophil elastase inhibition',
        'pathway': 'Protease-antiprotease balance',
        'diseases': ['Alpha-1 Antitrypsin Deficiency', 'COPD', 'Liver Disease'],
        'drugs': ['Alpha-1 proteinase inhibitor (Prolastin)', 'Zemaira', 'Glassia'],
        'drug_status': 'FDA Approved (augmentation therapy)',
        'pdb_ids': ['1QLP', '3NE4'],
        'druggable': True,
    },
    'BMPR2': {
        'protein': 'Bone morphogenetic protein receptor type 2',
        'function': 'BMP signaling',
        'pathway': 'TGF-beta/BMP pathway',
        'diseases': ['Pulmonary Arterial Hypertension', 'Hereditary PAH'],
        'drugs': ['Sotatercept (Winrevair)'],
        'drug_status': 'FDA Approved (2024)',
        'pdb_ids': ['2HLQ'],
        'druggable': True,
    },
    'EDNRA': {
        'protein': 'Endothelin receptor type A',
        'function': 'Endothelin signaling, vasoconstriction',
        'pathway': 'Endothelin pathway',
        'diseases': ['Pulmonary Arterial Hypertension'],
        'drugs': ['Ambrisentan (Letairis)', 'Macitentan (Opsumit)', 'Bosentan'],
        'drug_status': 'FDA Approved',
        'pdb_ids': ['5GLH'],
        'druggable': True,
    },
    'PDE5A': {
        'protein': 'Phosphodiesterase 5A',
        'function': 'cGMP degradation',
        'pathway': 'NO/cGMP pathway',
        'diseases': ['Pulmonary Arterial Hypertension', 'Erectile Dysfunction'],
        'drugs': ['Sildenafil (Revatio)', 'Tadalafil (Adcirca)'],
        'drug_status': 'FDA Approved',
        'pdb_ids': ['1TBF', '1UDT'],
        'druggable': True,
    },
    'GUCY1A1': {
        'protein': 'Soluble guanylate cyclase alpha-1',
        'function': 'cGMP production',
        'pathway': 'NO/cGMP pathway',
        'diseases': ['Pulmonary Arterial Hypertension', 'Heart Failure'],
        'drugs': ['Riociguat (Adempas)', 'Vericiguat (Verquvo)'],
        'drug_status': 'FDA Approved',
        'pdb_ids': ['6JT0'],
        'druggable': True,
    },

    # =========================================================================
    # OPHTHALMOLOGY (NEW SECTION)
    # =========================================================================

    'VEGFA': {
        'protein': 'Vascular endothelial growth factor A',
        'function': 'Angiogenesis',
        'pathway': 'VEGF signaling',
        'diseases': ['Age-related Macular Degeneration', 'Diabetic Retinopathy', 'DME'],
        'drugs': ['Aflibercept (Eylea)', 'Ranibizumab (Lucentis)', 'Bevacizumab', 'Faricimab'],
        'drug_status': 'FDA Approved (blockbuster)',
        'pdb_ids': ['1VPF', '4GLS'],
        'druggable': True,
    },
    'CFH': {
        'protein': 'Complement factor H',
        'function': 'Complement regulation',
        'pathway': 'Alternative complement pathway',
        'diseases': ['Age-related Macular Degeneration', 'Atypical HUS'],
        'drugs': ['Pegcetacoplan (Syfovre)', 'Avacincaptad pegol (Izervay)'],
        'drug_status': 'FDA Approved (2023)',
        'pdb_ids': ['2UWN', '3R62'],
        'druggable': True,
    },
    'C3': {
        'protein': 'Complement component 3',
        'function': 'Central complement component',
        'pathway': 'Complement cascade',
        'diseases': ['Geographic Atrophy AMD', 'PNH', 'C3 Glomerulopathy'],
        'drugs': ['Pegcetacoplan (Syfovre/Empaveli)'],
        'drug_status': 'FDA Approved',
        'pdb_ids': ['2A73', '6RUR'],
        'druggable': True,
    },
    'C5': {
        'protein': 'Complement component 5',
        'function': 'Terminal complement component',
        'pathway': 'Complement cascade',
        'diseases': ['PNH', 'aHUS', 'Myasthenia Gravis', 'Geographic Atrophy'],
        'drugs': ['Eculizumab (Soliris)', 'Ravulizumab (Ultomiris)', 'Avacincaptad pegol'],
        'drug_status': 'FDA Approved',
        'pdb_ids': ['3CU7', '5I5K'],
        'druggable': True,
    },
    'RHO': {
        'protein': 'Rhodopsin',
        'function': 'Phototransduction',
        'pathway': 'Visual cycle',
        'diseases': ['Retinitis Pigmentosa', 'Congenital Stationary Night Blindness'],
        'drugs': ['Gene therapy (research)'],
        'drug_status': 'Research/Phase I',
        'pdb_ids': ['1F88', '4ZWJ'],
        'druggable': True,
    },
    'RPE65': {
        'protein': 'Retinal pigment epithelium 65 kDa protein',
        'function': 'Visual cycle enzyme',
        'pathway': 'Retinoid metabolism',
        'diseases': ['Leber Congenital Amaurosis', 'Retinitis Pigmentosa'],
        'drugs': ['Voretigene neparvovec (Luxturna)'],
        'drug_status': 'FDA Approved (gene therapy)',
        'pdb_ids': ['4F2Z'],
        'druggable': True,
    },
    'BEST1': {
        'protein': 'Bestrophin-1',
        'function': 'Chloride channel',
        'pathway': 'RPE ion transport',
        'diseases': ['Best Vitelliform Macular Dystrophy', 'ADVIRC'],
        'drugs': ['Gene therapy (research)'],
        'drug_status': 'Research',
        'pdb_ids': ['4RDQ'],
        'druggable': False,
    },
    'ABCA4': {
        'protein': 'ABCA4 transporter',
        'function': 'Retinal N-retinylidene-PE transport',
        'pathway': 'Visual cycle',
        'diseases': ['Stargardt Disease', 'Cone-Rod Dystrophy'],
        'drugs': ['ALK-001 (vitamin A modulator)', 'Gene therapy'],
        'drug_status': 'Phase II/III',
        'pdb_ids': [],
        'druggable': True,
    },
    'USH2A': {
        'protein': 'Usherin',
        'function': 'Photoreceptor structure',
        'pathway': 'Photoreceptor maintenance',
        'diseases': ['Usher Syndrome Type 2A', 'Retinitis Pigmentosa'],
        'drugs': ['QR-421a (ASO)', 'Gene therapy'],
        'drug_status': 'Phase II/III',
        'pdb_ids': [],
        'druggable': True,
    },
    'ROCK1': {
        'protein': 'Rho-associated protein kinase 1',
        'function': 'Cytoskeleton regulation',
        'pathway': 'Rho/ROCK signaling',
        'diseases': ['Glaucoma', 'Fibrosis'],
        'drugs': ['Netarsudil (Rhopressa)', 'Ripasudil'],
        'drug_status': 'FDA Approved',
        'pdb_ids': ['2ESM', '3TV7'],
        'druggable': True,
    },
    'CA2': {
        'protein': 'Carbonic anhydrase 2',
        'function': 'Aqueous humor production',
        'pathway': 'Bicarbonate metabolism',
        'diseases': ['Glaucoma', 'Ocular Hypertension'],
        'drugs': ['Dorzolamide', 'Brinzolamide', 'Acetazolamide'],
        'drug_status': 'FDA Approved',
        'pdb_ids': ['1CA2', '3HS4'],
        'druggable': True,
    },

    # =========================================================================
    # DERMATOLOGY (NEW SECTION)
    # =========================================================================

    'IL31RA': {
        'protein': 'Interleukin-31 receptor A',
        'function': 'Itch/pruritus signaling',
        'pathway': 'IL-31 signaling',
        'diseases': ['Atopic Dermatitis', 'Prurigo Nodularis'],
        'drugs': ['Nemolizumab'],
        'drug_status': 'FDA Approved (2024)',
        'pdb_ids': [],
        'druggable': True,
    },
    'IL36RN': {
        'protein': 'Interleukin-36 receptor antagonist',
        'function': 'IL-36 signaling inhibition',
        'pathway': 'IL-36/IL-1 family signaling',
        'diseases': ['Generalized Pustular Psoriasis', 'DITRA'],
        'drugs': ['Spesolimab (Spevigo)'],
        'drug_status': 'FDA Approved (2022)',
        'pdb_ids': [],
        'druggable': True,
    },
    'OSM': {
        'protein': 'Oncostatin M',
        'function': 'IL-6 family cytokine',
        'pathway': 'JAK/STAT signaling',
        'diseases': ['Atopic Dermatitis', 'Prurigo Nodularis'],
        'drugs': ['Nemolizumab targets OSM signaling'],
        'drug_status': 'Approved',
        'pdb_ids': ['1EVS'],
        'druggable': True,
    },
    'TYK2': {
        'protein': 'Tyrosine kinase 2',
        'function': 'JAK family kinase',
        'pathway': 'JAK/STAT signaling',
        'diseases': ['Psoriasis', 'Psoriatic Arthritis', 'IBD'],
        'drugs': ['Deucravacitinib (Sotyktu)'],
        'drug_status': 'FDA Approved (2022)',
        'pdb_ids': ['3LXN', '4GVJ'],
        'druggable': True,
    },
    'KIT': {
        'protein': 'Stem cell factor receptor (c-Kit)',
        'function': 'Receptor tyrosine kinase',
        'pathway': 'KIT/SCF signaling',
        'diseases': ['Mastocytosis', 'GIST', 'Melanoma'],
        'drugs': ['Imatinib', 'Avapritinib (Ayvakit)', 'Ripretinib'],
        'drug_status': 'FDA Approved',
        'pdb_ids': ['1T45', '6MOB'],
        'druggable': True,
    },
    'COL7A1': {
        'protein': 'Collagen type VII alpha 1',
        'function': 'Anchoring fibril component',
        'pathway': 'Basement membrane adhesion',
        'diseases': ['Dystrophic Epidermolysis Bullosa'],
        'drugs': ['Beremagene geperpavec (Vyjuvek)', 'Gene therapy'],
        'drug_status': 'FDA Approved (2023 - gene therapy)',
        'pdb_ids': [],
        'druggable': True,
    },
    'TGM1': {
        'protein': 'Transglutaminase 1',
        'function': 'Cornified envelope formation',
        'pathway': 'Epidermal differentiation',
        'diseases': ['Lamellar Ichthyosis', 'Congenital Ichthyosiform Erythroderma'],
        'drugs': ['Gene therapy (research)'],
        'drug_status': 'Research',
        'pdb_ids': ['1L9M'],
        'druggable': False,
    },
    'SPINK5': {
        'protein': 'Serine protease inhibitor Kazal-type 5 (LEKTI)',
        'function': 'Serine protease inhibition',
        'pathway': 'Epidermal barrier',
        'diseases': ['Netherton Syndrome', 'Atopic Dermatitis'],
        'drugs': ['Gene therapy (research)'],
        'drug_status': 'Research',
        'pdb_ids': ['4IS5'],
        'druggable': False,
    },
    'FLG': {
        'protein': 'Filaggrin',
        'function': 'Epidermal barrier protein',
        'pathway': 'Skin barrier formation',
        'diseases': ['Atopic Dermatitis', 'Ichthyosis Vulgaris'],
        'drugs': ['Barrier repair strategies'],
        'drug_status': 'Biomarker',
        'pdb_ids': [],
        'druggable': False,
    },

    # =========================================================================
    # HEMATOLOGY (NEW SECTION - Beyond Rare Disease)
    # =========================================================================

    'SYK': {
        'protein': 'Spleen tyrosine kinase',
        'function': 'BCR/FcR signaling',
        'pathway': 'B-cell/platelet signaling',
        'diseases': ['Immune Thrombocytopenia', 'Autoimmune Hemolytic Anemia', 'CLL'],
        'drugs': ['Fostamatinib (Tavalisse)', 'Entospletinib'],
        'drug_status': 'FDA Approved',
        'pdb_ids': ['1XBA', '4FL2'],
        'druggable': True,
    },
    'THPO': {
        'protein': 'Thrombopoietin',
        'function': 'Megakaryocyte growth factor',
        'pathway': 'Thrombopoiesis',
        'diseases': ['Immune Thrombocytopenia', 'Aplastic Anemia'],
        'drugs': ['Romiplostim (Nplate)', 'Eltrombopag', 'Avatrombopag', 'Lusutrombopag'],
        'drug_status': 'FDA Approved',
        'pdb_ids': ['1V7M'],
        'druggable': True,
    },
    'MPL': {
        'protein': 'Thrombopoietin receptor (c-Mpl)',
        'function': 'TPO receptor',
        'pathway': 'Thrombopoiesis',
        'diseases': ['Myeloproliferative Neoplasms', 'Immune Thrombocytopenia'],
        'drugs': ['TPO receptor agonists'],
        'drug_status': 'FDA Approved',
        'pdb_ids': ['1V7N'],
        'druggable': True,
    },
    'EPOR': {
        'protein': 'Erythropoietin receptor',
        'function': 'EPO signaling',
        'pathway': 'Erythropoiesis',
        'diseases': ['Anemia', 'Polycythemia'],
        'drugs': ['Epoetin alfa (Epogen)', 'Darbepoetin alfa'],
        'drug_status': 'FDA Approved',
        'pdb_ids': ['1EER', '1CN4'],
        'druggable': True,
    },
    'HIF2A': {
        'protein': 'Hypoxia-inducible factor 2-alpha',
        'function': 'Hypoxia response transcription factor',
        'pathway': 'HIF pathway',
        'diseases': ['Renal Cell Carcinoma', 'Anemia of CKD'],
        'drugs': ['Belzutifan (Welireg)', 'Roxadustat (PHD inhibitor)'],
        'drug_status': 'FDA Approved',
        'pdb_ids': ['4XT2', '6E3S'],
        'druggable': True,
    },
    'CALR': {
        'protein': 'Calreticulin',
        'function': 'ER chaperone, TPO receptor activation',
        'pathway': 'JAK/STAT signaling',
        'diseases': ['Essential Thrombocythemia', 'Primary Myelofibrosis'],
        'drugs': ['JAK inhibitors (ruxolitinib)'],
        'drug_status': 'Biomarker + JAK inhibitors',
        'pdb_ids': ['1HHN'],
        'druggable': False,
    },
    'CXCR4': {
        'protein': 'C-X-C chemokine receptor type 4',
        'function': 'Stem cell homing, chemotaxis',
        'pathway': 'CXCL12/CXCR4 axis',
        'diseases': ['WHIM Syndrome', 'Waldenstrom Macroglobulinemia', 'AML'],
        'drugs': ['Plerixafor (Mozobil)', 'Mavorixafor'],
        'drug_status': 'FDA Approved',
        'pdb_ids': ['3ODU', '4RWS'],
        'druggable': True,
    },
    'ADAMTS13': {
        'protein': 'A disintegrin and metalloproteinase with thrombospondin motifs 13',
        'function': 'von Willebrand factor cleavage',
        'pathway': 'Hemostasis',
        'diseases': ['Thrombotic Thrombocytopenic Purpura (TTP)'],
        'drugs': ['Caplacizumab (Cablivi)', 'Recombinant ADAMTS13'],
        'drug_status': 'FDA Approved',
        'pdb_ids': ['3GHM'],
        'druggable': True,
    },
    'VWF': {
        'protein': 'von Willebrand factor',
        'function': 'Platelet adhesion, FVIII carrier',
        'pathway': 'Primary hemostasis',
        'diseases': ['von Willebrand Disease', 'TTP'],
        'drugs': ['Caplacizumab (anti-VWF)', 'VWF concentrates'],
        'drug_status': 'FDA Approved',
        'pdb_ids': ['1AUQ', '1M10'],
        'druggable': True,
    },
    'SERPINC1': {
        'protein': 'Antithrombin III',
        'function': 'Thrombin/FXa inhibition',
        'pathway': 'Coagulation regulation',
        'diseases': ['Antithrombin Deficiency', 'Thrombophilia'],
        'drugs': ['Antithrombin concentrates', 'Fitusiran (siRNA - for hemophilia)'],
        'drug_status': 'FDA Approved',
        'pdb_ids': ['1E05', '2ANT'],
        'druggable': True,
    },
    'F10': {
        'protein': 'Coagulation factor X',
        'function': 'Coagulation protease',
        'pathway': 'Common coagulation pathway',
        'diseases': ['Thrombosis', 'Atrial Fibrillation'],
        'drugs': ['Rivaroxaban (Xarelto)', 'Apixaban (Eliquis)', 'Edoxaban', 'Betrixaban'],
        'drug_status': 'FDA Approved',
        'pdb_ids': ['1FJS', '2W26'],
        'druggable': True,
    },
    'F2': {
        'protein': 'Prothrombin (Factor II)',
        'function': 'Thrombin generation',
        'pathway': 'Coagulation cascade',
        'diseases': ['Thrombosis', 'Atrial Fibrillation'],
        'drugs': ['Dabigatran (Pradaxa)'],
        'drug_status': 'FDA Approved',
        'pdb_ids': ['1IHS', '3U69'],
        'druggable': True,
    },

    # =========================================================================
    # GI / HEPATOLOGY (NEW SECTION)
    # =========================================================================

    'ATP4A': {
        'protein': 'Gastric H+/K+ ATPase alpha subunit',
        'function': 'Gastric acid secretion',
        'pathway': 'Proton pump',
        'diseases': ['GERD', 'Peptic Ulcer Disease', 'Zollinger-Ellison Syndrome'],
        'drugs': ['Omeprazole', 'Esomeprazole', 'Pantoprazole', 'Lansoprazole'],
        'drug_status': 'FDA Approved (blockbuster)',
        'pdb_ids': ['5YLU'],
        'druggable': True,
    },
    'KCNQ1_GI': {
        'protein': 'Potassium channel (acid-related)',
        'function': 'Potassium-competitive acid blocker target',
        'pathway': 'Gastric acid secretion',
        'diseases': ['GERD', 'Erosive Esophagitis'],
        'drugs': ['Vonoprazan (Voquezna)'],
        'drug_status': 'FDA Approved (2022)',
        'pdb_ids': ['5VMS'],
        'druggable': True,
    },
    'NOD2': {
        'protein': 'Nucleotide-binding oligomerization domain 2',
        'function': 'Innate immune receptor',
        'pathway': 'NF-kB/autophagy',
        'diseases': ['Crohn Disease', 'Blau Syndrome'],
        'drugs': ['Research compounds'],
        'drug_status': 'Genetic marker',
        'pdb_ids': ['5IRN'],
        'druggable': False,
    },
    'ATG16L1': {
        'protein': 'Autophagy-related 16-like 1',
        'function': 'Autophagosome formation',
        'pathway': 'Autophagy',
        'diseases': ['Crohn Disease', 'IBD'],
        'drugs': ['Autophagy modulators (research)'],
        'drug_status': 'Genetic marker',
        'pdb_ids': ['3A7O'],
        'druggable': False,
    },
    'IL12B': {
        'protein': 'Interleukin-12 subunit beta (p40)',
        'function': 'IL-12/IL-23 shared subunit',
        'pathway': 'Th1/Th17 immunity',
        'diseases': ['Crohn Disease', 'Ulcerative Colitis', 'Psoriasis'],
        'drugs': ['Ustekinumab (Stelara)'],
        'drug_status': 'FDA Approved',
        'pdb_ids': ['1F45', '3HMX'],
        'druggable': True,
    },
    'ITGA4': {
        'protein': 'Integrin alpha-4',
        'function': 'Lymphocyte adhesion/migration',
        'pathway': 'Leukocyte trafficking',
        'diseases': ['Crohn Disease', 'Ulcerative Colitis', 'Multiple Sclerosis'],
        'drugs': ['Vedolizumab (Entyvio)', 'Natalizumab'],
        'drug_status': 'FDA Approved',
        'pdb_ids': ['3V4P'],
        'druggable': True,
    },
    'ITGB7': {
        'protein': 'Integrin beta-7',
        'function': 'Gut-homing integrin',
        'pathway': 'Gut lymphocyte homing',
        'diseases': ['Ulcerative Colitis', 'Crohn Disease'],
        'drugs': ['Vedolizumab (Entyvio)', 'Etrolizumab'],
        'drug_status': 'FDA Approved',
        'pdb_ids': ['3V4V'],
        'druggable': True,
    },
    'S1PR1': {
        'protein': 'Sphingosine-1-phosphate receptor 1',
        'function': 'Lymphocyte egress from lymph nodes',
        'pathway': 'S1P signaling',
        'diseases': ['Ulcerative Colitis', 'Multiple Sclerosis'],
        'drugs': ['Ozanimod (Zeposia)', 'Etrasimod (Velsipity)', 'Fingolimod'],
        'drug_status': 'FDA Approved',
        'pdb_ids': ['3V2Y'],
        'druggable': True,
    },
    'PNPLA3': {
        'protein': 'Patatin-like phospholipase domain-containing 3',
        'function': 'Lipid metabolism',
        'pathway': 'Hepatic lipid storage',
        'diseases': ['NAFLD/NASH', 'Alcoholic Liver Disease', 'Cirrhosis'],
        'drugs': ['ASO/siRNA therapies (research)'],
        'drug_status': 'Genetic risk factor',
        'pdb_ids': [],
        'druggable': True,
    },
    'HSD17B13': {
        'protein': 'Hydroxysteroid 17-beta dehydrogenase 13',
        'function': 'Lipid droplet enzyme',
        'pathway': 'Hepatic lipid metabolism',
        'diseases': ['NAFLD/NASH', 'Cirrhosis'],
        'drugs': ['ARO-HSD (siRNA)', 'ASO therapies'],
        'drug_status': 'Phase II',
        'pdb_ids': [],
        'druggable': True,
    },
    'FXR': {
        'protein': 'Farnesoid X receptor (NR1H4)',
        'function': 'Nuclear receptor, bile acid sensing',
        'pathway': 'Bile acid metabolism',
        'diseases': ['Primary Biliary Cholangitis', 'NASH'],
        'drugs': ['Obeticholic acid (Ocaliva)'],
        'drug_status': 'FDA Approved',
        'pdb_ids': ['1OSV', '3DCT'],
        'druggable': True,
    },
    'THR_BETA': {
        'protein': 'Thyroid hormone receptor beta',
        'function': 'Nuclear receptor',
        'pathway': 'Thyroid hormone signaling',
        'diseases': ['NASH', 'Dyslipidemia'],
        'drugs': ['Resmetirom (Rezdiffra)'],
        'drug_status': 'FDA Approved (2024 - first NASH drug)',
        'pdb_ids': ['1NAX', '3GWS'],
        'druggable': True,
    },
}


# =============================================================================
# HELPER FUNCTIONS
# =============================================================================

def get_knowledge_for_genes(genes: List[str]) -> List[Dict[str, Any]]:
    """
    Get knowledge connections for a list of genes.

    Args:
        genes: List of gene symbols (case-insensitive)

    Returns:
        List of knowledge connection dictionaries with gene included
    """
    connections = []
    seen = set()

    for gene in genes:
        gene_upper = gene.upper()
        if gene_upper in KNOWLEDGE_CONNECTIONS and gene_upper not in seen:
            conn = {'gene': gene_upper, **KNOWLEDGE_CONNECTIONS[gene_upper]}
            connections.append(conn)
            seen.add(gene_upper)

    return connections


def get_knowledge_for_evidence(evidence_list: List[Dict[str, Any]]) -> List[Dict[str, Any]]:
    """
    Extract genes from evidence and return their knowledge connections.

    Args:
        evidence_list: List of evidence dictionaries from Milvus search

    Returns:
        List of knowledge connection dictionaries
    """
    genes = []
    for ev in evidence_list:
        gene = ev.get('gene', '')
        if gene:
            genes.append(gene)

    return get_knowledge_for_genes(genes)


def format_knowledge_for_prompt(evidence_list: List[Dict[str, Any]]) -> str:
    """
    Format knowledge connections as context for Claude's prompt.

    Args:
        evidence_list: List of evidence dictionaries from Milvus search

    Returns:
        Formatted string to include in LLM prompt
    """
    connections = get_knowledge_for_evidence(evidence_list)

    if not connections:
        return ""

    lines = ["## Therapeutic Knowledge Connections (Clinker)\n"]
    lines.append("The following genes from the evidence have known therapeutic relevance:\n")

    for conn in connections:
        gene = conn['gene']
        druggable_marker = " [DRUGGABLE TARGET]" if conn['druggable'] else ""

        lines.append(f"### {gene}{druggable_marker}")
        lines.append(f"- **Protein:** {conn['protein']}")
        lines.append(f"- **Function:** {conn['function']}")
        lines.append(f"- **Pathway:** {conn['pathway']}")
        lines.append(f"- **Associated Diseases:** {', '.join(conn['diseases'])}")
        lines.append(f"- **Therapeutic Options:** {', '.join(conn['drugs'])}")
        lines.append(f"- **Development Status:** {conn['drug_status']}")
        if conn['pdb_ids']:
            lines.append(f"- **Protein Structures (PDB):** {', '.join(conn['pdb_ids'])}")
        lines.append("")

    return "\n".join(lines)


def get_druggable_genes() -> List[str]:
    """Return list of genes marked as druggable targets."""
    return [gene for gene, data in KNOWLEDGE_CONNECTIONS.items() if data['druggable']]


def get_gene_drugs(gene: str) -> Optional[List[str]]:
    """Get list of drugs/therapeutics for a specific gene."""
    gene_upper = gene.upper()
    if gene_upper in KNOWLEDGE_CONNECTIONS:
        return KNOWLEDGE_CONNECTIONS[gene_upper]['drugs']
    return None


def get_genes_by_disease(disease_keyword: str) -> List[str]:
    """Find genes associated with a disease keyword."""
    matches = []
    keyword_lower = disease_keyword.lower()
    for gene, data in KNOWLEDGE_CONNECTIONS.items():
        for disease in data['diseases']:
            if keyword_lower in disease.lower():
                matches.append(gene)
                break
    return matches


def get_genes_by_pathway(pathway_keyword: str) -> List[str]:
    """Find genes in a specific pathway."""
    matches = []
    keyword_lower = pathway_keyword.lower()
    for gene, data in KNOWLEDGE_CONNECTIONS.items():
        if keyword_lower in data['pathway'].lower():
            matches.append(gene)
    return matches


def get_knowledge_stats() -> Dict[str, Any]:
    """Get statistics about the knowledge base."""
    total = len(KNOWLEDGE_CONNECTIONS)
    druggable = sum(1 for data in KNOWLEDGE_CONNECTIONS.values() if data['druggable'])

    # Count by therapeutic area (rough categorization)
    categories = {
        'oncology': 0,
        'cardiovascular': 0,
        'rare_disease': 0,
        'neurology': 0,
        'immunology': 0,
        'pharmacogenomics': 0,
    }

    return {
        'total_genes': total,
        'druggable_targets': druggable,
        'non_druggable': total - druggable,
        'fda_approved_drugs': sum(1 for data in KNOWLEDGE_CONNECTIONS.values()
                                   if 'FDA Approved' in data['drug_status']),
    }
