"""NeMo Guardrails wrapper for clinical imaging AI safety.

Provides input validation, output safety checking, PII sanitization,
and clinical disclaimer injection for the Imaging Intelligence Agent.

Operates in two modes:
  1. **Full mode** — NeMo Guardrails installed, uses the framework's
     rail definitions from config/guardrails/.
  2. **Lite mode** — NeMo Guardrails NOT installed, uses built-in
     regex/pattern-based checks as a fallback.

Author: Adam Jones
Date: April 2026
"""

import re
from pathlib import Path
from typing import List, Optional

from loguru import logger
from pydantic import BaseModel, Field


# ═══════════════════════════════════════════════════════════════════════════════
# Result model
# ═══════════════════════════════════════════════════════════════════════════════

class GuardrailResult(BaseModel):
    """Result of a guardrail safety check."""
    passed: bool
    flags: List[str] = Field(default_factory=list)
    modified_text: Optional[str] = None
    blocked: bool = False


# ═══════════════════════════════════════════════════════════════════════════════
# Clinical disclaimer
# ═══════════════════════════════════════════════════════════════════════════════

CLINICAL_DISCLAIMER = (
    "\n\n---\n"
    "**Clinical Decision Support Notice:** This analysis is generated by an "
    "AI system for informational and research purposes only. It is not a "
    "substitute for professional medical judgment. All findings must be "
    "reviewed and validated by a qualified radiologist or clinician before "
    "any clinical decision-making."
)

DISCLAIMER_SENTINEL = "Clinical Decision Support"


# ═══════════════════════════════════════════════════════════════════════════════
# PII patterns
# ═══════════════════════════════════════════════════════════════════════════════

_PII_PATTERNS = {
    "ssn": re.compile(r"\b\d{3}-\d{2}-\d{4}\b"),
    "mrn": re.compile(r"\bMRN:?\s*\d{4,}\b", re.IGNORECASE),
    "email": re.compile(
        r"\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Z|a-z]{2,}\b"
    ),
    "phone": re.compile(
        r"\b(?:\+?1[-.\s]?)?\(?\d{3}\)?[-.\s]?\d{3}[-.\s]?\d{4}\b"
    ),
}


# ═══════════════════════════════════════════════════════════════════════════════
# Input safety patterns
# ═══════════════════════════════════════════════════════════════════════════════

_INPUT_REJECT_PATTERNS = [
    re.compile(
        r"\b(?:prescribe|prescribing)\b",
        re.IGNORECASE,
    ),
    re.compile(
        r"\bdiagnose\s+definitively\b",
        re.IGNORECASE,
    ),
    re.compile(
        r"\bstop\s+taking\s+medication\b",
        re.IGNORECASE,
    ),
]

_NON_MEDICAL_PATTERNS = [
    re.compile(
        r"\b(?:stock\s+price|weather\s+forecast|sports\s+score|recipe\s+for"
        r"|movie\s+review|write\s+(?:a\s+)?poem|tell\s+(?:me\s+)?a\s+joke"
        r"|how\s+to\s+cook|cryptocurrency|bitcoin)\b",
        re.IGNORECASE,
    ),
]


# ═══════════════════════════════════════════════════════════════════════════════
# Output safety patterns
# ═══════════════════════════════════════════════════════════════════════════════

_ABSOLUTE_DIAGNOSIS_PATTERNS = [
    re.compile(
        r"\bthis\s+(?:is|shows)\s+(?:definitely|certainly|absolutely)\s+",
        re.IGNORECASE,
    ),
    re.compile(
        r"\bthis\s+is\s+(?:cancer|malignant|benign)\b",
        re.IGNORECASE,
    ),
    re.compile(
        r"\bI\s+(?:can\s+)?confirm\s+(?:the\s+)?diagnosis\b",
        re.IGNORECASE,
    ),
    re.compile(
        r"\bdefinitively\s+diagnos",
        re.IGNORECASE,
    ),
]

_CONTRAINDICATED_PATTERNS = [
    re.compile(
        r"\byou\s+(?:should|must)\s+(?:stop|discontinue)\s+",
        re.IGNORECASE,
    ),
    re.compile(
        r"\bI\s+(?:am\s+)?prescribing\b",
        re.IGNORECASE,
    ),
    re.compile(
        r"\btake\s+\d+\s*mg\s+of\b",
        re.IGNORECASE,
    ),
]


# ═══════════════════════════════════════════════════════════════════════════════
# NeMo Guardrails Colang/YAML content (embedded for full mode init)
# ═══════════════════════════════════════════════════════════════════════════════

_NEMO_CONFIG_YAML = """\
models:
  - type: main
    engine: anthropic
    model: claude-sonnet-4-20250514

instructions:
  - type: general
    content: |
      You are a clinical decision support system for medical imaging.
      You MUST include evidence citations in every response.
      You MUST NOT make definitive diagnoses.
      You MUST include a clinical disclaimer.
      You MUST NOT reveal patient identifiers.

sample_conversation: |
  user: What does this CT show?
  bot: Based on the available evidence, the CT findings suggest... [Evidence: PMID:12345]
  Note: This is clinical decision support, not a diagnostic determination. All findings should be reviewed by a qualified radiologist.
"""

_NEMO_RAILS_COLANG = """\
define flow check clinical safety
  if user query contains diagnostic request
    bot inform "I provide clinical decision support, not definitive diagnoses. All findings should be reviewed by a qualified radiologist."

define flow add clinical disclaimer
  bot response
  bot append "Clinical Decision Support: This analysis is for informational purposes. Not a substitute for professional medical judgment."

define flow check patient privacy
  if bot response contains PII pattern
    bot sanitize response
    bot warn "Patient identifiable information was detected and removed."
"""


# ═══════════════════════════════════════════════════════════════════════════════
# ClinicalGuardrails
# ═══════════════════════════════════════════════════════════════════════════════


class ClinicalGuardrails:
    """NeMo Guardrails wrapper for clinical imaging AI safety.

    Supports two operating modes:
      - **full**: Uses NeMo Guardrails framework with Colang rail definitions.
      - **lite**: Uses built-in regex/pattern-based checks (no external deps).

    When ``enabled=False``, all checks pass unconditionally.
    """

    def __init__(
        self,
        enabled: bool = True,
        mode: str = "lite",
        config_dir: Optional[str] = None,
    ):
        self.enabled = enabled
        self.mode = mode
        self.config_dir = config_dir
        self._rails = None

        if self.enabled and self.mode == "full":
            self._init_guardrails()

        logger.info(
            f"ClinicalGuardrails initialized: enabled={self.enabled}, "
            f"mode={self.mode}"
        )

    # ───────────────────────────────────────────────────────────────────
    # NeMo Guardrails initialization (full mode)
    # ───────────────────────────────────────────────────────────────────

    def _init_guardrails(self) -> None:
        """Initialize NeMo Guardrails with clinical safety config.

        Tries to import nemoguardrails; if unavailable, logs a warning
        and falls back to lite mode.
        """
        try:
            from nemoguardrails import RailsConfig, LLMRails  # type: ignore

            # Try file-based config first, then embedded content
            if self.config_dir and Path(self.config_dir).is_dir():
                config = RailsConfig.from_path(self.config_dir)
                logger.info(
                    f"NeMo Guardrails loaded from {self.config_dir}"
                )
            else:
                config = RailsConfig.from_content(
                    yaml_content=_NEMO_CONFIG_YAML,
                    colang_content=_NEMO_RAILS_COLANG,
                )
                logger.info("NeMo Guardrails loaded from embedded config")

            self._rails = LLMRails(config)

        except ImportError:
            logger.warning(
                "NeMo Guardrails not installed (pip install nemoguardrails). "
                "Falling back to lite mode with regex-based safety checks."
            )
            self.mode = "lite"

        except Exception as exc:
            logger.error(
                f"NeMo Guardrails initialization failed: {exc}. "
                "Falling back to lite mode."
            )
            self.mode = "lite"

    # ───────────────────────────────────────────────────────────────────
    # Input checking
    # ───────────────────────────────────────────────────────────────────

    def check_input(self, query: str) -> GuardrailResult:
        """Check user query for safety issues.

        Rejects:
          - Non-medical queries (stock prices, recipes, etc.)
          - Queries requesting prescriptions or definitive diagnoses
          - Queries containing patient PII patterns (SSN, MRN, email, phone)

        Args:
            query: The raw user query string.

        Returns:
            GuardrailResult with ``passed=True`` if query is safe.
        """
        if not self.enabled:
            return GuardrailResult(passed=True)

        flags: List[str] = []
        blocked = False
        modified_text = query

        # ── PII detection ──
        pii_found = self._detect_pii(query)
        if pii_found:
            flags.extend([f"pii_detected:{kind}" for kind in pii_found])
            modified_text = self._sanitize_pii_text(modified_text)
            blocked = True

        # ── Non-medical query rejection ──
        for pattern in _NON_MEDICAL_PATTERNS:
            if pattern.search(query):
                flags.append("non_medical_query")
                blocked = True
                break

        # ── Critical safety rejection ──
        for pattern in _INPUT_REJECT_PATTERNS:
            if pattern.search(query):
                flags.append("unsafe_request")
                blocked = True

        passed = not blocked
        return GuardrailResult(
            passed=passed,
            flags=flags,
            modified_text=modified_text if modified_text != query else None,
            blocked=blocked,
        )

    # ───────────────────────────────────────────────────────────────────
    # Output checking
    # ───────────────────────────────────────────────────────────────────

    def check_output(
        self,
        response: str,
        evidence_count: int,
    ) -> GuardrailResult:
        """Check AI-generated response for safety issues.

        Validates:
          - Clinical disclaimer is present (appends if missing)
          - Evidence citations exist (evidence_count > 0)
          - No absolute diagnostic claims ("this IS cancer")
          - No contraindicated recommendation patterns

        Args:
            response: The AI-generated response text.
            evidence_count: Number of evidence citations backing the response.

        Returns:
            GuardrailResult. ``modified_text`` contains the sanitized/
            disclaimer-appended version if changes were made.
        """
        if not self.enabled:
            return GuardrailResult(passed=True)

        flags: List[str] = []
        modified = response

        # ── PII in output ──
        pii_found = self._detect_pii(response)
        if pii_found:
            flags.extend([f"output_pii:{kind}" for kind in pii_found])
            modified = self._sanitize_pii_text(modified)

        # ── Evidence grounding ──
        if evidence_count == 0:
            flags.append("no_evidence_citations")

        # ── Absolute diagnosis claims ──
        for pattern in _ABSOLUTE_DIAGNOSIS_PATTERNS:
            if pattern.search(response):
                flags.append("absolute_diagnosis_claim")
                break

        # ── Contraindicated recommendations ──
        for pattern in _CONTRAINDICATED_PATTERNS:
            if pattern.search(response):
                flags.append("contraindicated_recommendation")
                break

        # ── Disclaimer check ──
        if DISCLAIMER_SENTINEL not in modified:
            flags.append("disclaimer_missing")
            modified = self.add_disclaimer(modified)

        text_changed = modified != response
        passed = not any(
            f in flags
            for f in (
                "absolute_diagnosis_claim",
                "contraindicated_recommendation",
            )
        )

        return GuardrailResult(
            passed=passed,
            flags=flags,
            modified_text=modified if text_changed else None,
            blocked=False,
        )

    # ───────────────────────────────────────────────────────────────────
    # Disclaimer injection
    # ───────────────────────────────────────────────────────────────────

    def add_disclaimer(self, response: str) -> str:
        """Add clinical decision support disclaimer to response.

        If the disclaimer sentinel is already present, the response is
        returned unchanged.

        Args:
            response: AI-generated response text.

        Returns:
            Response with clinical disclaimer appended.
        """
        if DISCLAIMER_SENTINEL in response:
            return response
        return response + CLINICAL_DISCLAIMER

    # ───────────────────────────────────────────────────────────────────
    # PII handling
    # ───────────────────────────────────────────────────────────────────

    def sanitize_pii(self, text: str) -> str:
        """Remove potential PII patterns from text.

        Replaces SSN, MRN, email, and phone patterns with ``[REDACTED]``.

        Args:
            text: Input text that may contain PII.

        Returns:
            Text with PII patterns replaced by ``[REDACTED]``.
        """
        return self._sanitize_pii_text(text)

    def _detect_pii(self, text: str) -> List[str]:
        """Detect PII pattern types present in text.

        Returns:
            List of PII type keys (e.g., ``["ssn", "email"]``).
        """
        found = []
        for kind, pattern in _PII_PATTERNS.items():
            if pattern.search(text):
                found.append(kind)
        return found

    def _sanitize_pii_text(self, text: str) -> str:
        """Replace all PII patterns in text with [REDACTED]."""
        result = text
        for _kind, pattern in _PII_PATTERNS.items():
            result = pattern.sub("[REDACTED]", result)
        return result
