name: Feature Request
description: Suggest a new feature or enhancement
labels: ["enhancement"]
body:
  - type: dropdown
    id: pipeline
    attributes:
      label: Related Component
      options:
        - Genomics Pipeline
        - RAG Chat Pipeline
        - Drug Discovery Pipeline
        - Landing Page
        - CAR-T Intelligence Agent
        - Imaging Intelligence Agent
        - Precision Oncology Agent
        - Orchestrator
        - New Component
        - Other
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: What would you like to see added or changed?
    validations:
      required: true

  - type: textarea
    id: use_case
    attributes:
      label: Use Case
      description: How would this feature be used? What problem does it solve?
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered any workarounds or alternative approaches?
    validations:
      required: false
