"""Report export system for the Clinical Trial Intelligence Agent.

Supports four export formats:
  - export_markdown()      -- structured clinical Markdown report
  - export_json()          -- machine-readable JSON
  - export_pdf()           -- styled PDF via ReportLab Platypus
  - export_fhir_r4()       -- FHIR R4 DiagnosticReport Bundle

Plus specialised report generators:
  - export_trial_match_report()       -- patient-trial matching report
  - export_protocol_analysis()        -- protocol design analysis
  - export_competitive_landscape()    -- competitive intelligence report
  - export_safety_report()            -- safety signal analysis

Author: Adam Jones
Date: March 2026
"""

from __future__ import annotations

import io
import logging
import uuid
from datetime import datetime, timezone
from typing import Any, Dict, List, Union

from .models import (
    CompetitorProfile,
    OverallMatch,
    SafetySignal,
    SeverityLevel,
    WorkflowResult,
)


logger = logging.getLogger(__name__)

VERSION = "1.0.0"


# ===================================================================
# SEVERITY COLOUR MAP
# ===================================================================

SEVERITY_COLORS: Dict[SeverityLevel, str] = {
    SeverityLevel.LOW:            "#2ECC71",  # green
    SeverityLevel.INFORMATIONAL:  "#3498DB",  # blue
    SeverityLevel.MODERATE:       "#F39C12",  # orange
    SeverityLevel.HIGH:           "#E74C3C",  # red
    SeverityLevel.CRITICAL:       "#8E44AD",  # purple
}

# Hex colour shorthand for PDF rendering
_SEV_HEX = SEVERITY_COLORS


# ===================================================================
# REPORT TEMPLATES (Markdown fragments)
# ===================================================================

REPORT_TEMPLATES: Dict[str, str] = {
    "trial_match": (
        "# Patient-Trial Matching Report\n\n"
        "**Patient ID:** {patient_id}  \n"
        "**Report Type:** Trial Matching  \n"
        "**Generated:** {timestamp}  \n"
        "**Agent Version:** {version}\n\n"
        "---\n\n"
    ),
    "protocol_analysis": (
        "# Protocol Design Analysis Report\n\n"
        "**Trial ID:** {trial_id}  \n"
        "**Report Type:** Protocol Analysis  \n"
        "**Generated:** {timestamp}  \n"
        "**Agent Version:** {version}\n\n"
        "---\n\n"
    ),
    "competitive_landscape": (
        "# Competitive Landscape Report\n\n"
        "**Therapeutic Area:** {therapeutic_area}  \n"
        "**Report Type:** Competitive Intelligence  \n"
        "**Generated:** {timestamp}  \n"
        "**Agent Version:** {version}\n\n"
        "---\n\n"
    ),
    "safety": (
        "# Safety Signal Analysis Report\n\n"
        "**Trial ID:** {trial_id}  \n"
        "**Report Type:** Safety Analysis  \n"
        "**Generated:** {timestamp}  \n"
        "**Agent Version:** {version}\n\n"
        "---\n\n"
    ),
    "workflow": (
        "# Clinical Trial Workflow Report\n\n"
        "**Report Type:** {workflow_type} Workflow  \n"
        "**Generated:** {timestamp}  \n"
        "**Agent Version:** {version}\n\n"
        "---\n\n"
    ),
}

_DISCLAIMER = (
    "\n\n---\n\n"
    "> **Disclaimer:** This report is generated by the HCLS AI Factory "
    "Clinical Trial Intelligence Agent for decision-support purposes "
    "only. It does not constitute regulatory or medical advice and must "
    "be reviewed by qualified personnel before any action is taken. "
    "All match scores are estimates based on available data and may "
    "not reflect actual eligibility.\n"
)


# ===================================================================
# HELPER FUNCTIONS
# ===================================================================


def _now_iso() -> str:
    """Return the current UTC timestamp in ISO-8601 format."""
    return datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")


def _now_display() -> str:
    """Return a human-friendly UTC timestamp."""
    return datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")


def _severity_badge(severity: SeverityLevel) -> str:
    """Return a Markdown badge string for a severity level."""
    colour = SEVERITY_COLORS.get(severity, "#95A5A6")
    label = severity.value.replace("_", " ").title()
    return f"![{label}](https://img.shields.io/badge/Severity-{label.replace(' ', '%20')}-{colour[1:]})"


def _severity_indicator(severity: SeverityLevel) -> str:
    """Return a text indicator for severity."""
    mapping = {
        SeverityLevel.LOW: "[LOW]",
        SeverityLevel.INFORMATIONAL: "[INFO]",
        SeverityLevel.MODERATE: "[MODERATE]",
        SeverityLevel.HIGH: "[HIGH]",
        SeverityLevel.CRITICAL: "[CRITICAL]",
    }
    return mapping.get(severity, "[UNKNOWN]")


def _generate_filename(prefix: str, extension: str) -> str:
    """Generate a timestamped filename for export."""
    ts = datetime.now(timezone.utc).strftime("%Y%m%dT%H%M%SZ")
    return f"{prefix}_{ts}.{extension}"


# ===================================================================
# MAIN EXPORTER CLASS
# ===================================================================


class TrialReportExporter:
    """Multi-format report exporter for the Clinical Trial Intelligence Agent.

    Accepts clinical response objects (``WorkflowResult``, ``OverallMatch``,
    ``SafetySignal``, ``CompetitorProfile``) and produces reports in
    Markdown, JSON, PDF, and FHIR R4 formats.

    Usage::

        exporter = TrialReportExporter()
        md = exporter.export_trial_match_report(matches, patient_id="P-001")
        pdf_bytes = exporter.export_pdf(workflow_result)
        fhir = exporter.export_fhir_r4(workflow_result)
    """

    # ── Trial Match Report ────────────────────────────────────────────

    def export_trial_match_report(
        self,
        matches: List[Union[OverallMatch, Dict[str, Any]]],
        patient_id: str = "DEMO",
        format_type: str = "markdown",
    ) -> Union[str, dict]:
        """Export a patient-trial matching report.

        Args:
            matches: List of ``OverallMatch`` objects or dicts.
            patient_id: Patient identifier.
            format_type: Output format (``"markdown"`` or ``"json"``).

        Returns:
            Markdown string or JSON dict depending on format_type.
        """
        timestamp = _now_display()
        header = REPORT_TEMPLATES["trial_match"].format(
            patient_id=patient_id,
            timestamp=timestamp,
            version=VERSION,
        )

        if format_type == "json":
            return self._trial_match_json(matches, patient_id)

        lines: List[str] = [header]
        lines.append(f"## Match Results ({len(matches)} trials)\n")

        for i, match in enumerate(matches, 1):
            if isinstance(match, OverallMatch):
                trial_id = match.trial_id
                title = match.trial_title
                phase = match.phase.value
                score = match.overall_score
                confidence = match.confidence
                inc_met = match.inclusion_met
                inc_total = match.inclusion_total
                exc_clear = match.exclusion_clear
                exc_total = match.exclusion_total
            elif isinstance(match, dict):
                trial_id = match.get("trial_id", "")
                title = match.get("trial_title", "")
                phase = match.get("phase", "")
                score = match.get("overall_score", 0.0)
                confidence = match.get("confidence", 0.0)
                inc_met = match.get("inclusion_met", 0)
                inc_total = match.get("inclusion_total", 0)
                exc_clear = match.get("exclusion_clear", 0)
                exc_total = match.get("exclusion_total", 0)
            else:
                continue

            lines.append(f"### {i}. {title}")
            lines.append(f"- **Trial ID:** {trial_id}")
            lines.append(f"- **Phase:** {phase}")
            lines.append(f"- **Overall Score:** {score:.0%}")
            lines.append(f"- **Confidence:** {confidence:.0%}")
            lines.append(f"- **Inclusion Criteria Met:** {inc_met}/{inc_total}")
            lines.append(f"- **Exclusion Criteria Clear:** {exc_clear}/{exc_total}")
            lines.append("")

        lines.append(_DISCLAIMER)
        return "\n".join(lines)

    def _trial_match_json(
        self,
        matches: List[Union[OverallMatch, Dict[str, Any]]],
        patient_id: str,
    ) -> dict:
        """Serialize trial matches as JSON."""
        match_data = []
        for match in matches:
            if isinstance(match, OverallMatch):
                match_data.append(match.model_dump())
            elif isinstance(match, dict):
                match_data.append(match)

        return {
            "report_type": "trial_match",
            "patient_id": patient_id,
            "generated_at": _now_iso(),
            "version": VERSION,
            "match_count": len(match_data),
            "matches": match_data,
        }

    # ── Protocol Analysis Report ──────────────────────────────────────

    def export_protocol_analysis(
        self,
        analysis: Union[WorkflowResult, Dict[str, Any]],
        trial_id: str = "DEMO",
    ) -> str:
        """Export a protocol design analysis as Markdown.

        Args:
            analysis: ``WorkflowResult`` or dict with analysis data.
            trial_id: Trial NCT identifier.

        Returns:
            Markdown report string.
        """
        timestamp = _now_display()
        header = REPORT_TEMPLATES["protocol_analysis"].format(
            trial_id=trial_id,
            timestamp=timestamp,
            version=VERSION,
        )

        lines: List[str] = [header]

        if isinstance(analysis, WorkflowResult):
            severity = analysis.severity
            findings = analysis.findings
            recommendations = analysis.recommendations
            confidence = analysis.confidence
            guideline_refs = analysis.guideline_references
        elif isinstance(analysis, dict):
            severity = SeverityLevel(analysis.get("severity", "informational"))
            findings = analysis.get("findings", [])
            recommendations = analysis.get("recommendations", [])
            confidence = analysis.get("confidence", 0.0)
            guideline_refs = analysis.get("guideline_references", [])
        else:
            severity = SeverityLevel.INFORMATIONAL
            findings = []
            recommendations = []
            confidence = 0.0
            guideline_refs = []

        lines.append(f"**Severity:** {_severity_badge(severity)}")
        lines.append(f"**Confidence:** {confidence:.0%}\n")

        if findings:
            lines.append("## Findings\n")
            for j, finding in enumerate(findings, 1):
                lines.append(f"{j}. {finding}")
            lines.append("")

        if recommendations:
            lines.append("## Recommendations\n")
            for j, rec in enumerate(recommendations, 1):
                lines.append(f"{j}. {rec}")
            lines.append("")

        if guideline_refs:
            lines.append("## Regulatory References\n")
            for ref in guideline_refs:
                lines.append(f"> {ref}")
            lines.append("")

        lines.append(_DISCLAIMER)
        return "\n".join(lines)

    # ── Competitive Landscape Report ──────────────────────────────────

    def export_competitive_landscape(
        self,
        competitors: List[Union[CompetitorProfile, Dict[str, Any]]],
        therapeutic_area: str = "General",
    ) -> str:
        """Export a competitive landscape analysis as Markdown.

        Args:
            competitors: List of ``CompetitorProfile`` or dict.
            therapeutic_area: Target therapeutic area.

        Returns:
            Markdown report string.
        """
        timestamp = _now_display()
        header = REPORT_TEMPLATES["competitive_landscape"].format(
            therapeutic_area=therapeutic_area,
            timestamp=timestamp,
            version=VERSION,
        )

        lines: List[str] = [header]
        lines.append(f"## Competitor Landscape ({len(competitors)} trials)\n")

        # Summary table
        lines.append("| Trial ID | Sponsor | Phase | Indication | Threat |")
        lines.append("|----------|---------|-------|------------|--------|")

        for comp in competitors:
            if isinstance(comp, CompetitorProfile):
                tid = comp.trial_id
                sponsor = comp.sponsor
                phase = comp.phase.value
                indication = comp.indication
                threat = comp.threat_level.value.title()
            elif isinstance(comp, dict):
                tid = comp.get("trial_id", "")
                sponsor = comp.get("sponsor", "")
                phase = comp.get("phase", "")
                indication = comp.get("indication", "")
                threat = comp.get("threat_level", "informational").title()
            else:
                continue

            lines.append(f"| {tid} | {sponsor} | {phase} | {indication} | {threat} |")

        lines.append("")

        # Detail sections
        for i, comp in enumerate(competitors, 1):
            if isinstance(comp, CompetitorProfile):
                lines.append(f"### {i}. {comp.trial_id}: {comp.indication}")
                lines.append(f"- **Sponsor:** {comp.sponsor}")
                lines.append(f"- **Phase:** {comp.phase.value}")
                lines.append(f"- **Mechanism:** {comp.mechanism}")
                lines.append(f"- **Enrollment Progress:** {comp.enrollment_progress:.0%}")
                if comp.estimated_completion:
                    lines.append(f"- **Est. Completion:** {comp.estimated_completion}")
                lines.append(f"- **Threat Level:** {_severity_indicator(comp.threat_level)}")
                lines.append("")

        lines.append(_DISCLAIMER)
        return "\n".join(lines)

    # ── Safety Report ─────────────────────────────────────────────────

    def export_safety_report(
        self,
        signals: List[Union[SafetySignal, Dict[str, Any]]],
        trial_id: str = "DEMO",
    ) -> str:
        """Export a safety signal analysis report as Markdown.

        Args:
            signals: List of ``SafetySignal`` objects or dicts.
            trial_id: Trial NCT identifier.

        Returns:
            Markdown report string.
        """
        timestamp = _now_display()
        header = REPORT_TEMPLATES["safety"].format(
            trial_id=trial_id,
            timestamp=timestamp,
            version=VERSION,
        )

        lines: List[str] = [header]
        lines.append(f"## Safety Signals ({len(signals)} detected)\n")

        # Summary table
        lines.append("| Event Type | Severity | Frequency | PRR | Causality |")
        lines.append("|------------|----------|-----------|-----|-----------|")

        for signal in signals:
            if isinstance(signal, SafetySignal):
                etype = signal.event_type
                severity = signal.severity.value.title()
                freq = f"{signal.frequency:.1%}"
                prr = f"{signal.prr:.2f}" if signal.prr is not None else "N/A"
                causality = signal.causality_assessment or "Not assessed"
            elif isinstance(signal, dict):
                etype = signal.get("event_type", "")
                severity = signal.get("severity", "").title()
                freq_val = signal.get("frequency", 0.0)
                freq = f"{freq_val:.1%}" if isinstance(freq_val, (int, float)) else str(freq_val)
                prr = str(signal.get("prr", "N/A"))
                causality = signal.get("causality_assessment", "Not assessed")
            else:
                continue

            lines.append(f"| {etype} | {severity} | {freq} | {prr} | {causality} |")

        lines.append("")

        # Critical signal alerts
        critical_signals = [
            s for s in signals
            if (isinstance(s, SafetySignal) and s.severity in (SeverityLevel.CRITICAL, SeverityLevel.HIGH))
            or (isinstance(s, dict) and s.get("severity", "") in ("critical", "high"))
        ]

        if critical_signals:
            lines.append("## Critical / High Severity Alerts\n")
            for signal in critical_signals:
                if isinstance(signal, SafetySignal):
                    lines.append(f"- **{signal.event_type}** -- {_severity_indicator(signal.severity)}")
                    if signal.causality_assessment:
                        lines.append(f"  Causality: {signal.causality_assessment}")
                lines.append("")

        lines.append(_DISCLAIMER)
        return "\n".join(lines)

    # ── Generic Markdown Export ────────────────────────────────────────

    def export_markdown(
        self,
        response: Union[WorkflowResult, Dict[str, Any]],
        report_type: str = "workflow",
    ) -> str:
        """Export a generic workflow response as Markdown.

        Args:
            response: A ``WorkflowResult`` or dict.
            report_type: Template key from REPORT_TEMPLATES.

        Returns:
            Markdown report string.
        """
        timestamp = _now_display()
        template_key = report_type if report_type in REPORT_TEMPLATES else "workflow"
        template = REPORT_TEMPLATES[template_key]

        header_vars: Dict[str, str] = {
            "timestamp": timestamp,
            "version": VERSION,
            "patient_id": "DEMO",
            "trial_id": "DEMO",
            "therapeutic_area": "General",
        }

        if isinstance(response, WorkflowResult):
            header_vars["workflow_type"] = response.workflow_type.value.replace(
                "_", " "
            ).title()
        else:
            header_vars["workflow_type"] = report_type.replace("_", " ").title()

        lines: List[str] = [template.format(**header_vars)]

        if isinstance(response, WorkflowResult):
            findings = response.findings
            recommendations = response.recommendations
            confidence = response.confidence
        elif isinstance(response, dict):
            findings = response.get("findings", [])
            recommendations = response.get("recommendations", [])
            confidence = response.get("confidence", 0.0)
        else:
            findings = []
            recommendations = []
            confidence = 0.0

        lines.append(f"**Confidence:** {confidence:.0%}\n")

        if findings:
            lines.append("## Findings\n")
            for j, finding in enumerate(findings, 1):
                lines.append(f"{j}. {finding}")
            lines.append("")

        if recommendations:
            lines.append("## Recommendations\n")
            for j, rec in enumerate(recommendations, 1):
                lines.append(f"{j}. {rec}")
            lines.append("")

        lines.append(_DISCLAIMER)
        return "\n".join(lines)

    # ── JSON Export ────────────────────────────────────────────────────

    def export_json(
        self,
        response: Union[WorkflowResult, Dict[str, Any]],
    ) -> dict:
        """Export a clinical response as structured JSON.

        Args:
            response: A ``WorkflowResult`` or dict.

        Returns:
            Serialized JSON dict.
        """
        if isinstance(response, WorkflowResult):
            data = response.model_dump()
        elif isinstance(response, dict):
            data = response
        else:
            data = {"raw": str(response)}

        return {
            "report_type": "clinical_trial_workflow",
            "generated_at": _now_iso(),
            "version": VERSION,
            "data": data,
        }

    # ── PDF Export ─────────────────────────────────────────────────────

    def export_pdf(
        self,
        response: Union[WorkflowResult, Dict[str, Any]],
        title: str = "Clinical Trial Intelligence Report",
    ) -> bytes:
        """Export a clinical response as a PDF document.

        Requires ``reportlab`` to be installed. Returns empty bytes if
        the dependency is not available.

        Args:
            response: A ``WorkflowResult`` or dict.
            title: Report title.

        Returns:
            PDF file bytes.
        """
        try:
            from reportlab.lib.pagesizes import letter
            from reportlab.platypus import (
                SimpleDocTemplate,
                Paragraph,
                Spacer,
            )
            from reportlab.lib.styles import getSampleStyleSheet
        except ImportError:
            logger.warning(
                "reportlab not installed -- PDF export returning empty bytes"
            )
            return b""

        buffer = io.BytesIO()
        doc = SimpleDocTemplate(buffer, pagesize=letter)
        styles = getSampleStyleSheet()
        story: List[Any] = []

        # Title
        story.append(Paragraph(title, styles["Title"]))
        story.append(Spacer(1, 12))

        # Timestamp
        story.append(
            Paragraph(
                f"Generated: {_now_display()} | Version: {VERSION}",
                styles["Normal"],
            )
        )
        story.append(Spacer(1, 12))

        # Content
        if isinstance(response, WorkflowResult):
            for finding in response.findings:
                story.append(Paragraph(f"Finding: {finding}", styles["Normal"]))
                story.append(Spacer(1, 6))
            for rec in response.recommendations:
                story.append(Paragraph(f"Recommendation: {rec}", styles["Normal"]))
                story.append(Spacer(1, 6))
        elif isinstance(response, dict):
            for finding in response.get("findings", []):
                story.append(Paragraph(f"Finding: {finding}", styles["Normal"]))
                story.append(Spacer(1, 6))

        # Disclaimer
        story.append(Spacer(1, 24))
        story.append(
            Paragraph(
                "Disclaimer: This report is for decision-support only.",
                styles["Italic"],
            )
        )

        doc.build(story)
        return buffer.getvalue()

    # ── FHIR R4 Export ─────────────────────────────────────────────────

    def export_fhir_r4(
        self,
        response: Union[WorkflowResult, Dict[str, Any]],
        patient_id: str = "DEMO",
    ) -> dict:
        """Export as a FHIR R4 DiagnosticReport Bundle.

        Args:
            response: A ``WorkflowResult`` or dict.
            patient_id: Patient reference.

        Returns:
            FHIR R4 Bundle dictionary.
        """
        report_id = str(uuid.uuid4())
        timestamp = _now_iso()

        if isinstance(response, WorkflowResult):
            conclusion = "; ".join(response.findings[:3]) if response.findings else ""
            category_code = response.workflow_type.value
        elif isinstance(response, dict):
            findings = response.get("findings", [])
            conclusion = "; ".join(findings[:3]) if findings else ""
            category_code = response.get("workflow_type", "general")
        else:
            conclusion = str(response)
            category_code = "general"

        diagnostic_report = {
            "resourceType": "DiagnosticReport",
            "id": report_id,
            "status": "final",
            "category": [
                {
                    "coding": [
                        {
                            "system": "http://hcls-ai-factory.dev/trial-agent",
                            "code": category_code,
                            "display": category_code.replace("_", " ").title(),
                        }
                    ]
                }
            ],
            "code": {
                "coding": [
                    {
                        "system": "http://loinc.org",
                        "code": "75321-0",
                        "display": "Clinical trial screening",
                    }
                ]
            },
            "subject": {"reference": f"Patient/{patient_id}"},
            "effectiveDateTime": timestamp,
            "issued": timestamp,
            "conclusion": conclusion,
        }

        bundle = {
            "resourceType": "Bundle",
            "type": "document",
            "timestamp": timestamp,
            "entry": [
                {
                    "resource": diagnostic_report,
                    "fullUrl": f"urn:uuid:{report_id}",
                }
            ],
            "meta": {
                "profile": [
                    "http://hcls-ai-factory.dev/fhir/trial-intelligence-report"
                ],
                "tag": [
                    {
                        "system": "http://hcls-ai-factory.dev/version",
                        "code": VERSION,
                    }
                ],
            },
        }

        return bundle
