"""Report export system for the Cardiology Intelligence Agent.

Supports four export formats:
  - export_markdown()      -- structured clinical Markdown report
  - export_json()          -- machine-readable JSON
  - export_pdf()           -- styled PDF via ReportLab Platypus
  - export_fhir_r4()       -- FHIR R4 DiagnosticReport Bundle

Plus specialised report generators:
  - export_risk_score_report()  -- dedicated multi-score risk report
  - export_gdmt_report()        -- GDMT optimisation summary
  - export_workflow_report()    -- clinical workflow results

Author: Adam Jones
Date: March 2026
"""

from __future__ import annotations

import io
import json
import logging
import uuid
from datetime import datetime, timezone
from typing import Any, Dict, List, Optional, Union

from .models import (
    CrossModalTrigger,
    EvidenceLevel,
    GDMTRecommendation,
    GuidelineClass,
    RiskScoreResult,
    SeverityLevel,
    WorkflowResult,
)


logger = logging.getLogger(__name__)

VERSION = "1.0.0"


# ═══════════════════════════════════════════════════════════════════════
# SEVERITY COLOUR MAP
# ═══════════════════════════════════════════════════════════════════════

SEVERITY_COLORS: Dict[SeverityLevel, str] = {
    SeverityLevel.LOW:          "#2ECC71",  # green
    SeverityLevel.BORDERLINE:   "#F1C40F",  # yellow
    SeverityLevel.INTERMEDIATE: "#F39C12",  # orange
    SeverityLevel.MODERATE:     "#E67E22",  # dark orange
    SeverityLevel.HIGH:         "#E74C3C",  # red
    SeverityLevel.VERY_HIGH:    "#C0392B",  # dark red
    SeverityLevel.CRITICAL:     "#8E44AD",  # purple
}

# Hex colour shorthand for PDF rendering
_SEV_HEX = SEVERITY_COLORS


# ═══════════════════════════════════════════════════════════════════════
# REPORT TEMPLATES (Markdown fragments)
# ═══════════════════════════════════════════════════════════════════════

REPORT_TEMPLATES: Dict[str, str] = {
    "consultation": (
        "# Cardiology Intelligence Report\n\n"
        "**Patient ID:** {patient_id}  \n"
        "**Report Type:** Clinical Consultation  \n"
        "**Generated:** {timestamp}  \n"
        "**Agent Version:** {version}\n\n"
        "---\n\n"
    ),
    "risk_assessment": (
        "# Cardiovascular Risk Assessment Report\n\n"
        "**Patient ID:** {patient_id}  \n"
        "**Report Type:** Risk Assessment  \n"
        "**Generated:** {timestamp}  \n"
        "**Agent Version:** {version}\n\n"
        "---\n\n"
    ),
    "gdmt_optimization": (
        "# GDMT Optimisation Report\n\n"
        "**Patient ID:** {patient_id}  \n"
        "**Report Type:** Guideline-Directed Medical Therapy  \n"
        "**Generated:** {timestamp}  \n"
        "**Agent Version:** {version}\n\n"
        "---\n\n"
    ),
    "workflow": (
        "# Clinical Workflow Report\n\n"
        "**Patient ID:** {patient_id}  \n"
        "**Report Type:** {workflow_type} Workflow  \n"
        "**Generated:** {timestamp}  \n"
        "**Agent Version:** {version}\n\n"
        "---\n\n"
    ),
}

_DISCLAIMER = (
    "\n\n---\n\n"
    "> **Disclaimer:** This report is generated by the HCLS AI Factory "
    "Cardiology Intelligence Agent for clinical decision-support purposes "
    "only. It does not constitute medical advice and must be reviewed by a "
    "qualified healthcare professional before any clinical action is taken. "
    "All risk scores are estimates based on population-level data and may "
    "not reflect individual patient risk.\n"
)


# ═══════════════════════════════════════════════════════════════════════
# HELPER FUNCTIONS
# ═══════════════════════════════════════════════════════════════════════


def _now_iso() -> str:
    """Return the current UTC timestamp in ISO-8601 format."""
    return datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")


def _now_display() -> str:
    """Return a human-friendly UTC timestamp."""
    return datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")


def _severity_badge(severity: SeverityLevel) -> str:
    """Return a Markdown badge string for a severity level."""
    colour = SEVERITY_COLORS.get(severity, "#95A5A6")
    label = severity.value.replace("_", " ").title()
    return f"![{label}](https://img.shields.io/badge/Severity-{label.replace(' ', '%20')}-{colour[1:]})"


def _severity_emoji(severity: SeverityLevel) -> str:
    """Return a text indicator for severity (no actual emoji, just text markers)."""
    mapping = {
        SeverityLevel.LOW: "[LOW]",
        SeverityLevel.BORDERLINE: "[BORDERLINE]",
        SeverityLevel.INTERMEDIATE: "[INTERMEDIATE]",
        SeverityLevel.MODERATE: "[MODERATE]",
        SeverityLevel.HIGH: "[HIGH]",
        SeverityLevel.VERY_HIGH: "[VERY HIGH]",
        SeverityLevel.CRITICAL: "[CRITICAL]",
    }
    return mapping.get(severity, "[UNKNOWN]")


def format_risk_score_table(scores: List[RiskScoreResult]) -> str:
    """Format a list of risk scores as a Markdown table.

    Args:
        scores: List of ``RiskScoreResult`` instances.

    Returns:
        Markdown table string with columns for score type, value,
        category, severity, and interpretation.
    """
    if not scores:
        return "*No risk scores calculated.*\n"

    lines = [
        "| Score | Value | Risk Category | Severity | Interpretation |",
        "|-------|-------|---------------|----------|----------------|",
    ]
    for s in scores:
        stype = s.score_type.value.upper().replace("_", "-")
        severity_label = s.severity.value.replace("_", " ").title()
        interp = s.interpretation[:80] if s.interpretation else ""
        lines.append(
            f"| {stype} | {s.score_value:.1f} | {s.risk_category} "
            f"| {severity_label} | {interp} |"
        )
    return "\n".join(lines) + "\n"


def format_guideline_citation(guideline: str) -> str:
    """Format a guideline reference as a Markdown citation block.

    Args:
        guideline: Guideline reference string (e.g. ``"ACC/AHA 2022 ..."``).

    Returns:
        Markdown blockquote citation.
    """
    if not guideline:
        return ""
    return f"> **Guideline:** {guideline}\n"


def _format_class_loe(
    guideline_class: Optional[GuidelineClass],
    evidence_level: Optional[EvidenceLevel],
) -> str:
    """Format guideline Class and Level of Evidence as a compact string."""
    parts = []
    if guideline_class:
        parts.append(f"Class {guideline_class.value}")
    if evidence_level:
        parts.append(f"LOE {evidence_level.value}")
    return " / ".join(parts) if parts else ""


def _format_cross_modal_trigger(trigger: CrossModalTrigger) -> str:
    """Format a single cross-modal trigger as Markdown."""
    lines = [
        f"- **{trigger.trigger_type.title()} Trigger:** {trigger.finding}",
    ]
    if trigger.conditions:
        lines.append(f"  - Suspected conditions: {', '.join(trigger.conditions)}")
    if trigger.gene_panel:
        lines.append(f"  - Recommended gene panel: {', '.join(trigger.gene_panel)}")
    if trigger.criteria_met:
        lines.append(f"  - Criteria met: {trigger.criteria_met}")
    if trigger.guideline:
        lines.append(f"  - Guideline: {trigger.guideline}")
    urgency = trigger.urgency.value.replace("_", " ").title()
    lines.append(f"  - Urgency: {urgency}")
    return "\n".join(lines)


def _generate_filename(prefix: str, extension: str) -> str:
    """Generate a timestamped filename for export."""
    ts = datetime.now(timezone.utc).strftime("%Y%m%dT%H%M%SZ")
    return f"{prefix}_{ts}.{extension}"


# ═══════════════════════════════════════════════════════════════════════
# MAIN EXPORTER CLASS
# ═══════════════════════════════════════════════════════════════════════


class CardioReportExporter:
    """Multi-format report exporter for the Cardiology Intelligence Agent.

    Accepts clinical response objects (``WorkflowResult``,
    ``RiskScoreResult``, ``GDMTRecommendation``) and produces reports in
    Markdown, JSON, PDF, and FHIR R4 formats.

    Usage::

        exporter = CardioReportExporter()
        md = exporter.export_markdown(workflow_result, patient_id="P-001")
        pdf_bytes = exporter.export_pdf(workflow_result, patient_id="P-001")
        fhir = exporter.export_fhir_r4(workflow_result, patient_id="P-001")
    """

    # ── Markdown Export ────────────────────────────────────────────────

    def export_markdown(
        self,
        response: Union[WorkflowResult, Dict[str, Any]],
        patient_id: str = "DEMO",
        report_type: str = "consultation",
    ) -> str:
        """Export a clinical response as a structured Markdown report.

        Args:
            response: A ``WorkflowResult`` or dict containing clinical data.
            patient_id: Patient identifier for the report header.
            report_type: One of ``consultation``, ``risk_assessment``,
                ``gdmt_optimization``, or ``workflow``.

        Returns:
            Complete Markdown report as a string.
        """
        timestamp = _now_display()
        template_key = report_type if report_type in REPORT_TEMPLATES else "consultation"
        template = REPORT_TEMPLATES[template_key]

        # Build header
        header_vars: Dict[str, str] = {
            "patient_id": patient_id,
            "timestamp": timestamp,
            "version": VERSION,
        }
        if isinstance(response, WorkflowResult):
            header_vars["workflow_type"] = response.workflow_type.value.replace(
                "_", " "
            ).title()
        else:
            header_vars["workflow_type"] = report_type.replace("_", " ").title()

        lines: List[str] = [template.format(**header_vars)]

        # Extract fields depending on response type
        if isinstance(response, WorkflowResult):
            severity = response.severity
            summary = response.summary
            findings = response.findings
            recommendations = response.recommendations
            risk_scores = response.risk_scores
            cross_modal = response.cross_modal_triggers
            guideline_refs = response.guideline_references
            confidence = response.confidence
        elif isinstance(response, dict):
            severity = SeverityLevel(response.get("severity", "low"))
            summary = response.get("summary", "")
            findings = response.get("findings", [])
            recommendations = response.get("recommendations", [])
            risk_scores = response.get("risk_scores", [])
            cross_modal = response.get("cross_modal_triggers", [])
            guideline_refs = response.get("guideline_references", [])
            confidence = response.get("confidence", 1.0)
        else:
            severity = SeverityLevel.LOW
            summary = str(response)
            findings = []
            recommendations = []
            risk_scores = []
            cross_modal = []
            guideline_refs = []
            confidence = 1.0

        # Severity badge
        lines.append(f"**Severity:** {_severity_badge(severity)}\n")
        lines.append(f"**Confidence:** {confidence:.0%}\n\n")

        # Clinical summary
        lines.append("## Clinical Summary\n")
        if summary:
            lines.append(f"{summary}\n\n")
        else:
            lines.append("*No summary available.*\n\n")

        # Findings
        if findings:
            lines.append("## Findings\n")
            for i, finding in enumerate(findings, 1):
                lines.append(f"{i}. {finding}")
            lines.append("\n")

        # Risk scores
        if risk_scores:
            lines.append("## Risk Scores\n")
            if isinstance(risk_scores[0], RiskScoreResult):
                lines.append(format_risk_score_table(risk_scores))
            else:
                # Assume list of dicts
                parsed = []
                for rs in risk_scores:
                    if isinstance(rs, dict):
                        try:
                            parsed.append(RiskScoreResult(**rs))
                        except Exception as exc:
                            logger.warning("Failed to process risk score dict: %s", exc)
                    else:
                        parsed.append(rs)
                lines.append(format_risk_score_table(parsed))

            # Detailed interpretation for each score
            score_list = risk_scores if isinstance(risk_scores[0], RiskScoreResult) else parsed
            for rs in score_list:
                if not isinstance(rs, RiskScoreResult):
                    continue
                stype = rs.score_type.value.upper().replace("_", "-")
                lines.append(f"### {stype} Score Detail\n")
                lines.append(f"- **Value:** {rs.score_value:.1f}")
                lines.append(f"- **Category:** {rs.risk_category}")
                lines.append(
                    f"- **Severity:** {rs.severity.value.replace('_', ' ').title()}"
                )
                if rs.interpretation:
                    lines.append(f"- **Interpretation:** {rs.interpretation}")
                class_loe = _format_class_loe(rs.guideline_class, rs.evidence_level)
                if class_loe:
                    lines.append(f"- **Recommendation:** {class_loe}")
                if rs.guideline_reference:
                    lines.append(f"- **Reference:** {rs.guideline_reference}")
                if rs.recommendations:
                    lines.append("\n**Recommendations:**\n")
                    for rec in rs.recommendations:
                        lines.append(f"  - {rec}")
                if rs.component_breakdown:
                    lines.append("\n**Component Breakdown:**\n")
                    for comp, val in rs.component_breakdown.items():
                        lines.append(f"  - {comp}: {val}")
                lines.append("\n")

        # Guideline recommendations
        if recommendations:
            lines.append("## Guideline Recommendations\n")
            for i, rec in enumerate(recommendations, 1):
                lines.append(f"{i}. {rec}")
            lines.append("\n")

        # Guideline references
        if guideline_refs:
            lines.append("## Guideline References\n")
            for ref in guideline_refs:
                lines.append(format_guideline_citation(ref))
            lines.append("\n")

        # Cross-modal triggers
        if cross_modal:
            lines.append("## Cross-Modal Genomic Triggers\n")
            lines.append(
                "The following clinical findings triggered recommendations "
                "for genomic analysis:\n\n"
            )
            for trigger in cross_modal:
                if isinstance(trigger, CrossModalTrigger):
                    lines.append(_format_cross_modal_trigger(trigger))
                elif isinstance(trigger, dict):
                    try:
                        lines.append(
                            _format_cross_modal_trigger(CrossModalTrigger(**trigger))
                        )
                    except Exception:
                        lines.append(f"- {trigger}")
                lines.append("")
            lines.append("\n")

        # Disclaimer
        lines.append(_DISCLAIMER)

        return "\n".join(lines)

    # ── JSON Export ────────────────────────────────────────────────────

    def export_json(
        self,
        response: Union[WorkflowResult, Dict[str, Any]],
        patient_id: str = "DEMO",
    ) -> dict:
        """Export a clinical response as structured JSON.

        Args:
            response: A ``WorkflowResult`` or dict containing clinical data.
            patient_id: Patient identifier.

        Returns:
            Dict suitable for ``json.dumps()`` serialization.
        """
        timestamp = _now_iso()

        if isinstance(response, WorkflowResult):
            data = response.model_dump()
        elif isinstance(response, dict):
            data = dict(response)
        else:
            data = {"raw": str(response)}

        return {
            "report_type": "cardio_intelligence_report",
            "version": VERSION,
            "generated_at": timestamp,
            "patient_id": patient_id,
            "agent": "cardiology_intelligence_agent",
            "data": data,
        }

    # ── PDF Export ─────────────────────────────────────────────────────

    def export_pdf(
        self,
        response: Union[WorkflowResult, Dict[str, Any]],
        patient_id: str = "DEMO",
        output_path: Optional[str] = None,
    ) -> bytes:
        """Export a clinical response as a styled PDF document.

        Uses ReportLab Platypus for a professional layout with HCLS AI
        Factory branding and colour-coded severity sections.

        Args:
            response: A ``WorkflowResult`` or dict containing clinical data.
            patient_id: Patient identifier.
            output_path: Optional file path to write the PDF to disk.

        Returns:
            PDF content as bytes.
        """
        try:
            from reportlab.lib import colors as rl_colors
            from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_RIGHT
            from reportlab.lib.pagesizes import letter
            from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
            from reportlab.lib.units import inch
            from reportlab.platypus import (
                BaseDocTemplate,
                Frame,
                NextPageTemplate,
                PageBreak,
                PageTemplate,
                Paragraph,
                SimpleDocTemplate,
                Spacer,
                Table,
                TableStyle,
            )
        except ImportError:
            raise ImportError(
                "reportlab is required for PDF export. "
                "Install with: pip install reportlab>=4.0"
            )

        buf = io.BytesIO()
        doc = SimpleDocTemplate(
            buf,
            pagesize=letter,
            topMargin=0.75 * inch,
            bottomMargin=0.75 * inch,
            leftMargin=0.75 * inch,
            rightMargin=0.75 * inch,
        )

        styles = getSampleStyleSheet()
        story: List[Any] = []

        # Custom styles
        title_style = ParagraphStyle(
            "CardioTitle",
            parent=styles["Title"],
            fontSize=18,
            leading=22,
            textColor=rl_colors.HexColor("#1A5276"),
            spaceAfter=6,
        )
        heading_style = ParagraphStyle(
            "CardioHeading",
            parent=styles["Heading2"],
            fontSize=13,
            leading=16,
            textColor=rl_colors.HexColor("#2C3E50"),
            spaceBefore=12,
            spaceAfter=6,
        )
        body_style = ParagraphStyle(
            "CardioBody",
            parent=styles["Normal"],
            fontSize=10,
            leading=13,
            spaceBefore=3,
            spaceAfter=3,
        )
        meta_style = ParagraphStyle(
            "CardioMeta",
            parent=styles["Normal"],
            fontSize=9,
            leading=11,
            textColor=rl_colors.HexColor("#7F8C8D"),
        )
        disclaimer_style = ParagraphStyle(
            "CardioDisclaimer",
            parent=styles["Normal"],
            fontSize=7,
            leading=9,
            textColor=rl_colors.HexColor("#95A5A6"),
            spaceBefore=18,
        )

        # Extract data
        if isinstance(response, WorkflowResult):
            severity = response.severity
            summary = response.summary
            findings = response.findings
            recommendations = response.recommendations
            risk_scores = response.risk_scores
            workflow_type_str = response.workflow_type.value.replace("_", " ").title()
        elif isinstance(response, dict):
            severity = SeverityLevel(response.get("severity", "low"))
            summary = response.get("summary", "")
            findings = response.get("findings", [])
            recommendations = response.get("recommendations", [])
            risk_scores = response.get("risk_scores", [])
            workflow_type_str = response.get("workflow_type", "General").replace(
                "_", " "
            ).title()
        else:
            severity = SeverityLevel.LOW
            summary = str(response)
            findings = []
            recommendations = []
            risk_scores = []
            workflow_type_str = "General"

        timestamp = _now_display()
        sev_colour = rl_colors.HexColor(
            SEVERITY_COLORS.get(severity, "#95A5A6")
        )

        # Title
        story.append(Paragraph("HCLS AI Factory", meta_style))
        story.append(
            Paragraph("Cardiology Intelligence Report", title_style)
        )
        story.append(Spacer(1, 6))

        # Metadata table
        meta_data = [
            ["Patient ID:", patient_id, "Report Date:", timestamp],
            [
                "Workflow:",
                workflow_type_str,
                "Severity:",
                severity.value.replace("_", " ").title(),
            ],
            ["Agent Version:", VERSION, "", ""],
        ]
        meta_table = Table(meta_data, colWidths=[1.2 * inch, 2.0 * inch, 1.2 * inch, 2.0 * inch])
        meta_table.setStyle(
            TableStyle(
                [
                    ("FONTNAME", (0, 0), (-1, -1), "Helvetica"),
                    ("FONTSIZE", (0, 0), (-1, -1), 9),
                    ("FONTNAME", (0, 0), (0, -1), "Helvetica-Bold"),
                    ("FONTNAME", (2, 0), (2, -1), "Helvetica-Bold"),
                    ("TEXTCOLOR", (0, 0), (0, -1), rl_colors.HexColor("#2C3E50")),
                    ("TEXTCOLOR", (2, 0), (2, -1), rl_colors.HexColor("#2C3E50")),
                    ("BOTTOMPADDING", (0, 0), (-1, -1), 3),
                    ("TOPPADDING", (0, 0), (-1, -1), 3),
                ]
            )
        )
        story.append(meta_table)
        story.append(Spacer(1, 12))

        # Severity bar
        sev_bar_data = [[
            Paragraph(
                f"<b>Clinical Severity: "
                f"{severity.value.replace('_', ' ').upper()}</b>",
                ParagraphStyle(
                    "SevBar", parent=body_style, textColor=rl_colors.white,
                    fontSize=10, alignment=TA_CENTER,
                ),
            )
        ]]
        sev_bar = Table(sev_bar_data, colWidths=[6.5 * inch])
        sev_bar.setStyle(
            TableStyle(
                [
                    ("BACKGROUND", (0, 0), (-1, -1), sev_colour),
                    ("ALIGN", (0, 0), (-1, -1), "CENTER"),
                    ("TOPPADDING", (0, 0), (-1, -1), 6),
                    ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
                    ("ROUNDEDCORNERS", [4, 4, 4, 4]),
                ]
            )
        )
        story.append(sev_bar)
        story.append(Spacer(1, 12))

        # Clinical Summary
        story.append(Paragraph("Clinical Summary", heading_style))
        if summary:
            story.append(Paragraph(summary, body_style))
        else:
            story.append(
                Paragraph("<i>No summary available.</i>", body_style)
            )

        # Findings
        if findings:
            story.append(Paragraph("Findings", heading_style))
            for i, finding in enumerate(findings, 1):
                story.append(
                    Paragraph(f"{i}. {finding}", body_style)
                )

        # Risk scores table
        if risk_scores:
            story.append(Paragraph("Risk Scores", heading_style))
            rs_header = ["Score", "Value", "Category", "Severity", "Interpretation"]
            rs_rows = [rs_header]
            for rs in risk_scores:
                if isinstance(rs, RiskScoreResult):
                    rs_rows.append([
                        rs.score_type.value.upper().replace("_", "-"),
                        f"{rs.score_value:.1f}",
                        rs.risk_category,
                        rs.severity.value.replace("_", " ").title(),
                        rs.interpretation[:60] if rs.interpretation else "",
                    ])
                elif isinstance(rs, dict):
                    rs_rows.append([
                        str(rs.get("score_type", "")),
                        str(rs.get("score_value", "")),
                        str(rs.get("risk_category", "")),
                        str(rs.get("severity", "")),
                        str(rs.get("interpretation", ""))[:60],
                    ])
            if len(rs_rows) > 1:
                rs_table = Table(
                    rs_rows,
                    colWidths=[
                        1.0 * inch, 0.7 * inch, 1.0 * inch,
                        0.9 * inch, 2.9 * inch,
                    ],
                )
                rs_table.setStyle(
                    TableStyle(
                        [
                            ("BACKGROUND", (0, 0), (-1, 0), rl_colors.HexColor("#1A5276")),
                            ("TEXTCOLOR", (0, 0), (-1, 0), rl_colors.white),
                            ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
                            ("FONTSIZE", (0, 0), (-1, -1), 8),
                            ("FONTNAME", (0, 1), (-1, -1), "Helvetica"),
                            ("GRID", (0, 0), (-1, -1), 0.5, rl_colors.HexColor("#BDC3C7")),
                            ("ROWBACKGROUNDS", (0, 1), (-1, -1), [
                                rl_colors.white, rl_colors.HexColor("#F8F9FA"),
                            ]),
                            ("TOPPADDING", (0, 0), (-1, -1), 4),
                            ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
                        ]
                    )
                )
                story.append(rs_table)

        # Recommendations
        if recommendations:
            story.append(Paragraph("Recommendations", heading_style))
            for i, rec in enumerate(recommendations, 1):
                story.append(Paragraph(f"{i}. {rec}", body_style))

        # Disclaimer
        story.append(
            Paragraph(
                "Disclaimer: This report is generated by the HCLS AI Factory "
                "Cardiology Intelligence Agent for clinical decision-support "
                "purposes only. It does not constitute medical advice and must "
                "be reviewed by a qualified healthcare professional before any "
                "clinical action is taken.",
                disclaimer_style,
            )
        )

        # Build PDF
        doc.build(story)
        pdf_bytes = buf.getvalue()
        buf.close()

        # Optionally write to disk
        if output_path:
            with open(output_path, "wb") as f:
                f.write(pdf_bytes)

        return pdf_bytes

    # ── FHIR R4 Export ─────────────────────────────────────────────────

    def export_fhir_r4(
        self,
        response: Union[WorkflowResult, Dict[str, Any]],
        patient_id: str = "DEMO",
    ) -> dict:
        """Export a clinical response as a FHIR R4 DiagnosticReport.

        Produces a FHIR R4 Bundle containing a DiagnosticReport resource
        with Observation references for each risk score.

        Args:
            response: A ``WorkflowResult`` or dict containing clinical data.
            patient_id: Patient identifier (used as FHIR subject reference).

        Returns:
            FHIR R4 Bundle dict ready for JSON serialization.
        """
        now = _now_iso()
        report_id = str(uuid.uuid4())

        # Extract fields
        if isinstance(response, WorkflowResult):
            severity = response.severity
            summary = response.summary
            findings = response.findings
            risk_scores = response.risk_scores
            workflow_type_str = response.workflow_type.value
            confidence = response.confidence
        elif isinstance(response, dict):
            severity = response.get("severity", "low")
            if isinstance(severity, SeverityLevel):
                severity = severity.value
            summary = response.get("summary", "")
            findings = response.get("findings", [])
            risk_scores = response.get("risk_scores", [])
            workflow_type_str = response.get("workflow_type", "general")
            confidence = response.get("confidence", 1.0)
        else:
            severity = "low"
            summary = str(response)
            findings = []
            risk_scores = []
            workflow_type_str = "general"
            confidence = 1.0

        # Build Observation resources for risk scores
        observations: List[dict] = []
        result_refs: List[dict] = []
        for rs in risk_scores:
            obs_id = str(uuid.uuid4())
            if isinstance(rs, RiskScoreResult):
                score_type = rs.score_type.value
                score_value = rs.score_value
                risk_cat = rs.risk_category
                interp = rs.interpretation
            elif isinstance(rs, dict):
                score_type = rs.get("score_type", "unknown")
                score_value = rs.get("score_value", 0)
                risk_cat = rs.get("risk_category", "unknown")
                interp = rs.get("interpretation", "")
            else:
                continue

            observation = {
                "resourceType": "Observation",
                "id": obs_id,
                "status": "final",
                "category": [
                    {
                        "coding": [
                            {
                                "system": "http://terminology.hl7.org/CodeSystem/observation-category",
                                "code": "exam",
                                "display": "Exam",
                            }
                        ]
                    }
                ],
                "code": {
                    "coding": [
                        {
                            "system": "http://hcls-ai-factory.local/cardio/risk-scores",
                            "code": score_type,
                            "display": f"Cardiovascular Risk Score: {score_type.upper()}",
                        }
                    ],
                    "text": f"{score_type.upper()} Risk Score",
                },
                "subject": {"reference": f"Patient/{patient_id}"},
                "effectiveDateTime": now,
                "valueQuantity": {
                    "value": score_value,
                    "unit": "score",
                    "system": "http://unitsofmeasure.org",
                    "code": "{score}",
                },
                "interpretation": [
                    {
                        "coding": [
                            {
                                "system": "http://terminology.hl7.org/CodeSystem/v3-ObservationInterpretation",
                                "code": _fhir_interpretation_code(risk_cat),
                                "display": risk_cat,
                            }
                        ],
                        "text": interp,
                    }
                ],
            }
            observations.append(observation)
            result_refs.append({"reference": f"Observation/{obs_id}"})

        # Build conclusion text
        conclusion_parts = [summary] if summary else []
        if findings:
            conclusion_parts.append("Findings: " + "; ".join(findings[:5]))

        # LOINC code for cardiovascular assessment
        report_code = {
            "coding": [
                {
                    "system": "http://loinc.org",
                    "code": "34140-4",
                    "display": "Cardiology Consultation note",
                }
            ],
            "text": f"Cardiology Intelligence Report ({workflow_type_str})",
        }

        # Build DiagnosticReport
        diagnostic_report = {
            "resourceType": "DiagnosticReport",
            "id": report_id,
            "status": "final",
            "category": [
                {
                    "coding": [
                        {
                            "system": "http://terminology.hl7.org/CodeSystem/v2-0074",
                            "code": "CUS",
                            "display": "Cardiac Ultrasound",
                        }
                    ]
                }
            ],
            "code": report_code,
            "subject": {"reference": f"Patient/{patient_id}"},
            "effectiveDateTime": now,
            "issued": now,
            "conclusion": ". ".join(conclusion_parts) if conclusion_parts else "No significant findings.",
            "result": result_refs,
            "presentedForm": [
                {
                    "contentType": "text/markdown",
                    "language": "en",
                    "title": "Cardiology Intelligence Report (Markdown)",
                    "data": "",  # Base64 of Markdown would go here in production
                }
            ],
            "extension": [
                {
                    "url": "http://hcls-ai-factory.local/fhir/StructureDefinition/agent-confidence",
                    "valueDecimal": confidence,
                },
                {
                    "url": "http://hcls-ai-factory.local/fhir/StructureDefinition/clinical-severity",
                    "valueString": severity if isinstance(severity, str) else severity.value,
                },
            ],
        }

        # Assemble Bundle
        bundle_entries = [
            {"fullUrl": f"urn:uuid:{report_id}", "resource": diagnostic_report}
        ]
        for obs in observations:
            bundle_entries.append(
                {"fullUrl": f"urn:uuid:{obs['id']}", "resource": obs}
            )

        bundle = {
            "resourceType": "Bundle",
            "id": str(uuid.uuid4()),
            "type": "collection",
            "timestamp": now,
            "entry": bundle_entries,
            "meta": {
                "profile": [
                    "http://hcls-ai-factory.local/fhir/StructureDefinition/CardioIntelligenceBundle"
                ],
                "tag": [
                    {
                        "system": "http://hcls-ai-factory.local/fhir/CodeSystem/agent-version",
                        "code": VERSION,
                        "display": f"Cardiology Intelligence Agent v{VERSION}",
                    }
                ],
            },
        }

        return bundle

    # ── Risk Score Report ──────────────────────────────────────────────

    def export_risk_score_report(
        self,
        risk_scores: List[RiskScoreResult],
        patient_id: str = "DEMO",
    ) -> str:
        """Export a dedicated risk score report with all calculated scores.

        Produces a detailed Markdown report focused exclusively on
        cardiovascular risk scores, their interpretation, component
        breakdowns, and clinical recommendations.

        Args:
            risk_scores: List of ``RiskScoreResult`` instances.
            patient_id: Patient identifier.

        Returns:
            Markdown report as a string.
        """
        timestamp = _now_display()
        template = REPORT_TEMPLATES["risk_assessment"]
        lines: List[str] = [
            template.format(
                patient_id=patient_id, timestamp=timestamp, version=VERSION,
            )
        ]

        if not risk_scores:
            lines.append("*No risk scores available for this patient.*\n")
            lines.append(_DISCLAIMER)
            return "\n".join(lines)

        # Overall severity (highest among scores)
        max_sev = max(risk_scores, key=lambda r: _severity_ordinal(r.severity))
        lines.append(
            f"**Overall Risk Severity:** "
            f"{_severity_badge(max_sev.severity)}\n\n"
        )

        # Summary table
        lines.append("## Score Summary\n")
        lines.append(format_risk_score_table(risk_scores))
        lines.append("\n")

        # Detailed breakdown per score
        lines.append("## Detailed Score Analysis\n")
        for i, rs in enumerate(risk_scores, 1):
            stype = rs.score_type.value.upper().replace("_", "-")
            lines.append(f"### {i}. {stype}\n")
            lines.append(f"- **Score Value:** {rs.score_value:.1f}")
            lines.append(f"- **Risk Category:** {rs.risk_category}")
            sev_label = rs.severity.value.replace("_", " ").title()
            lines.append(f"- **Severity:** {sev_label}")
            lines.append(f"- **Interpretation:** {rs.interpretation}\n")

            class_loe = _format_class_loe(rs.guideline_class, rs.evidence_level)
            if class_loe:
                lines.append(f"**Guideline Recommendation:** {class_loe}\n")
            if rs.guideline_reference:
                lines.append(format_guideline_citation(rs.guideline_reference))

            if rs.component_breakdown:
                lines.append("\n**Component Breakdown:**\n")
                lines.append("| Component | Value |")
                lines.append("|-----------|-------|")
                for comp_name, comp_val in rs.component_breakdown.items():
                    lines.append(f"| {comp_name} | {comp_val} |")
                lines.append("")

            if rs.recommendations:
                lines.append("\n**Clinical Recommendations:**\n")
                for rec in rs.recommendations:
                    lines.append(f"- {rec}")
                lines.append("")

            lines.append("")

        # Aggregated recommendations
        all_recs = []
        for rs in risk_scores:
            all_recs.extend(rs.recommendations)
        if all_recs:
            lines.append("## Consolidated Recommendations\n")
            seen = set()
            for rec in all_recs:
                if rec not in seen:
                    seen.add(rec)
                    lines.append(f"- {rec}")
            lines.append("\n")

        lines.append(_DISCLAIMER)
        return "\n".join(lines)

    # ── GDMT Report ────────────────────────────────────────────────────

    def export_gdmt_report(
        self,
        gdmt_recommendation: GDMTRecommendation,
        patient_id: str = "DEMO",
    ) -> str:
        """Export a GDMT optimisation report.

        Produces a detailed Markdown report covering the four pillars of
        guideline-directed medical therapy for heart failure, including
        current status, gaps, titration plans, and device therapy
        considerations.

        Args:
            gdmt_recommendation: A ``GDMTRecommendation`` instance.
            patient_id: Patient identifier.

        Returns:
            Markdown report as a string.
        """
        gdmt = gdmt_recommendation
        timestamp = _now_display()
        template = REPORT_TEMPLATES["gdmt_optimization"]
        lines: List[str] = [
            template.format(
                patient_id=patient_id, timestamp=timestamp, version=VERSION,
            )
        ]

        # Patient classification
        lines.append("## Heart Failure Classification\n")
        lines.append(f"- **EF Category:** {gdmt.ef_category.value}")
        lines.append(f"- **NYHA Class:** {gdmt.nyha_class.value}")
        lines.append(
            f"- **Overall Status:** {gdmt.overall_status or 'Not assessed'}"
        )
        sev_label = gdmt.severity.value.replace("_", " ").title()
        lines.append(f"- **Severity:** {sev_label}\n")

        # Four pillars status
        lines.append("## GDMT Four Pillars Status\n")
        lines.append(
            "| Pillar | Drug | Current Dose | Target Dose | Status |"
        )
        lines.append(
            "|--------|------|-------------|-------------|--------|"
        )
        for pillar_name, med in gdmt.current_gdmt.items():
            status_label = med.status.value.replace("_", " ").title()
            lines.append(
                f"| {pillar_name.replace('_', ' ').title()} "
                f"| {med.drug_name} "
                f"| {med.current_dose or 'N/A'} "
                f"| {med.target_dose or 'N/A'} "
                f"| {status_label} |"
            )
        lines.append("")

        # Gaps identified
        if gdmt.gaps_identified:
            lines.append("## Gaps Identified\n")
            for gap in gdmt.gaps_identified:
                lines.append(f"- {gap}")
            lines.append("")

        # New medications to initiate
        if gdmt.new_medications:
            lines.append("## New Medications to Initiate\n")
            for med in gdmt.new_medications:
                if isinstance(med, dict):
                    name = med.get("drug", med.get("name", "Unknown"))
                    dose = med.get("starting_dose", med.get("dose", ""))
                    reason = med.get("reason", "")
                    lines.append(f"- **{name}**: Start {dose}")
                    if reason:
                        lines.append(f"  - Rationale: {reason}")
                else:
                    lines.append(f"- {med}")
            lines.append("")

        # Titration plans
        if gdmt.titration_plans:
            lines.append("## Titration Plans\n")
            for plan in gdmt.titration_plans:
                if isinstance(plan, dict):
                    drug = plan.get("drug", "Unknown")
                    current = plan.get("current_dose", "")
                    target = plan.get("target_dose", "")
                    interval = plan.get("titration_interval", "2 weeks")
                    lines.append(
                        f"- **{drug}**: {current} -> {target} "
                        f"(titrate every {interval})"
                    )
                else:
                    lines.append(f"- {plan}")
            lines.append("")

        # Additional therapies
        if gdmt.additional_therapies:
            lines.append("## Additional Therapies\n")
            for therapy in gdmt.additional_therapies:
                if isinstance(therapy, dict):
                    name = therapy.get("name", therapy.get("therapy", "Unknown"))
                    indication = therapy.get("indication", "")
                    lines.append(f"- **{name}**")
                    if indication:
                        lines.append(f"  - Indication: {indication}")
                else:
                    lines.append(f"- {therapy}")
            lines.append("")

        # Device therapy
        if gdmt.device_therapy:
            lines.append("## Device Therapy Considerations\n")
            for device in gdmt.device_therapy:
                if isinstance(device, dict):
                    dtype = device.get("type", device.get("device", "Unknown"))
                    indication = device.get("indication", "")
                    criteria = device.get("criteria_met", "")
                    lines.append(f"- **{dtype}**")
                    if indication:
                        lines.append(f"  - Indication: {indication}")
                    if criteria:
                        lines.append(f"  - Criteria: {criteria}")
                else:
                    lines.append(f"- {device}")
            lines.append("")

        # Monitoring plan
        if gdmt.monitoring_plan:
            lines.append("## Monitoring Plan\n")
            for key, value in gdmt.monitoring_plan.items():
                label = key.replace("_", " ").title()
                lines.append(f"- **{label}:** {value}")
            lines.append("")

        # Contraindications and warnings
        if gdmt.contraindication_notes:
            lines.append("## Contraindication Notes\n")
            for note in gdmt.contraindication_notes:
                lines.append(f"- {note}")
            lines.append("")

        if gdmt.interaction_warnings:
            lines.append("## Drug Interaction Warnings\n")
            for warning in gdmt.interaction_warnings:
                lines.append(f"- {warning}")
            lines.append("")

        # Reassessment
        lines.append("## Reassessment Timeline\n")
        lines.append(f"{gdmt.reassessment_timeline}\n")

        # Guideline reference
        lines.append(format_guideline_citation(gdmt.guideline_reference))

        lines.append(_DISCLAIMER)
        return "\n".join(lines)

    # ── Workflow Report ────────────────────────────────────────────────

    def export_workflow_report(
        self,
        workflow_result: WorkflowResult,
        patient_id: str = "DEMO",
    ) -> str:
        """Export clinical workflow results as a structured report.

        This is a convenience wrapper around ``export_markdown()`` with
        the ``workflow`` template and additional raw-data sections.

        Args:
            workflow_result: A ``WorkflowResult`` instance.
            patient_id: Patient identifier.

        Returns:
            Markdown report as a string.
        """
        timestamp = _now_display()
        wf_type = workflow_result.workflow_type.value.replace("_", " ").title()
        template = REPORT_TEMPLATES["workflow"]
        lines: List[str] = [
            template.format(
                patient_id=patient_id,
                timestamp=timestamp,
                version=VERSION,
                workflow_type=wf_type,
            )
        ]

        # Severity and confidence
        lines.append(
            f"**Severity:** {_severity_badge(workflow_result.severity)}\n"
        )
        lines.append(f"**Confidence:** {workflow_result.confidence:.0%}\n\n")

        # Summary
        lines.append("## Summary\n")
        if workflow_result.summary:
            lines.append(f"{workflow_result.summary}\n\n")
        else:
            lines.append("*No summary available.*\n\n")

        # Findings
        if workflow_result.findings:
            lines.append("## Findings\n")
            for i, f in enumerate(workflow_result.findings, 1):
                lines.append(f"{i}. {f}")
            lines.append("\n")

        # Risk scores
        if workflow_result.risk_scores:
            lines.append("## Risk Scores\n")
            lines.append(format_risk_score_table(workflow_result.risk_scores))
            lines.append("\n")

        # Recommendations
        if workflow_result.recommendations:
            lines.append("## Recommendations\n")
            for i, rec in enumerate(workflow_result.recommendations, 1):
                lines.append(f"{i}. {rec}")
            lines.append("\n")

        # Guideline references
        if workflow_result.guideline_references:
            lines.append("## Guideline References\n")
            for ref in workflow_result.guideline_references:
                lines.append(format_guideline_citation(ref))
            lines.append("\n")

        # Cross-modal triggers
        if workflow_result.cross_modal_triggers:
            lines.append("## Cross-Modal Genomic Triggers\n")
            for trigger in workflow_result.cross_modal_triggers:
                if isinstance(trigger, CrossModalTrigger):
                    lines.append(_format_cross_modal_trigger(trigger))
                lines.append("")
            lines.append("\n")

        # Raw data (if present)
        if workflow_result.raw_data:
            lines.append("## Intermediate Data\n")
            lines.append("```json")
            lines.append(json.dumps(workflow_result.raw_data, indent=2, default=str))
            lines.append("```\n")

        lines.append(_DISCLAIMER)
        return "\n".join(lines)


# ═══════════════════════════════════════════════════════════════════════
# PRIVATE HELPERS
# ═══════════════════════════════════════════════════════════════════════


def _severity_ordinal(severity: SeverityLevel) -> int:
    """Map severity to an ordinal for comparison."""
    order = {
        SeverityLevel.LOW: 0,
        SeverityLevel.BORDERLINE: 1,
        SeverityLevel.INTERMEDIATE: 2,
        SeverityLevel.MODERATE: 3,
        SeverityLevel.HIGH: 4,
        SeverityLevel.VERY_HIGH: 5,
        SeverityLevel.CRITICAL: 6,
    }
    return order.get(severity, 0)


def _fhir_interpretation_code(risk_category: str) -> str:
    """Map a risk category string to a FHIR observation interpretation code.

    Uses the v3 ObservationInterpretation value set:
      - N  = Normal
      - L  = Low
      - H  = High
      - HH = Critical high
    """
    cat = risk_category.lower()
    if "critical" in cat or "very high" in cat:
        return "HH"
    if "high" in cat:
        return "H"
    if "low" in cat:
        return "L"
    return "N"


# ═══════════════════════════════════════════════════════════════════════
# MODULE-LEVEL CONVENIENCE FUNCTIONS
# ═══════════════════════════════════════════════════════════════════════

_default_exporter = CardioReportExporter()


def export_markdown(
    response: Union[WorkflowResult, Dict[str, Any]],
    patient_id: str = "DEMO",
    report_type: str = "consultation",
) -> str:
    """Module-level convenience for ``CardioReportExporter.export_markdown``."""
    return _default_exporter.export_markdown(response, patient_id, report_type)


def export_json(
    response: Union[WorkflowResult, Dict[str, Any]],
    patient_id: str = "DEMO",
) -> dict:
    """Module-level convenience for ``CardioReportExporter.export_json``."""
    return _default_exporter.export_json(response, patient_id)


def export_pdf(
    response: Union[WorkflowResult, Dict[str, Any]],
    patient_id: str = "DEMO",
    output_path: Optional[str] = None,
) -> bytes:
    """Module-level convenience for ``CardioReportExporter.export_pdf``."""
    return _default_exporter.export_pdf(response, patient_id, output_path)


def export_fhir_r4(
    response: Union[WorkflowResult, Dict[str, Any]],
    patient_id: str = "DEMO",
) -> dict:
    """Module-level convenience for ``CardioReportExporter.export_fhir_r4``."""
    return _default_exporter.export_fhir_r4(response, patient_id)


def generate_filename(extension: str) -> str:
    """Generate a timestamped filename for cardiology report export.

    Args:
        extension: File extension without dot (e.g. ``"md"``, ``"json"``).

    Returns:
        Filename like ``cardio_report_20260313T120000Z.md``.
    """
    return _generate_filename("cardio_report", extension)
