"""Prometheus metrics for the Pharmacogenomics Intelligence Agent.

Exposes counters, histograms, and gauges for query latency, collection hits,
LLM token usage, evidence counts, clinical alerts, drug checks, phenoconversion
detection, HLA screening, VCF processing, and ingest freshness.  Scraped by the
Grafana + Prometheus stack on port 9099.

All metrics use the ``pgx_`` prefix so they are easily filterable in
Grafana dashboards alongside the existing HCLS AI Factory exporters
(node_exporter:9100, DCGM:9400).

If ``prometheus_client`` is not installed the module silently exports
no-op stubs so the rest of the application can import metrics helpers
without a hard dependency.

Author: Adam Jones
Date: March 2026
"""

from __future__ import annotations

from typing import Dict

try:
    from prometheus_client import Counter, Gauge, Histogram, generate_latest

    # -- Histograms --

    QUERY_LATENCY = Histogram(
        "pgx_query_latency_seconds",
        "Query processing time",
        ["query_type"],
        buckets=[0.1, 0.5, 1, 2, 5, 10, 30],
    )

    EVIDENCE_COUNT = Histogram(
        "pgx_evidence_count",
        "Evidence items per query",
        buckets=[0, 5, 10, 15, 20, 25, 30],
    )

    CROSS_COLLECTION_QUERY_LATENCY = Histogram(
        "pgx_cross_collection_query_latency_seconds",
        "Cross-collection query processing time",
        ["query_type"],
        buckets=[0.1, 0.5, 1, 2, 5, 10, 30],
    )

    CROSS_COLLECTION_RESULTS = Histogram(
        "pgx_cross_collection_results_count",
        "Number of results returned from cross-collection queries",
        buckets=[0, 1, 5, 10, 20, 50, 100],
    )

    LLM_API_LATENCY = Histogram(
        "pgx_llm_api_latency_seconds",
        "LLM API call latency",
        ["provider", "model"],
        buckets=[0.5, 1, 2, 5, 10, 30, 60],
    )

    EMBEDDING_LATENCY = Histogram(
        "pgx_embedding_latency_seconds",
        "Embedding generation latency",
        buckets=[0.01, 0.05, 0.1, 0.25, 0.5, 1],
    )

    PIPELINE_STAGE_DURATION = Histogram(
        "pgx_pipeline_stage_duration_seconds",
        "Duration of individual pipeline stages",
        ["stage"],
        buckets=[0.1, 0.5, 1, 5, 10, 30, 60, 120],
    )

    MILVUS_SEARCH_LATENCY = Histogram(
        "pgx_milvus_search_latency_seconds",
        "Milvus vector search latency",
        buckets=[0.01, 0.05, 0.1, 0.25, 0.5, 1, 2],
    )

    MILVUS_UPSERT_LATENCY = Histogram(
        "pgx_milvus_upsert_latency_seconds",
        "Milvus upsert latency",
        buckets=[0.01, 0.05, 0.1, 0.25, 0.5, 1, 5],
    )

    VCF_PROCESSING = Histogram(
        "pgx_vcf_processing_seconds",
        "VCF file processing time for PGx variant extraction",
        ["sample_type"],
        buckets=[0.5, 1, 5, 10, 30, 60, 120, 300, 600],
    )

    # -- Counters --

    QUERY_COUNT = Counter(
        "pgx_queries_total",
        "Total queries processed",
        ["query_type", "status"],
    )

    COLLECTION_HITS = Counter(
        "pgx_collection_hits_total",
        "Hits by collection",
        ["collection"],
    )

    LLM_TOKENS = Counter(
        "pgx_llm_tokens_total",
        "LLM tokens used",
        ["direction"],
    )

    ALERTS_GENERATED = Counter(
        "pgx_alerts_generated_total",
        "Clinical decision support alerts generated",
        ["alert_level"],
    )

    DRUG_CHECKS = Counter(
        "pgx_drug_checks_total",
        "Drug-gene interaction checks performed",
        ["gene", "drug"],
    )

    PHENOCONVERSIONS_DETECTED = Counter(
        "pgx_phenoconversions_detected_total",
        "Drug-induced phenoconversions detected",
        ["enzyme", "precipitant_drug"],
    )

    HLA_SCREENS = Counter(
        "pgx_hla_screens_total",
        "HLA allele screening checks performed",
        ["hla_allele", "drug"],
    )

    REPORTS_GENERATED = Counter(
        "pgx_reports_generated_total",
        "Reports generated by format",
        ["format"],
    )

    # -- Gauges --

    ACTIVE_CONNECTIONS = Gauge(
        "pgx_active_connections",
        "Active connections",
    )

    COLLECTION_SIZE = Gauge(
        "pgx_collection_size",
        "Records per collection",
        ["collection"],
    )

    LAST_INGEST = Gauge(
        "pgx_last_ingest_timestamp",
        "Last ingest timestamp",
        ["source"],
    )

    PATIENT_PROFILES_STORED = Gauge(
        "pgx_patient_profiles_stored",
        "Number of patient PGx profiles stored in the system",
    )

    _PROMETHEUS_AVAILABLE = True

except ImportError:
    # -- No-op stubs when prometheus_client is not installed --
    _PROMETHEUS_AVAILABLE = False

    class _NoOpLabeled:
        """Stub that silently ignores .labels().observe/inc/set calls."""

        def labels(self, *args, **kwargs):
            return self

        def observe(self, *args, **kwargs):
            pass

        def inc(self, *args, **kwargs):
            pass

        def dec(self, *args, **kwargs):
            pass

        def set(self, *args, **kwargs):
            pass

    class _NoOpGauge:
        """Stub for label-less Gauge (ACTIVE_CONNECTIONS, PATIENT_PROFILES_STORED)."""

        def inc(self, *args, **kwargs):
            pass

        def dec(self, *args, **kwargs):
            pass

        def set(self, *args, **kwargs):
            pass

    QUERY_LATENCY = _NoOpLabeled()                    # type: ignore[assignment]
    EVIDENCE_COUNT = _NoOpLabeled()                    # type: ignore[assignment]
    QUERY_COUNT = _NoOpLabeled()                       # type: ignore[assignment]
    COLLECTION_HITS = _NoOpLabeled()                   # type: ignore[assignment]
    LLM_TOKENS = _NoOpLabeled()                        # type: ignore[assignment]
    ACTIVE_CONNECTIONS = _NoOpGauge()                   # type: ignore[assignment]
    COLLECTION_SIZE = _NoOpLabeled()                    # type: ignore[assignment]
    LAST_INGEST = _NoOpLabeled()                        # type: ignore[assignment]

    CROSS_COLLECTION_QUERY_LATENCY = _NoOpLabeled()    # type: ignore[assignment]
    CROSS_COLLECTION_RESULTS = _NoOpLabeled()           # type: ignore[assignment]
    LLM_API_LATENCY = _NoOpLabeled()                    # type: ignore[assignment]
    EMBEDDING_LATENCY = _NoOpLabeled()                  # type: ignore[assignment]
    PIPELINE_STAGE_DURATION = _NoOpLabeled()            # type: ignore[assignment]
    MILVUS_SEARCH_LATENCY = _NoOpLabeled()              # type: ignore[assignment]
    MILVUS_UPSERT_LATENCY = _NoOpLabeled()              # type: ignore[assignment]
    VCF_PROCESSING = _NoOpLabeled()                     # type: ignore[assignment]
    ALERTS_GENERATED = _NoOpLabeled()                   # type: ignore[assignment]
    DRUG_CHECKS = _NoOpLabeled()                        # type: ignore[assignment]
    PHENOCONVERSIONS_DETECTED = _NoOpLabeled()          # type: ignore[assignment]
    HLA_SCREENS = _NoOpLabeled()                        # type: ignore[assignment]
    REPORTS_GENERATED = _NoOpLabeled()                  # type: ignore[assignment]
    PATIENT_PROFILES_STORED = _NoOpGauge()              # type: ignore[assignment]

    def generate_latest() -> bytes:  # type: ignore[misc]
        return b""


# =====================================================================
# HELPER FUNCTIONS
# =====================================================================


def record_query(
    query_type: str,
    latency: float,
    hit_count: int,
    status: str = "success",
) -> None:
    """Record metrics for a completed query.

    Call this once at the end of every RAG query or agent run to update
    latency, hit count, and total-query counters in a single place.

    Args:
        query_type: Query category -- e.g. ``"rag"``, ``"agent"``,
            ``"gene_query"``, ``"drug_query"``, ``"hla_screen"``.
        latency: Wall-clock processing time in **seconds**.
        hit_count: Total evidence items returned to the user.
        status: Outcome label -- ``"success"`` or ``"error"``.
    """
    QUERY_LATENCY.labels(query_type=query_type).observe(latency)
    QUERY_COUNT.labels(query_type=query_type, status=status).inc()
    EVIDENCE_COUNT.observe(hit_count)


def record_collection_hits(hits_by_collection: Dict[str, int]) -> None:
    """Increment per-collection hit counters.

    Args:
        hits_by_collection: Mapping of collection name (e.g.
            ``"pgx_drug_guidelines"``) to the number of hits returned from
            that collection in a single query.
    """
    for collection, count in hits_by_collection.items():
        COLLECTION_HITS.labels(collection=collection).inc(count)


def update_collection_sizes(stats: Dict[str, int]) -> None:
    """Set the current record count for each collection.

    Typically called after ``PGxCollectionManager.get_collection_stats()``
    returns its ``{collection_name: row_count}`` dict.

    Args:
        stats: Mapping of collection name to entity/row count.
    """
    for collection, size in stats.items():
        COLLECTION_SIZE.labels(collection=collection).set(size)


def record_llm_call(
    provider: str,
    model: str,
    latency: float,
    input_tokens: int = 0,
    output_tokens: int = 0,
) -> None:
    """Record metrics for an LLM API call.

    Args:
        provider: LLM provider (e.g. ``"anthropic"``, ``"openai"``).
        model: Model identifier (e.g. ``"claude-sonnet-4-6"``).
        latency: Call latency in **seconds**.
        input_tokens: Number of input tokens used.
        output_tokens: Number of output tokens generated.
    """
    LLM_API_LATENCY.labels(provider=provider, model=model).observe(latency)
    if input_tokens > 0:
        LLM_TOKENS.labels(direction="input").inc(input_tokens)
    if output_tokens > 0:
        LLM_TOKENS.labels(direction="output").inc(output_tokens)


def record_embedding(latency: float) -> None:
    """Record metrics for an embedding operation.

    Args:
        latency: Embedding generation time in **seconds**.
    """
    EMBEDDING_LATENCY.observe(latency)


def record_pipeline_stage(stage: str, duration: float) -> None:
    """Record duration for a pipeline stage.

    Args:
        stage: Stage name (e.g. ``"plan"``, ``"search"``, ``"evaluate"``,
            ``"synthesize"``, ``"report"``).
        duration: Stage duration in **seconds**.
    """
    PIPELINE_STAGE_DURATION.labels(stage=stage).observe(duration)


def record_alert_generated(alert_level: str) -> None:
    """Record a clinical decision support alert generation.

    Args:
        alert_level: Alert severity -- ``"critical"``, ``"warning"``, or ``"info"``.
    """
    ALERTS_GENERATED.labels(alert_level=alert_level).inc()


def record_drug_check(gene: str, drug: str) -> None:
    """Record a drug-gene interaction check.

    Args:
        gene: Gene symbol (e.g. ``"CYP2D6"``).
        drug: Drug name (e.g. ``"codeine"``).
    """
    DRUG_CHECKS.labels(gene=gene, drug=drug).inc()


def record_phenoconversion(enzyme: str, precipitant_drug: str) -> None:
    """Record a detected drug-induced phenoconversion.

    Args:
        enzyme: Affected enzyme (e.g. ``"CYP2D6"``).
        precipitant_drug: Drug causing the inhibition (e.g. ``"fluoxetine"``).
    """
    PHENOCONVERSIONS_DETECTED.labels(
        enzyme=enzyme, precipitant_drug=precipitant_drug,
    ).inc()


def record_hla_screen(hla_allele: str, drug: str) -> None:
    """Record an HLA allele screening check.

    Args:
        hla_allele: HLA allele tested (e.g. ``"HLA-B*57:01"``).
        drug: Drug requiring screening (e.g. ``"abacavir"``).
    """
    HLA_SCREENS.labels(hla_allele=hla_allele, drug=drug).inc()


def record_report_generated(fmt: str) -> None:
    """Record a report generation.

    Args:
        fmt: Report format (e.g. ``"pdf"``, ``"markdown"``, ``"json"``,
            ``"fhir_r4"``, ``"passport"``).
    """
    REPORTS_GENERATED.labels(format=fmt).inc()


def record_vcf_processing(sample_type: str, duration: float) -> None:
    """Record VCF file processing time for PGx variant extraction.

    Args:
        sample_type: Type of sample (e.g. ``"wgs"``, ``"wes"``, ``"panel"``).
        duration: Processing time in **seconds**.
    """
    VCF_PROCESSING.labels(sample_type=sample_type).observe(duration)


def get_metrics_text() -> str:
    """Return the current Prometheus metrics exposition in text format.

    This is the string you serve at ``/metrics`` (typically via FastAPI
    or a dedicated ``prometheus_client.start_http_server``).

    Returns:
        UTF-8 decoded Prometheus exposition text, or an empty string if
        ``prometheus_client`` is not installed.
    """
    return generate_latest().decode("utf-8")
