#!/usr/bin/env python3
"""Check the published docs for two defects that a strict mkdocs build does not catch.

1. **Broken internal links.** mkdocs resolves links at build time, so a page generated by
   mkdocs-gen-files (the maturity matrix, the per-capability pages) is NOT missing even though
   it is absent from the repo. A naive checker reports 40 broken links here; 29 of them are
   generated pages. This one reads the generator list and the capability registry so the number
   it prints is the number worth acting on.

2. **Commands that name a script which does not exist.** This is the defect the checker was
   written for: 26 references across five guides told the reader to run `./setup-data.sh --all`,
   a script with a full documented flag interface that was never written. The documented FIRST
   STEP of the public repo failed immediately. `start-services.sh` and `run_pipeline.py` were
   the same. A broken link is a nuisance; a confident instruction to run a command that does not
   exist is the honesty failure this platform exists to avoid.

Usage:
    .venv/bin/python scripts/check_docs.py            # docs/ + the engine READMEs
    .venv/bin/python scripts/check_docs.py --all      # every tracked markdown file
"""
from __future__ import annotations

import json
import pathlib
import re
import subprocess
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
DOCS = ROOT / "docs"

# Pages mkdocs-gen-files creates during the build; absent from the repo by design.
GENERATED_STATIC = {"factory/engines/index.md", "factory/agents/index.md",
                    "brief/README.md", "honesty/maturity-matrix.md"}

# Scripts that are CREATED by a tool at run time and are correctly absent from the repo.
# NVFlare writes these into provision/workspace/*/startup/ when a federation is provisioned.
KNOWN_ABSENT: set[str] = {"start.sh", "fl_admin.sh"}

# Link-checking is skipped here: site_content/{engines,agents}/*.md is INJECTED into the page
# mkdocs-gen-files writes at factory/{engines,agents}/<id>.md, so its relative links resolve
# from that destination, not from where the source file sits.
LINK_SKIP_PREFIXES = ("site_content/",)


def generated_pages() -> set[str]:
    pages = set(GENERATED_STATIC)
    reg = json.loads((ROOT / "lib" / "hcls_common" / "capabilities.json").read_text())
    for c in reg["capabilities"]:
        if c.get("type") == "engine":
            pages.add(f"factory/engines/{c['id']}.md")
        elif c.get("type") == "agent":
            pages.add(f"factory/agents/{c['id']}.md")
    return pages


def tracked_markdown(all_files: bool) -> list[pathlib.Path]:
    # -z: tracked filenames contain spaces (a "Claude ….md" under precision-biomarker),
    # and splitting on whitespace silently truncates them into paths that do not exist.
    out = subprocess.run(["git", "ls-files", "-z", "*.md"], cwd=ROOT,
                         capture_output=True, text=True).stdout.split("\0")
    paths = [ROOT / f for f in out if f]
    if all_files:
        return paths
    keep = ("docs/", "core/engines/genomic-foundation/", "core/engines/precision-intelligence/")
    return [p for p in paths
            if any(str(p.relative_to(ROOT)).startswith(k) for k in keep)
            and "open_public" not in str(p)]


def check_links(paths: list[pathlib.Path], gen: set[str]) -> list[str]:
    bad = []
    for md in paths:
        if str(md.relative_to(ROOT)).startswith(LINK_SKIP_PREFIXES):
            continue
        for m in re.finditer(r"\]\(([^)#:]+\.md)[#)]", md.read_text(errors="ignore")):
            target = md.parent / m.group(1)
            if target.resolve().exists():
                continue
            try:
                rel = str(target.resolve().relative_to(DOCS.resolve()))
            except ValueError:
                rel = None
            if rel in gen:
                continue
            bad.append(f"{md.relative_to(ROOT)} -> {m.group(1)}")
    return bad


# `./foo.sh`, `./foo.sh --flag`, at the start of a shell-block line or inline.
_CMD = re.compile(r"(?:^|\s|`)\./([A-Za-z0-9_.-]+\.(?:sh|py))\b")
_CD = re.compile(r"^\s*(?:#\s*)?cd\s+([A-Za-z0-9_./-]+)")
_FENCE = re.compile(r"^\s*```")


_BASENAMES: set[str] | None = None


def _tracked_basenames() -> set[str]:
    """Every tracked file's basename.

    The check deliberately stops at "does a script by this name exist in the repo at all",
    rather than trying to prove the reader's working directory. Proving the path needs a shell
    interpreter; the defect this exists to catch — `setup-data.sh`, `start-services.sh`,
    `run_pipeline.py`, documented with full flag interfaces and never written — is caught by the
    weaker rule, and the weaker rule produces no false alarms. A check that cries wolf is one
    nobody runs.
    """
    global _BASENAMES
    if _BASENAMES is None:
        out = subprocess.run(["git", "ls-files", "-z"], cwd=ROOT,
                             capture_output=True, text=True).stdout.split("\0")
        _BASENAMES = {pathlib.Path(f).name for f in out if f}
    return _BASENAMES


def _resolve_dir(target: str, cwd: pathlib.Path, doc_dir: pathlib.Path):
    """Resolve a `cd` target the way a reader would: relative to here, to the repo root, or to
    any ancestor of the document — a guide in `<engine>/docs/` saying `cd web-portal` means
    `<engine>/web-portal`."""
    if target.startswith("/"):
        p = pathlib.Path(target)
        return p.resolve() if p.is_dir() else None
    tries = [cwd / target, ROOT / target]
    here = doc_dir
    while True:
        tries.append(here / target)
        if here == ROOT or here.parent == here:
            break
        here = here.parent
    for t in tries:
        if t.is_dir():
            return t.resolve()
    return None


def check_commands(paths: list[pathlib.Path]) -> list[str]:
    """A `./script.sh` reference must resolve from where the reader would actually be.

    That means following `cd` inside the same fenced block: a guide at the repo root may
    legitimately say `cd core/engines/genomic-foundation` and then `./run.sh download`.
    Without tracking the `cd`, every such line reads as broken and the check becomes noise —
    and a check that cries wolf is one nobody runs.
    """
    bad = []
    for md in paths:
        text = md.read_text(errors="ignore")
        cwd = md.parent            # outside a fence, resolve next to the document
        in_fence = False
        for lineno, line in enumerate(text.splitlines(), 1):
            if _FENCE.match(line):
                in_fence = not in_fence
                if in_fence:
                    cwd = md.parent        # each block starts where the document lives
                continue
            if m := _CD.match(line):
                if (d := _resolve_dir(m.group(1), cwd, md.parent)) is not None:
                    cwd = d
                if "&&" not in line:       # `cd x && ./y` continues on this same line
                    continue
            for m in _CMD.finditer(line):
                name = m.group(1)
                if name in KNOWN_ABSENT:
                    continue
                candidates = [cwd / name, md.parent / name, ROOT / name]
                here = md.parent
                while here != ROOT and here.parent != here:
                    candidates.append(here / name)
                    here = here.parent
                if any(c.exists() for c in candidates) or name in _tracked_basenames():
                    continue
                bad.append(f"{md.relative_to(ROOT)}:{lineno} -> ./{name} does not exist")
    return bad


def main() -> int:
    all_files = "--all" in sys.argv
    paths = tracked_markdown(all_files)
    gen = generated_pages()

    links = check_links(paths, gen)
    cmds = check_commands(paths)

    print(f"  scanned {len(paths)} markdown files "
          f"({'all tracked' if all_files else 'docs/ + genomics & intelligence engines'})")
    print(f"  {len(gen)} build-generated pages excluded from the link check\n")

    for b in links:
        print(f"  BROKEN LINK  {b}")
    for b in cmds:
        print(f"  MISSING CMD  {b}")

    if not links and not cmds:
        print("  OK — every internal link resolves and every referenced script exists.")
        return 0
    print(f"\n  {len(links)} broken links · {len(cmds)} references to missing scripts")
    return 1


if __name__ == "__main__":
    raise SystemExit(main())
