#!/usr/bin/env python3
"""Generate the four documentation guides for each of the 17 subjects.

Overview · Foundation Learning · Advanced Learning · Demo  =  4 x 17 = 68 documents.
With one infographic each (gen_subject_infographics.py) that is the 85-asset set.

Every factual statement — ports, test counts, module names, capability status, dependencies — comes
from scripts/subject_facts.py, which reads the repo. The per-subject clinical framing in CONTEXT is
hand-written, because that is the part that requires judgement and must not be autogenerated.

Nothing here invents a capability, a port, or a claim. If a subject has no API port, the guide says
so rather than deriving one.

Usage:
    .venv/bin/python scripts/gen_subject_guides.py            # all 17
    .venv/bin/python scripts/gen_subject_guides.py cardiology # one
"""
from __future__ import annotations
import json, pathlib, subprocess, sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
OUT = ROOT / "docs" / "subjects"

DISCLAIMER = ("> **Decision support for a qualified clinician — never autonomous diagnosis or "
              "prescribing.** Every output on this page is intended to inform a clinician's "
              "judgement, not replace it.")

# Hand-written per subject. Keys: what it is for a lay reader, why it matters clinically,
# the honest limit, and the concept a newcomer must grasp first.
CONTEXT = {
 "genomic-foundation": dict(
   lay="Turns raw sequencing reads into a list of the specific letters where a person's genome differs from the reference.",
   clinical="Every downstream answer — which variant, which drug, which trial — depends on this list being right.",
   limit="Alignment and variant calling require NVIDIA Parabricks, which is not installed on this box. Results shown today are pre-computed.",
   concept="A variant is a difference from a reference sequence. Most differences mean nothing; a few change a protein's shape, and a very few cause disease."),
 "precision-intelligence": dict(
   lay="The evidence layer. You ask a question in plain English and it retrieves what is known, with citations.",
   clinical="It is the difference between a variant list and an interpretation. It connects a letter change to published clinical significance.",
   limit="Retrieval quality is bounded by what has been indexed. An unseeded collection returns nothing — that is a data problem, not a reasoning failure.",
   concept="Retrieval-augmented generation: find the relevant evidence first, then reason over it, then cite it. The citation is what makes it checkable."),
 "therapeutic-discovery": dict(
   lay="Designs new candidate molecules shaped to fit a specific protein, and scores how well each might bind.",
   clinical="It attacks the hardest question in drug discovery — which molecule to even try — at the very front of a 10-15 year pipeline.",
   limit="Molecule generation (MolMIM) and docking (DiffDock) are gated NVIDIA NIMs and are not installed. Candidates shown are pre-computed. This is the flagship demo and the easiest to overclaim.",
   concept="Most medicines work by locking onto one specific protein. If you know the protein's shape, you can search for molecules that fit it."),
 "clinical-imaging": dict(
   lay="Reads medical scans and produces a graded, structured report a radiologist can act on.",
   clinical="Coronary CT to CAD-RADS 2.0 with modifiers, then a named genomic follow-up — imaging and genetics reasoning about the same patient.",
   limit="CAD-RADS is a reporting standard, not a diagnosis. The report supports a clinician's read; it does not replace it.",
   concept="Structured reporting turns 'there is narrowing' into a category everyone interprets the same way, which is what makes it actionable."),
 "precision-oncology": dict(
   lay="Takes a tumour's molecular profile and lays out the therapy options with the strength of evidence behind each.",
   clinical="A molecular tumour board compresses weeks of cross-specialty review; showing the evidence tier is what clinicians actually trust.",
   limit="Trial matching is informational. Therapy selection remains the treating oncologist's decision.",
   concept="Not all evidence is equal. FDA-approved, off-label with data, and trial-only are three different answers to the same question."),
 "cardiology": dict(
   lay="Turns cardiac data into a structured risk assessment with the reasoning shown.",
   clinical="Risk only matters if it changes management. Pair it with imaging findings and pharmacogenomics to decide whether a given statin will work.",
   limit="Risk scores are population statistics applied to an individual. They inform, they do not determine.",
   concept="A risk score is a probability, not a prophecy — and its value is in whether it changes what you do next."),
 "structural-biology": dict(
   lay="Works with the three-dimensional shape of proteins — searching, scoring and designing against them.",
   clinical="A drug has to physically fit its target. Knowing the shape, atom by atom, is what makes rational design possible.",
   limit="ESMFold prediction and ProteinMPNN design need CUDA; this box runs a CPU-only PyTorch build. Structures shown are deposited PDB entries, not predictions made live.",
   concept="Protein function follows shape. Cryo-electron microscopy and related methods let us see that shape and deposit it publicly in the Protein Data Bank."),
 "single-cell": dict(
   lay="Takes a sample of thousands of individual cells and works out how many distinct cell types are present.",
   clinical="Bulk measurements average across cell types and hide the population that matters. Single-cell resolution recovers it.",
   limit="Cluster annotation is by marker-gene overlap against a canonical panel. It is a strong heuristic, not a ground truth.",
   concept="Cluster first, then name. Cells that behave alike group together; matching those groups to known marker genes tells you what they are."),
 "cart": dict(
   lay="Reasons about engineered T-cell therapies — which construct, for which patient, with which risks.",
   clinical="CAR-T is powerful and dangerous in the same breath. Construct choice and its safety counterweight belong in the same conversation.",
   limit="On-target off-tumour toxicity and cytokine release are real. Any construct suggestion carries its monitoring requirement.",
   concept="A chimeric antigen receptor is a designed protein that teaches a patient's own T-cells to recognise a target on cancer cells."),
 "precision-biomarker": dict(
   lay="Identifies measurable markers that predict how a disease will behave or how a patient will respond.",
   clinical="Predictive and prognostic are different questions. Conflating them changes the wrong decision.",
   limit="Many biomarker inputs are research- or trial-use, not validated for routine clinical practice.",
   concept="Prognostic tells you the likely course. Predictive tells you whether a specific treatment will work. Only one of those chooses a therapy."),
 "pharmacogenomics": dict(
   lay="Explains why two patients given the same dose of the same drug can have completely different outcomes.",
   clinical="Genotype-guided dosing has CPIC guidelines behind it. For DPYD and fluorouracil the stakes are toxicity, not efficacy.",
   limit="CPIC guidance covers specific gene-drug pairs. Substrate relationships outside those pairs are pharmacology, not guideline-backed dosing advice.",
   concept="Enzymes that metabolise drugs vary between people. If yours works faster or slower than average, a standard dose is the wrong dose."),
 "precision-autoimmune": dict(
   lay="Reasons about autoimmune disease — where the immune system attacks the body it should protect.",
   clinical="Intervening before the next flare beats treating after it. That requires reading trajectory, not just current state.",
   limit="Decision support only; autoimmune management is highly individual and specialist-led.",
   concept="Autoimmunity is a targeting failure: the defence network described in basic immunology turns on self."),
 "neurology": dict(
   lay="Supports neurological assessment and the decisions that follow it.",
   clinical="In stroke, structured scoring and time-to-decision are the outcome. Consistency of assessment matters as much as speed.",
   limit="Scales such as NIHSS are clinician-administered instruments. The agent supports their interpretation, it does not perform the examination.",
   concept="Neurological assessment is systematic, not intuitive — a defined scale makes findings comparable between clinicians and across time."),
 "clinical-trial": dict(
   lay="Finds the trials a patient may be eligible for, and what a candidate molecule would need to enter one.",
   clinical="Trial matching closes the loop: a discovered molecule is only a hypothesis until there is a path to test it in people.",
   limit="Matching is informational. Eligibility is determined by the trial investigators, not by this agent.",
   concept="Every approved medicine passed through staged human trials. Matching a patient to an open trial is often the only route to a new option."),
 "rare-disease-diagnostic": dict(
   lay="Takes a set of observed clinical features and produces a ranked list of conditions that could explain them.",
   clinical="The diagnostic odyssey averages years. Compressing it is the mission of this platform in a single agent.",
   limit="A ranked differential is a starting point for investigation, never a diagnosis.",
   concept="Phenotype terms (HPO) turn 'unusual facial features and seizures' into structured data a computer can reason over."),
 "single-cell-agent": dict(
   lay="Interprets what single-cell clustering results mean clinically.",
   clinical="The engine computes; the agent explains. Nine clusters are a result — what they imply for this patient is an interpretation.",
   limit="Interpretation rests on the quality of the upstream clustering and the marker panel used.",
   concept="Computation and interpretation are separate jobs, and keeping them separate is what makes each one checkable."),
 "tuberous-sclerosis": dict(
   lay="The whole factory applied to one disease: tuberous sclerosis complex, a genetic condition causing growths across multiple organs.",
   clinical="Five disease-specific agents compose the horizontal engines — variant curation, trajectory, therapeutics, phenotype mapping and TAND surveillance.",
   limit="Gene-therapy correction of TSC1/TSC2 is preclinical — an open design bench, not a cure today. Pediatric caution at full force. Decision support, never prescribing.",
   concept="TSC1 and TSC2 act as a brake on mTOR, a growth pathway. Lose the brake and growth runs unchecked — which is why an mTOR inhibitor helps."),
}


def ctx(f):
    key = f["slug"]
    if key == "single-cell" and f["kind"] == "agent":
        key = "single-cell-agent"
    return CONTEXT[key]


def endpoints_block(f):
    if not f["capabilities"]:
        return "_No capability is registered for this subject in `lib/hcls_common/capabilities.json`._"
    rows = ["| Capability | Type | Status | Endpoint |", "|---|---|---|---|"]
    for c in f["capabilities"]:
        rows.append(f"| `{c['id']}` | {c['type']} | **{c['status']}** | {c['endpoint'] or '—'} |")
    return "\n".join(rows)


def ports_line(f):
    if f["ui_port"] and f["api_port"]:
        return f"**UI :{f['ui_port']} · API :{f['api_port']}** (platform convention: registry endpoint is the UI, API is UI + 1)"
    if f["ui_port"]:
        return f"**:{f['ui_port']}** — a single-service portal, so there is no separate API port"
    return "_No service port — this subject exposes no single registered endpoint._"


def overview(f):
    c = ctx(f)
    return f"""# {f['title']} — Overview

**Kind:** {f['kind']} · **Demo:** `{f['demo_key']}` · **Source:** `{f['path']}`

## What it is

{c['lay']}

## Why it matters

{c['clinical']}

{DISCLAIMER}

## Honest limit

{c['limit']}

## Endpoints

{ports_line(f)}

{endpoints_block(f)}

## Size and health

| | |
|---|---|
| Python files | {f['py_files']} |
| Lines of code | {f['loc']:,} |
| Test files | {f['test_files']} |
| Containerised | {'yes' if f['has_docker'] else 'no'} |

Verify at any time:

```bash
.venv/bin/python scripts/run_all_tests.py {f['slug']}
```

## Where to go next

- [Foundation Learning Guide](FOUNDATION.md) — the concepts, no prior knowledge assumed
- [Advanced Learning Guide](ADVANCED.md) — architecture, modules, extension points
- [Demo Guide](DEMO.md) — how to run `{f['demo_key']}`
"""


def foundation(f):
    c = ctx(f)
    return f"""# {f['title']} — Foundation Learning Guide

For a reader with no background in this area. If you have watched the Foundations film series, this
follows directly from it.

## The one idea to hold

{c['concept']}

## What this subject does with that idea

{c['lay']}

{c['clinical']}

{DISCLAIMER}

## What it cannot do

{c['limit']}

Stating the limit is not a disclaimer bolted on the end — it is how you tell a tool that helps from
a tool that misleads.

## Vocabulary you will meet

| Term | Plain meaning |
|---|---|
| Capability | One named thing the platform can do, registered in `capabilities.json` |
| `live` / `planned` | Whether a capability actually answers today, or is intended |
| Decision support | Output that informs a clinician; it never decides |
| LIVE / REPRESENTATIVE / BURST | Whether a demo ran now, was pre-computed, or ran on remote GPUs |

## Try it

The demo for this subject is **`{f['demo_key']}`**:

```bash
.venv/bin/python scripts/run_demo.py {f['demo_key']}
```

If it reports `BLOCKED`, the message names exactly what is missing. That is intentional — a demo
that cannot run says so rather than showing you something canned.

## Next

[Advanced Learning Guide](ADVANCED.md) · [Demo Guide](DEMO.md)
"""


def advanced(f):
    c = ctx(f)
    mods = []
    for m in f["modules"][:5]:
        syms = ", ".join(f"`{s['name']}`" for s in m["symbols"][:6]) or "_no public symbols_"
        mods.append(f"### `{m['path']}`\n\n{syms}\n")
        for s in m["symbols"][:4]:
            if s["doc"]:
                mods.append(f"- **`{s['name']}`** — {s['doc']}")
        mods.append("")
    deps = ", ".join(f"`{d}`" for d in f["dependencies"][:14]) or "_none declared_"
    return f"""# {f['title']} — Advanced Learning Guide

For engineers extending or operating this subject.

**Source:** `{f['path']}` · {f['py_files']} Python files · {f['loc']:,} LOC · {f['test_files']} test files

## Registered capabilities

{endpoints_block(f)}

{ports_line(f)}

## Principal modules

{chr(10).join(mods)}

## Dependencies

{deps}

## Running the tests

```bash
.venv/bin/python scripts/run_all_tests.py {f['slug']}
```

Two traps the shared harness handles, which a hand-rolled `pytest` invocation will not:

1. Several subjects ship `src/collections.py`, which **shadows the Python standard library**. Putting
   their `src/` on `PYTHONPATH` kills the interpreter before collection.
2. `structural-biology/vendor_rfdiffusion/` is vendored third-party code needing gated GPU packages
   and is excluded.

## Operational notes

{c['limit']}

Before changing a port, read [`../../build/PORT_MAP.md`](../../build/PORT_MAP.md). The convention is
enforced by `scripts/validate_registry.py`, which also cross-checks `health-monitor.sh` — a port
change in one place and not the other fails the build.

## Extending it

1. Add or change code under `{f['path']}`.
2. Keep the capability entry in `lib/hcls_common/capabilities.json` truthful — **a `live` status must
   answer a health probe**. Two capabilities were found registered `live` with nothing bound to their
   ports; do not add a third.
3. Run the gate: `ruff`, `pytest lib/hcls_common`, `validate_registry.py`, `run_all_tests.py`.
"""


def demo_guide(f):
    c = ctx(f)
    return f"""# {f['title']} — Demo Guide

**Demo key:** `{f['demo_key']}` · full specification in
[`../../demos/DEMO_CATALOG.md`](../../demos/DEMO_CATALOG.md)

## Run it

```bash
.venv/bin/python scripts/run_demo.py {f['demo_key']}
```

Check prerequisites without running anything:

```bash
.venv/bin/python scripts/run_demo.py --check-all
```

## What the audience is seeing

{c['lay']}

{c['clinical']}

## Say this out loud

{DISCLAIMER}

**{c['limit']}**

The label matters. **LIVE** means it ran, now, on real input, in front of the room. **REPRESENTATIVE**
means a pre-computed or curated result is standing in for a long or gated step — and you say so.
**BURST** means it ran live but on remote GPUs, which is "elastic burst", not "all on one box".

## If it will not run

The runner refuses to execute a demo declared LIVE whose service is unreachable, rather than quietly
degrading to a canned result. The failure message names the missing prerequisite:

- a service not listening → start it (`docker compose -f docker-compose.dgx-spark.yml up -d`)
- a missing Python package → install it
- a gated component → see [`../../build/GATED_SOFTWARE_BUILD_GUIDE.md`](../../build/GATED_SOFTWARE_BUILD_GUIDE.md)

## Transcript

Each run writes `demo/transcripts/{f['demo_key']}.txt`. Diff it after a change — a silent regression
shows up there before anyone notices it on stage.
"""


def main():
    facts = json.loads(subprocess.run(
        [sys.executable, str(ROOT / "scripts/subject_facts.py"), "--json", "/dev/stdout"],
        capture_output=True, text=True).stdout.split("wrote")[0] or "[]")
    if not facts:
        # fall back to the cached extract
        facts = json.loads((ROOT / "tmp/batch-01-run/subject-facts.json").read_text())
    only = [a for a in sys.argv[1:] if not a.startswith("--")]
    n = 0
    for f in facts:
        if only and not any(o in f["slug"] for o in only):
            continue
        key = f["demo_key"].lower()
        d = OUT / f"{key}-{f['slug']}"
        d.mkdir(parents=True, exist_ok=True)
        for name, fn in (("OVERVIEW.md", overview), ("FOUNDATION.md", foundation),
                         ("ADVANCED.md", advanced), ("DEMO.md", demo_guide)):
            (d / name).write_text(fn(f))
            n += 1
        print(f"  {f['demo_key']:4s} {f['slug']:26s} -> docs/subjects/{d.name}/  (4 guides)")
    print(f"\n{n} documents written")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
